DFE-Digital/npq-registration

- Gemfile
- Gemfile.lock
- config/environments/production.rb
Copy ECF and E&L and use lograge to make logs more palpitate. 
Deploy to production and inspect logs
> Use lograge in production

- .github/workflows/deploy_to_dev.yml
- .github/workflows/promote_to_production.yml
- .github/workflows/promote_to_staging.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- config/initializers/filter_parameter_logging.rb
- config/initializers/sentry.rb
- config/manifests/dev-manifest.yml
- config/manifests/prod-manifest.yml
- config/manifests/staging-manifest.yml
> Add Sentry

- app/views/layouts/application.html.erb
- app/views/pages/privacy_policy.html.erb
- config/routes.rb
- spec/features/privacy_policy_spec.rb
> Add Privacy Policy

- config/manifests/dev-manifest.yml
- config/manifests/prod-manifest.yml
- config/manifests/staging-manifest.yml
Add worker process with 1 instance on dev and staging, and 2 on production.
> Add DJ worker process

- app/lib/forms/check_answers.rb
- spec/features/happy_journeys_spec.rb
> Async application submission

- app/views/layouts/application.html.erb
- app/views/pages/accessibility.html.erb
- config/routes.rb
- spec/features/accessibility_statement_spec.rb
> Add accessibility statement

- Gemfile.lock
- app/lib/forms/about_npq.rb
- app/lib/forms/provider_check.rb
- app/models/registration_wizard.rb
- app/views/registration_wizard/about_npq.html.erb
- app/views/registration_wizard/provider_check.html.erb
- app/views/registration_wizard/start.html.erb
- config/locales/en.yml
- spec/features/back_links_spec.rb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- spec/features/validations_spec.rb
- spec/lib/forms/provider_check_spec.rb
> Add provider check page

- app/lib/forms/choose_your_provider.rb
- app/lib/forms/contact_details.rb
- app/views/registration_wizard/change_dqt.html.erb
- app/views/registration_wizard/choose_your_provider.html.erb
- app/views/registration_wizard/confirm_email.html.erb
- app/views/registration_wizard/confirmation.html.erb
- app/views/registration_wizard/contact_details.html.erb
- app/views/registration_wizard/not_updated_name.html.erb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
> Prototype copy updates

- app/lib/forms/check_answers.rb
- app/lib/forms/qualified_teacher_check.rb
- app/lib/services/npq_profile_creator.rb
- db/migrate/20210623090146_add_active_alert_to_user.rb
- db/schema.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
- spec/lib/services/npq_profile_creator_spec.rb
- spec/support/dqt_responses.rb
> Store and communicate active alert to ECF

- app/views/registration_wizard/confirmation.html.erb
- spec/features/happy_journeys_spec.rb
> Update confirmation page copy

- app/lib/forms/choose_your_provider.rb
- app/lib/forms/headteacher_duration.rb
- app/models/registration_wizard.rb
- app/views/registration_wizard/headteacher_duration.html.erb
- spec/features/happy_journeys_spec.rb
> Headship changes

- app/lib/forms/resend_code.rb
- app/views/layouts/application.html.erb
- app/views/registration_wizard/confirm_email.html.erb
- app/views/registration_wizard/resend_code.html.erb
- config/locales/en.yml
- spec/features/email_confirmation_spec.rb
> Confirm email tweaks

- app/jobs/application_submission_job.rb
- app/mailers/application_submission_mailer.rb
- spec/jobs/application_submission_job_spec.rb
> Send confirmation email on registration

- app/views/layouts/application.html.erb
> add extra content to footer

- app/views/layouts/application.html.erb
> populate alpha feedback link with mailto

- app/models/school.rb
- spec/models/school_spec.rb
- spec/requests/schools_spec.rb
> improve school searching by name

- app/views/registration_wizard/about_npq.html.erb
- db/migrate/20210624102737_update_lead_provider_names.rb
- db/schema.rb
- db/seeds.rb
> Update lead provider names

- app/views/registration_wizard/name_changes.html.erb
- app/views/registration_wizard/not_sure_updated_name.html.erb
- app/views/registration_wizard/updated_name.html.erb
> Change DQT to Teaching Regulation Agency records

- app/jobs/application_submission_job.rb
- app/lib/services/ecf_user_finder.rb
- spec/jobs/application_submission_job_spec.rb
- spec/lib/services/ecf_user_finder_spec.rb
- Do not merge this until https://github.com/DFE-Digital/early-careers-framework/pull/584 is in production
> handle if user email already exists in ECF

- app/lib/forms/share_provider.rb
> Fix share provider previous step

- config/manifests/staging-manifest.yml
> Temporarily use ECF test environment

- app/models/dqt_record.rb
- spec/models/dqt_record_spec.rb
> DQT NI numbers can be cased anyway

- app/lib/forms/qualified_teacher_check.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
> legacy TRNs and DQT api

- app/models/dqt_record.rb
- spec/models/dqt_record_spec.rb
> prevent users using null to match NI number

- app/lib/services/import_gias_schools.rb
- spec/lib/services/ecf_user_finder_spec.rb
- spec/lib/services/import_gias_schools_spec.rb
> Fix gias import

- app/lib/forms/qualified_teacher_check.rb
- app/views/registration_wizard/qualified_teacher_check.html.erb
- config/locales/en.yml
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
> trn must now be 7 digits only

- .github/workflows/test.yml
> run rubocop as part of CI

- Gemfile.lock
- app/controllers/csp_reports_controller.rb
- config/initializers/rack_attack.rb
> Decrease rate limit thresholds

- config/application.rb
This was reported as part of the pentest
> Set X-XSS-Protection header to 0

- app/lib/forms/check_answers.rb
- app/lib/forms/choose_school.rb
- app/lib/forms/choose_your_npq.rb
- app/lib/services/funding_eligibility.rb
- spec/lib/services/funding_eligibility_spec.rb
> update rules for NPQH funding

- config/initializers/rack_attack.rb
> Rate limit change routes

- config/initializers/rack_attack.rb
> Throttle correct session route

- app/views/registration_wizard/start.html.erb
> Remove link to check application status

- app/lib/forms/contact_details.rb
- app/lib/forms/resend_code.rb
- app/views/registration_wizard/about_npq.html.erb
- app/views/registration_wizard/dont_have_teacher_reference_number.html.erb
- app/views/registration_wizard/dont_know_teacher_reference_number.html.erb
- app/views/registration_wizard/name_changes.html.erb
- app/views/registration_wizard/qualified_teacher_check.html.erb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
> Various copy updates to reflect prototype

- app/views/registration_wizard/dqt_mismatch.html.erb
> DQT content updates

- .github/workflows/deploy_to_dev.yml
- Dockerfile
- docker-compose.yml
> expose git commit sha in env var and file

- Dockerfile
> move GIT_COMMIT_SHA to main image

- config/initializers/sentry.rb
> enable release tracking for sentry

- app/controllers/monitoring_controller.rb
> expose git sha and docker image id to healthcheck

- app/lib/forms/qualified_teacher_check.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
> rescue incase DQT lookup fails

- .github/workflows/deploy_to_dev.yml
- .github/workflows/update_schools.yml
- Couldn't find a decent delayed job scheduling library so I've done it via github and cloudfoundry instead
> School import schedule

- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/registration_wizard/contact_details.html.erb
- app/views/registration_wizard/dqt_mismatch.html.erb
- app/views/registration_wizard/not_sure_updated_name.html.erb
- app/views/registration_wizard/provider_check.html.erb
- app/views/registration_wizard/school_not_in_england.html.erb
- app/views/registration_wizard/share_provider.html.erb
- app/views/registration_wizard/teacher_reference_number.html.erb
- app/views/registration_wizard/updated_name.html.erb
- app/views/session_wizard/sign_in.html.erb
- config/locales/en.yml
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
> use smart apostrophes

- app/views/registration_wizard/about_npq.html.erb
- app/views/registration_wizard/dont_have_teacher_reference_number.html.erb
- app/views/registration_wizard/dont_know_teacher_reference_number.html.erb
> Copy updates

- app/lib/forms/headteacher_duration.rb
- app/lib/services/funding_eligibility.rb
- app/models/registration_wizard.rb
- app/views/registration_wizard/headteacher_duration.html.erb
- spec/features/happy_journeys_spec.rb
- spec/lib/services/funding_eligibility_spec.rb
- Add another fundable option to headship question
- ECF side already in place as part of https://github.com/DFE-Digital/early-careers-framework/pull/613/files
> Add 4th fundable option to headship question

- db/migrate/20210701145259_add_school_search_indexes.rb
- db/schema.rb
```sql
Limit  (cost=10431.79..10431.80 rows=1 width=251)
->  Sort  (cost=10431.79..10431.80 rows=1 width=251)
Sort Key: (ts_rank((((((((to_tsvector('simple'::regconfig, COALESCE(schools_1.la_name, ''::text)) || to_tsvector('simple'::regconfig, COALESCE(schools_1.address_1, ''::text))) || to_tsvector('simple'::regconfig, COALESCE(schools_1.address_2, ''::text))) || to_tsvector('simple'::regconfig, COALESCE(schools_1.address_3, ''::text))) || to_tsvector('simple'::regconfig, COALESCE(schools_1.town, ''::text))) || to_tsvector('simple'::regconfig, COALESCE(schools_1.county, ''::text))) || to_tsvector('simple'::regconfig, COALESCE(schools_1.postcode, ''::text))) || to_tsvector('simple'::regconfig, COALESCE(schools_1.region, ''::text))), '''london'''::tsquery, 0)) DESC, schools.id, …
```
> add index for school name searching

- app/views/registration_wizard/choose_school.html.erb
- app/views/registration_wizard/choose_your_npq.html.erb
- app/views/registration_wizard/choose_your_provider.html.erb
- app/views/registration_wizard/confirm_email.html.erb
- app/views/registration_wizard/contact_details.html.erb
- app/views/registration_wizard/find_school.html.erb
- app/views/registration_wizard/funding_your_npq.html.erb
- app/views/registration_wizard/headteacher_duration.html.erb
- app/views/registration_wizard/name_changes.html.erb
- app/views/registration_wizard/not_updated_name.html.erb
- app/views/registration_wizard/provider_check.html.erb
- app/views/registration_wizard/qualified_teacher_check.html.erb
- app/views/registration_wizard/resend_code.html.erb
- app/views/registration_wizard/share_provider.html.erb
- app/views/registration_wizard/start.html.erb
- app/views/registration_wizard/teacher_reference_number.html.erb
- app/views/registration_wizard/updated_name.html.erb
- app/views/session_wizard/sign_in.html.erb
- app/views/session_wizard/sign_in_code.html.erb
> add Error to page title if there is an error

- app/lib/services/report.rb
- app/models/application.rb
- spec/jobs/application_submission_job_spec.rb
- spec/lib/services/npq_profile_creator_spec.rb
> add stop gap csv report generator

- app/lib/forms/check_answers.rb
- app/lib/forms/qualified_teacher_check.rb
- app/lib/services/participant_validator.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- spec/lib/forms/check_answers_spec.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
- spec/lib/services/participant_validator_spec.rb
- spec/support/api_responses.rb
- depends on https://github.com/DFE-Digital/early-careers-framework/pull/636 which must be deployed to production first
> Participant validation

- app/views/registration_wizard/find_school.html.erb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
> copy tweak for first school search page

- app/webpacker/packs/application.js
- package.json
- yarn.lock
> fix school autocomplete to work with IE11

- .github/workflows/promote_to_sandbox.yml
- .github/workflows/update_schools.yml
- config/manifests/sandbox-manifest.yml
> add github flow to handle sandbox

- app/controllers/csp_reports_controller.rb
- spec/requests/csp_reports_spec.rb
> disable csrf token check for /csp_reports

- .github/workflows/generate_dashboard_report.yml
- app/jobs/dashboard_report_job.rb
- app/models/report.rb
- db/migrate/20210719104504_create_reports.rb
- db/schema.rb
- spec/jobs/dashboard_report_job_spec.rb
- Generate CSV dashboard report
- So later it can be exported to BigQuery
> Automate reporting

- app/lib/forms/qualified_teacher_check.rb
- app/views/registration_wizard/qualified_teacher_check.html.erb
- config/locales/en.yml
- spec/lib/forms/qualified_teacher_check_spec.rb
> relax trn length validation from 7 to 5-7

- .github/workflows/export_dashboard_report.yml
> export dashboard report to BigQuery

- app/models/registration_wizard.rb
- On error catch the DOB value to help debug error being raised
> add extra debug info around dob

- app/lib/forms/base.rb
- app/lib/forms/qualified_teacher_check.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
- this should help improve auto TRN validation
> strip whitespace from fields

- app/lib/forms/headteacher_duration.rb
- app/views/registration_wizard/headteacher_duration.html.erb
- spec/features/happy_journeys_spec.rb
> copy changes to headteacher status page

- app/lib/forms/check_answers.rb
- app/lib/forms/qualified_teacher_check.rb
- app/lib/services/report.rb
- db/migrate/20210802094543_add_trn_auto_verified_to_users.rb
- db/schema.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
- spec/lib/services/importers/manual_validation_spec.rb
- for reporting we want to track if a trn was auto validated or not
- add additional column so we can track if a trn was auto verified/validated or not
> Flag for auto trn validation

- app/views/registration_wizard/qualified_teacher_check.html.erb
- copy change
- update hint text for NI number
- none
> Update hint text for NI number

- .rubocop.yml
- app/lib/services/exporters/revalidate_applications.rb
- Sometimes TRA/DQT api is not available
- This causes auto validations to fail
- Add a service class that can be called to bulk re-validate TRNs in a batch
- none
> add script to revalidate applications

- app/lib/services/exporters/revalidate_applications.rb
> fix class namespace

- app/lib/forms/funding_your_npq.rb
- app/models/registration_wizard.rb
- app/views/registration_wizard/about_npq.html.erb
- app/views/registration_wizard/choose_school.html.erb
- app/views/registration_wizard/choose_your_provider.html.erb
- app/views/registration_wizard/dont_have_teacher_reference_number.html.erb
- app/views/registration_wizard/dont_know_teacher_reference_number.html.erb
- app/views/registration_wizard/find_school.html.erb
- app/views/registration_wizard/funding_your_npq.html.erb
- app/views/registration_wizard/name_changes.html.erb
- app/views/registration_wizard/not_sure_updated_name.html.erb
- app/views/registration_wizard/qualified_teacher_check.html.erb
- app/views/registration_wizard/school_not_in_england.html.erb
- app/views/registration_wizard/share_provider.html.erb
- app/views/registration_wizard/start.html.erb
- app/views/registration_wizard/teacher_reference_number.html.erb
- app/views/registration_wizard/updated_name.html.erb
- app/webpacker/packs/application.js
- config/locales/en.yml
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- Update copy change around the introduction of FE into the service
- Copy changes to mostly match the prototype
- none
> Update copy around adding FE

- app/lib/forms/choose_school.rb
- spec/lib/forms/choose_school_spec.rb
- For sandbox we have test schools with 7 digit urns
- Permits schools with 7 digit urns
- none
> permit seven digit urns for sandbox usage

- .github/workflows/export_dashboard_report.yml
- .github/workflows/generate_dashboard_report.yml
- fix broken github workflow syntax
- n/a
- n/a
> fix workflow syntax

- app/views/registration_wizard/about_npq.html.erb
- app/webpacker/styles/application.scss
> remove bullet style of parent of nested list

- app/views/registration_wizard/check_answers.html.erb
Make sure the links are the right blue colour
| Before | After |
| -- | -- |
| ![Screenshot 2021-09-09 at 15 24 44](https://user-images.githubusercontent.com/319055/132704396-8e0c7133-2ead-4595-8af0-b2759305a988.png) | ![Screenshot 2021-09-09 at 15 24 22](https://user-images.githubusercontent.com/319055/132704403-8d5f1d89-d313-4fe7-a064-8d5a904ba33e.png) |
> Use govuk_link_to helper on change links

- .github/workflows/schedule_sweep_stale_sessions.yml
- app/jobs/sweep_stale_sessions_job.rb
- spec/jobs/sweep_stale_sessions_job_spec.rb
- Sessions are now server side and therefore need pruning once stale
- Prune any stale sessions last updated over 15 days ago
- none
> schedule job to sweep stale sessions

- app/lib/forms/contact_details.rb
- app/lib/forms/resend_code.rb
- app/views/layouts/application.html.erb
- app/views/registration_wizard/headteacher_duration.html.erb
- app/views/registration_wizard/name_changes.html.erb
- app/views/registration_wizard/not_sure_updated_name.html.erb
- app/views/registration_wizard/school_not_in_england.html.erb
- app/views/registration_wizard/share_provider.html.erb
- app/views/registration_wizard/teacher_reference_number.html.erb
- app/views/registration_wizard/updated_name.html.erb
- spec/lib/forms/contact_details_spec.rb
There are many uses of smart quotes already, but there were some inconsistencies.
> Use smart quotes consistently

- app/lib/services/funding_eligibility.rb
- spec/lib/services/funding_eligibility_spec.rb
- Certain URNs which are FE related are eligible for funding regardless of course taken
- short circuit special urns to be eligible for funding
- none
> certain urns are eligible for funding

- package.json
- yarn.lock
- remove a js dependency that does not appear to be needed or used
- remove js dependency
- none
> remove set-value js dependency

- app/views/registration_wizard/dqt_mismatch.html.erb
- Copy changes to better explain manual validation process
- minor copy change
- none
> copy change for manual validation process

- .github/workflows/test.yml
- Gemfile
- Gemfile.lock
- config/brakeman.ignore
- add brakeman to CI suite
- added brakeman to CI suite
- test were run with an error which causes build to fail
- adding ignore file caused build to pass
> add brakeman

- app/views/registration_wizard/funding_your_npq.html.erb
- Copy change to align service copy to refer to `DfE scholarship funding`
- Change copy
- none
> copy update: use DfE scholarship on funding choice

- app/lib/forms/dqt_mismatch.rb
- spec/lib/forms/dqt_mismatch_spec.rb
https://dfedigital.atlassian.net/browse/CST-270
> Skipping find_school step after dqt_mismatch when not working in school

- app/views/interest_notification_sign_up/confirm.html.erb
- app/views/registration_interest/confirm.html.erb
A couple minor changes were spotted when checking on staging.
> Remove full stop from confirm screen

- app/lib/services/exporters/manual_validation.rb
To aid resolving manual validation queries we've been asked to include email address in the export
> add email to manual validation exporter

- app/views/registration_wizard/work_in_school.html.erb
Update copy for "Do you work in a school?" question.
> [CN-117] - Update copy for “work in school?” question

- app/lib/forms/choose_your_npq.rb
- app/models/course.rb
- app/views/registration_wizard/choose_your_npq.html.erb
- db/migrate/20220503111659_add_position_to_courses.rb
- db/migrate/20220503114606_add_display_to_courses.rb
- db/schema.rb
- db/seeds.rb
- spec/features/happy_journeys_non_js_spec.rb
- Added new NPQ courses plus other minor tweaks so unblock development of courses
- add new NPQ courses
- this unblocks other journeys for development
- tests are pended and will need updating to reflect new requirements
- added ability to hide courses
- added ability to render courses in desired order
- Assuming everything has been seeded
- Go through the journey
- When choosing NPQ
- Should see new courses
- Should not see ASO course
- Courses should be ordered correctly
- Selecting a new course will likely not take you to correct journey as it is yet to be implemented
> Add new courses

- app/lib/forms/confirmation.rb
- app/views/registration_wizard/confirmation.html.erb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- Adds EHCO information to confirmation page
- Complete flow through to confirmation page with non-EHCO NPQ to see that EHCO information is not added to the page.
- Complete flow through to confirmation page with EHCO NPQ to see that EHCO information is added to the page.
> [CN-91] Update confirmation page with EHCO information

- app/lib/forms/teacher_reference_number.rb
- app/views/registration_wizard/teacher_reference_number.html.erb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- Update copy for TRN page
- Follow questionnaire through to TRN page as someone from England
- Follow questionnaire through to TRN page as someone from Scotland
- See differing copy for each
> [CN-117] Update TRN page

- app/views/registration_wizard/choose_your_provider.html.erb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
Updates copy on the select your provider page
Move through the flow to the select your provider page to check that copy matches flowchart on the ticket.
> [CN-96] Update Select your Provider page copy

- app/lib/forms/aso_new_headteacher.rb
- app/lib/forms/choose_your_npq.rb
- app/lib/forms/choose_your_provider.rb
- app/lib/services/funding_eligibility.rb
- app/lib/services/handle_submission_for_store.rb
- app/models/application.rb
- app/models/registration_wizard.rb
- spec/lib/forms/choose_your_provider_spec.rb
- spec/lib/services/funding_eligibility_spec.rb
- spec/lib/services/handle_submission_for_store_spec.rb
- spec/models/application_spec.rb
Several upcoming tickets require more granular information related to funding eligiblity.
Generate funding eligibility reasons when calculating funding eligibility.
> Generate funding eligibility reasons

- app/lib/forms/aso_headteacher.rb
- app/lib/forms/aso_new_headteacher.rb
- app/views/registration_wizard/aso_new_headteacher.html.erb
- app/views/registration_wizard/aso_unavailable.html.erb
- app/views/registration_wizard/contact_details.html.erb
- app/views/session_wizard/sign_in.html.erb
- spec/features/admin_spec.rb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- spec/features/sessions_spec.rb
Updates copy to match prototypes
> [CN-119] [CN-118] [CN-116] Update copy on EHCO and Email pages

- app/views/registration_wizard/possible_funding/_private_childcare_provider.html.erb
- app/views/registration_wizard/possible_funding/_school.html.erb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
[Ticket](https://dfedigital.atlassian.net/browse/CN-98)
The funding copy for the EY or childcare is not correct.
Update the copy to match the prototype
> Update the Early Years funding copy

- app/lib/forms/funding_your_npq.rb
- app/views/registration_wizard/funding_your_npq.html.erb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
[Ticket CN-97](https://dfedigital.atlassian.net/browse/CN-97)
We want to simplify the copy in the "How are you paying" page.
Update the page to match the flowchart
Go through the School and Early Years journeys and choose ineligible workplaces and a NPQ course other than ASO/EHCO. Keep going until you reach the "How are you paying" page and then ensure the content matches the screenshots in the flowchart.
> Update the copy

- app/lib/forms/qualified_teacher_check.rb
- app/views/registration_wizard/about_ehco.html.erb
- app/views/registration_wizard/aso_funding_not_available.html.erb
- app/views/registration_wizard/choose_school.html.erb
- app/views/registration_wizard/choose_your_provider.html.erb
- app/views/registration_wizard/find_school.html.erb
- app/views/registration_wizard/ineligible_for_funding.erb
- app/views/registration_wizard/ineligible_for_funding/early_years/_not_applying_for_NPQEY.html.erb
- app/views/registration_wizard/ineligible_for_funding/early_years/_outside_catchment_or_not_on_early_years_register.html.erb
- app/views/registration_wizard/ineligible_for_funding/school/_has_already_been_funded.html.erb
- app/views/registration_wizard/ineligible_for_funding/school/_outside_catchment_or_ineligible_establishment.html.erb
- app/views/registration_wizard/provider_check.html.erb
- app/views/registration_wizard/qualified_teacher_check.html.erb
- app/views/registration_wizard/resend_code.html.erb
- app/views/registration_wizard/start.html.erb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
- spec/features/service_closed_spec.rb
- spec/lib/forms/qualified_teacher_check_spec.rb
I ran through large parts of the app from start to finish to locate places where copy and functionality matched.
- Correct copy mismatches
- Make National Insurance Number mandatory for users within England
> Update copy around app to match Lucid flowchart

- app/lib/forms/funding_your_npq.rb
- config/locales/en.yml
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
[Ticket](https://dfedigital.atlassian.net/browse/CN-97)
We want to remove the employer option as the the school option suffices.
- remove the employer option. 
- remove the condition from the school option to be always displayed
> Update the funding your npq options

- app/models/course.rb
- app/views/registration_wizard/ineligible_for_funding/early_years/_not_applying_for_NPQEY.html.erb
- spec/lib/services/handle_submission_for_store_spec.rb
There is a typo referring to a non-existent NPQ.
Fix the typo
> [CN-99] Fix typo

- app/lib/forms/dqt_mismatch.rb
- app/views/registration_wizard/have_ofsted_urn.html.erb
- spec/features/happy_journeys_spec.rb
- spec/lib/forms/dqt_mismatch_spec.rb
https://dfedigital.atlassian.net/browse/CN-197
https://dfedigital.atlassian.net/browse/CN-195
- Change question text
- Update dqt_mismatch flow to match qualified_teacher_check flow
> [CN-197] Fix bugs

- app/models/registration_wizard.rb
- app/views/registration_wizard/check_answers.html.erb
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/sad_journeys_spec.rb
[Ticket CN-201](https://dfedigital.atlassian.net/browse/CN-201)
Copy updates in the `Check your answers` page
Update the copy
Go through a journey and confirm the copy is correct when you reach the `Check your answers` page
> Update copy in the check your answers page

- app/lib/services/private_childcare_providers/importer.rb
- lib/private_childcare_providers/2021-08-31/childminder_agencies.csv
- lib/tasks/private_childcare_providers.rake
- spec/fixtures/files/private_childminder_agencies_sample.csv
- spec/fixtures/files/private_childminder_agencies_sample_with_errors.csv
- spec/lib/services/private_childcare_providers/importer_spec.rb
https://dfedigital.atlassian.net/browse/CN-199
Further PrivateChildcareProvider data needs to be imported
- Add support for Childminder Agency data format to PrivateChildcareProvider importer
- Add Childminder Agency data to repo for import
> [CN-199] Add support for Childminder Agencies data in childcare provider importer

- app/models/registration_wizard.rb
- config/locales/en.yml
- spec/features/happy_journeys_non_js_spec.rb
- spec/features/happy_journeys_spec.rb
- spec/features/sad_journeys_spec.rb
Tickets: [CN-202](https://dfedigital.atlassian.net/browse/CN-202), [CN-203](https://dfedigital.atlassian.net/browse/CN-203), [CN-205](https://dfedigital.atlassian.net/browse/CN-205)
We want to update the following questions in the `Check your answers` page 
1. `School or college` 
2. `What kind of nursery do you work in?` 
and add the EHCO questions.
Update the copy and add the EHCO rows.
> Update the content in the check your answers page

- .github/workflows/update_all_schools.yml
- app/jobs/refresh_all_gias_schools_job.rb
https://dfedigital.atlassian.net/browse/CN-222
It was recently found that GIAS data is updating without changing the LastChangedDate.
To easily allow a full refresh of data I've added in this Github Action.
> [CN-222] Add Github Action for refreshing GIAS data manually

- .github/workflows/update_all_schools.yml
- .github/workflows/update_all_schools_test_run.yml
- .github/workflows/update_schools.yml
See https://github.com/DFE-Digital/npq-registration/pull/444 for context.
This adds in an action that runs the download only in dev so we can do a trial run of the download.
> [CN-222] Add school data sync test github action

- lib/tasks/sync_applications.rake
The sync task wasn't properly calling update_column
> Fix sync rake task

- app/views/registration_wizard/about_npq.html.erb
- spec/features/sad_journeys/not_chosen_dqt_or_provider_spec.rb
Make the 'P' in 'provider' lower case:
> this p should not be capitalised

- app/views/registration_wizard/contact_details.html.erb
- app/views/session_wizard/sign_in.html.erb
- spec/features/admin_spec.rb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys/js/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb
- spec/features/happy_journeys/js/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb
- spec/features/happy_journeys/js/changing_from_outside_of_catchment_area_to_inside_spec.rb
- spec/features/happy_journeys/js/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb
- spec/features/happy_journeys/js/via_using_old_name_and_not_headship_spec.rb
- spec/features/happy_journeys/js/via_using_same_name_spec.rb
- spec/features/happy_journeys/js/when_outside_of_catchment_area_crown_dependencies_spec.rb
- spec/features/happy_journeys/js/when_outside_of_catchment_area_spec.rb
- spec/features/happy_journeys/js/when_previously_funded_spec.rb
- spec/features/happy_journeys/js/while_not_currently_working_at_school_spec.rb
- spec/features/happy_journeys/js/while_working_at_private_childcare_privider_but_not_a_nursery_spec.rb
- spec/features/happy_journeys/js/while_working_at_private_nursery_spec.rb
- spec/features/happy_journeys/js/while_working_at_public_nursery_spec.rb
- spec/features/happy_journeys/js/while_working_in_neither_a_school_nor_childcare_spec.rb
- spec/features/happy_journeys/non_js/able_to_receive_targeted_delivery_funding_spec.rb
- spec/features/happy_journeys/non_js/funded_ehco_registration_journey_spec.rb
- spec/features/happy_journeys/non_js/international_teacher_npqh_journey_spec.rb
- spec/features/happy_journeys/non_js/other_funded_ehco_registration_journey_spec.rb
- spec/features/happy_journeys/non_js/via_using_old_name_and_not_headship_spec.rb
- spec/features/happy_journeys/non_js/via_using_same_name_spec.rb
- spec/features/sad_journeys/applying_for_ehco_but_not_new_headteacher_spec.rb
- spec/features/sad_journeys/dqt_mismatch_spec.rb
- spec/features/sad_journeys/school_not_in_england_spec.rb
- spec/features/sad_journeys/works_in_childcare_but_not_in_england_spec.rb
- spec/features/sessions_spec.rb
This quote should be curly:
Like this:
> change straight quotes to curly quotes

- app/views/registration_wizard/choose_childcare_provider.html.erb
- app/views/registration_wizard/choose_school.html.erb
- spec/features/happy_journeys/js/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb
- spec/features/happy_journeys/js/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb
- spec/features/happy_journeys/js/changing_from_outside_of_catchment_area_to_inside_spec.rb
- spec/features/happy_journeys/js/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb
- spec/features/happy_journeys/js/via_using_old_name_and_not_headship_spec.rb
- spec/features/happy_journeys/js/via_using_same_name_spec.rb
- spec/features/happy_journeys/js/while_working_at_public_nursery_spec.rb
- spec/features/happy_journeys/non_js/able_to_receive_targeted_delivery_funding_spec.rb
- spec/features/happy_journeys/non_js/funded_ehco_registration_journey_spec.rb
- spec/features/happy_journeys/non_js/other_funded_ehco_registration_journey_spec.rb
- spec/features/happy_journeys/non_js/via_using_old_name_and_not_headship_spec.rb
- spec/features/happy_journeys/non_js/via_using_same_name_spec.rb
- spec/features/sad_journeys/applying_for_ehco_but_not_new_headteacher_spec.rb
- spec/features/sad_journeys/dqt_mismatch_spec.rb
- spec/features/sad_journeys/school_not_in_england_spec.rb
Correct a couple of rogue straight quotes.
> correct straight quotes

- app/views/registration_wizard/confirm_email.html.erb
- spec/features/email_confirmation_spec.rb
- spec/features/happy_journeys/js/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb
- spec/features/happy_journeys/js/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb
- spec/features/happy_journeys/js/changing_from_outside_of_catchment_area_to_inside_spec.rb
- spec/features/happy_journeys/js/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb
- spec/features/happy_journeys/js/via_using_old_name_and_not_headship_spec.rb
- spec/features/happy_journeys/js/via_using_same_name_spec.rb
- spec/features/happy_journeys/js/when_outside_of_catchment_area_crown_dependencies_spec.rb
- spec/features/happy_journeys/js/when_outside_of_catchment_area_spec.rb
- spec/features/happy_journeys/js/when_previously_funded_spec.rb
- spec/features/happy_journeys/js/while_not_currently_working_at_school_spec.rb
- spec/features/happy_journeys/js/while_working_at_private_childcare_privider_but_not_a_nursery_spec.rb
- spec/features/happy_journeys/js/while_working_at_private_nursery_spec.rb
- spec/features/happy_journeys/js/while_working_at_public_nursery_spec.rb
- spec/features/happy_journeys/js/while_working_in_neither_a_school_nor_childcare_spec.rb
- spec/features/happy_journeys/non_js/able_to_receive_targeted_delivery_funding_spec.rb
- spec/features/happy_journeys/non_js/funded_ehco_registration_journey_spec.rb
- spec/features/happy_journeys/non_js/international_teacher_npqh_journey_spec.rb
- spec/features/happy_journeys/non_js/other_funded_ehco_registration_journey_spec.rb
- spec/features/happy_journeys/non_js/via_using_old_name_and_not_headship_spec.rb
- spec/features/happy_journeys/non_js/via_using_same_name_spec.rb
- spec/features/sad_journeys/applying_for_ehco_but_not_new_headteacher_spec.rb
- spec/features/sad_journeys/dqt_mismatch_spec.rb
- spec/features/sad_journeys/school_not_in_england_spec.rb
- spec/features/sad_journeys/works_in_childcare_but_not_in_england_spec.rb
> change 'confirm your code' to 'confirm your email adress'

- .github/workflows/deploy_to_dev.yml
Testing out auto-tagging during action deployments
> Add deploy tagging to dev auto-deploy

- .github/CODEOWNERS
Now we're moving forwards with continuous deployment it feels like a good idea to ensure at least one dev that's directly involved with this project has approved PRs before they're merged.
> Add `CODEOWNERS` file to the project

- app/lib/services/ecf/npq_profile_creator.rb
- spec/lib/services/ecf/npq_profile_creator_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-581
Sent employment_type to ECF on application persistence.
Depends on https://github.com/DFE-Digital/early-careers-framework/pull/2438
> [CPDNPQ-581] Send employment_type data to ECF

- app/views/registration_wizard/choose_private_childcare_provider.html.erb
- spec/features/happy_journeys/js/when_previously_funded_spec.rb
- spec/features/happy_journeys/js/while_working_at_private_childcare_privider_but_not_a_nursery_spec.rb
- spec/features/happy_journeys/js/while_working_at_private_nursery_spec.rb
use curly quote instead on straight quote - these look different in gov styling
> change employer's to employer‘s

- app/controllers/omniauth_controller.rb
To track failures we need proper error logging
Capture various errors in OmniauthController and send them to Sentry
> Enhance error logging in omniauth controller

- app/lib/services/admin/dashboard_stats.rb
- app/views/admin/show.html.erb
We don't have stats for user counts in the admin interface
Add those stats
> Add stats for user counts

- app/views/admin/applications/show.html.erb
Useful information for debugging is missing
Add the information to the UI
> Add funding_eligiblity_status_code to admin UI

- .github/CODEOWNERS
Sam has joined the team and needs to be able to approve PRs
- Add Sam Johnson to CODEOWNERS
> Add Sam Johnson to CODEOWNERS

- app/lib/forms/choose_your_provider.rb
- app/views/registration_wizard/choose_your_provider.html.erb
- db/migrate/20221130142333_add_hint_to_lead_providers.rb
- db/schema.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-745
- Add hint text column to lead_providers table
- Display hint text on choose your provider page
- Add hint text to School-Led Network LeadProvider record
> [CPDNPQ-745] Add hint text to school-led network lead provider

- .gitignore
- lib/private_childcare_providers/2022-08-31/childminder_agencies.csv
- lib/tasks/private_childcare_providers.rake
Download and format the CSV so can be uploaded and write up the process to complete this in order to help future developers.
> Update the childcare providers URN list

- config/initializers/flipper.rb
There are various configuration options available for Flipper-UI. To make sure that the interface fits what we actually need this PR sets up the configuration.
- Add confirmation box when clicking "fully enable" feature
- Turn off the recommendation to set up Flipper CLoud
- Disable ability to delete feature flags from the UI
- Disable ability to add feature flags from the UI
- Add link back to admin interface to UI
> Add Flipper configuration

- app/lib/services/eligibility/targeted_delivery_funding.rb
These school should no longer automatically be marked as eligible.
Remove them from the eligible list.
> Remove schools from list of schools eligible for TSF

- app/views/registration_wizard/confirmation.html.erb
- Remove mention of 'costs' from post submission copy - most people do not need to pay
- Make it more obvious you need to apply with the provider
| Before  | After |
| ------------- |:-------------:|
| <img width="615" alt="Screenshot 2022-12-28 at 10 18 42" src="https://user-images.githubusercontent.com/56349171/209796927-ea9b09e1-9c8a-4460-8598-e0a87dc1c5c5.png">      | <img width="658" alt="Screenshot 2022-12-28 at 10 13 07" src="https://user-images.githubusercontent.com/56349171/209796094-0e6d7539-987e-440a-a3d9-9f489df9487d.png">     |
> Remove mention of 'cost' from post submission content

- db/migrate/20230106114221_update_default_cohort_for_ehco.rb
- db/schema.rb
The default cohort for EHCO needs updating to 2022
- Update the default cohort to 2022 for EHCO
> Update EHCO default cohort

- .github/workflows/deploy_to_review_app.yml
- app/views/admin/users/_user_details.html.erb
Bools in the admin panel should be styled with red/green indicators
> Admin panel style improvement

- .github/workflows/deploy_to_review_app.yml
- app/jobs/application_submission_job.rb
- app/lib/services/ecf/ecf_user_creator.rb
- app/lib/services/ecf/npq_profile_creator.rb
Unsafe navigation here was triggering data being logged that shouldn't have been.
> Use safe navigation when logging errors

- app/lib/services/admin/users_search.rb
- app/views/admin/users/index.html.erb
- spec/features/admin_spec.rb
- spec/lib/services/admin/users_search_spec.rb
Visit [admin users](https://register-national-professional-qualifications.education.gov.uk/admin/users) and allow searching by `school_urn` and `private_childcare_provider_urn`
Added tests for users search spec
> [CPDNPQ-791] Improve search functionality

- app/lib/services/eligibility/targeted_delivery_funding.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-956
Update the FE list after policies requirement
> Update the FE list

- app/views/registration_wizard/change_dqt.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1088
We are standardising on one page format across the app.
- Forms::ChangeDQT moved to use copy_page template
> [CPDNPQ-1088] Update change_dqt to use copy_page template

- .github/CODEOWNERS
@BroiSatse is joining the team and needs the ability to approve code changes.
What it says on the tin, this PR adds @broisatse to the CODEOWNERS file.
> Add Stanislaw to CODEOWNERS

- app/views/registration_wizard/check_answers.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1088
We are standardising on one page format across the app.
- Forms::CheckAnswers moved to use copy_page template
> [CPDNPQ-1088] Update check_answers to use copy_page template

- .github/CODEOWNERS
> Add new user to Codeowners

- .env.template
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1047
Codebase changes for improved handover.
Adds examples to .env.template required for app functionality.
> [CPDNPQ-1047] Add env examples to .env.template

- .rspec_parallel
- Gemfile
- Gemfile.lock
- config/database.yml
- spec/spec_helper.rb
Dev-only scope. Adds parallel_tests gem which significantly reduces test run time (on my local from nearly 7 minutes to 30 seconds).
> Introducing parallel tests

- .github/workflows/test.yml
- app/controllers/registration_wizard_controller.rb
- spec/spec_helper.rb
Using parallel spec in github actions
> Running tests in parallel on github

- app/views/registration_wizard/possible_funding.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1125
- Forms::PossibleFunding moved to use copy_page template
> Update Possible Funding Page to Use New Shared CopyPage Template

- app/views/registration_wizard/dqt_mismatch.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1123
- Forms::DQTMismatch moved to use copy_page template
> Update DQTMismatch Page to Use New Shared CopyPage Template

- app/lib/forms/find_childcare_provider.rb
- app/lib/forms/question_types/base.rb
- app/views/registration_wizard/find_childcare_provider.html.erb
- app/views/registration_wizard/shared/_question_page.html.erb
- app/views/registration_wizard/shared/questions/_text_field.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1111
- Update FindChildcareProvider to use QuestionTypes system
- Move all question/hint text loading into Forms::QuestionTypes::Base.
> [CPDNPQ-1111] Update FindChildcareProvider to use QuestionTypes system

- README.md
- docs/acquiring_new_private_childcare_provider_data.md
- docs/bigquery_reports.md
- docs/environments.md
- docs/get_a_identity.md
- docs/importing_data.md
- docs/logging.md
- docs/manual_validation_lifecycle.md
- docs/merging_deployment_and_env_variables.md
- docs/setup.md
- docs/specs_and_linting.md
- docs/using_govpaas.md
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1047
Improved app documentation
> [CPDNPQ-1047] Update docs

- .github/workflows/specs.yml
Should be a small speed improvement
Runs rspec, rubocop, and brakeman in parallel rather than sequentially, allowing them to fail/pass separately
> Parallelise specs/linting/brakeman on github

- docs/how_does_npq_work.md
Update the targeted support readme docs
> Update how_does_npq_work.md with Targeted support logic

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/specs.yml
- Gemfile
- Gemfile.lock
- app/lib/forms/have_ofsted_urn.rb
- app/views/registration_wizard/have_ofsted_urn.html.erb
- app/views/registration_wizard/shared/questions/_radio_button_group.html.erb
- config/locales/en.yml
- spec/rails_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1113
> Update Have Ofsted URN to use QuestionType system

- app/views/admin/applications/_application_details.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1160
Added following fields in NPQ and ECF admin consoles
- primary_establishment
- number_of_pupils
- targeted_support_funding_primary_plus_eligibility
> Surface New Targeted Support Funding Columns in the NPQ Application Data

- .github/workflows/specs.yml
- package.json
Upping node version from 16.20.0 to 16.20.1
> Upgraded node version

- .github/workflows/specs.yml
- app/views/registration_wizard/start.html.erb
- package.json
Update start page with new link and link text to go to revised NPQ guidance.
> update link and link text

- app/lib/forms/provider_check.rb
> make small question same size as other pages

- .github/CODEOWNERS
@shjohnson has left the project and needs removing as a code owner.
> Update CODEOWNERS to remove shjohnson

- lib/private_childcare_providers/2023-03-31/childminder_agencies.csv
https://dfedigital.atlassian.net/browse/CPDNPQ-730
> New list of private childcare providers

- .github/CODEOWNERS
Also removed Stan since he is no longer part of the project
> Added Pablo to Github approvers

- Makefile
https://trello.com/c/UiQ3GH2D
The corresponding service offering has been created. We need it to allocate Azure costs.
> [612] Update product tag

- app/helpers/application_helper.rb
- app/lib/services/feature.rb
- app/views/accounts/_application_table.html.erb
- app/views/accounts/_course_details.html.erb
Enabled feature flag for sandbox environment
https://dfedigital.atlassian.net/browse/CPDNPQ-1257
`SERVICE_ENV` is an environment variable that used to obtain the correct environment. Enable the feature flag as a result.
> Enabled feature flag for sandbox environment 

- .gitignore
- Makefile
https://trello.com/c/UiQ3GH2D
Minor error when applying DNS changes
Fix the Makefile
Also remove folder checked in by mistake
> [612] DNS zone fixes

- .env.template
- config/manifests/dev-manifest.yml
- config/manifests/review-app-manifest.yml
- config/manifests/sandbox-manifest.yml
- config/manifests/staging-manifest.yml
> Update ecf endpoint to external routes

- .github/workflows/deploy_to_dev.yml
- .github/workflows/deploy_to_production.yml
- .github/workflows/deploy_to_review_app.yml
- .github/workflows/deploy_to_sandbox.yml
https://github.com/cloudfoundry/cli/issues/2571
> Temporairly disable verification of cf repository

- app/views/registration_wizard/shared/_register_for_an_npq.html.erb
- spec/support/helpers/journey_assertion_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1273
> Select first best step from account page

- app/models/application.rb
- app/views/accounts/_work_details.html.erb
- app/views/accounts/user_registrations/show.html.erb
- spec/models/application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1272
Added Employer name and Employer URN fields and wrote respective functions in application model.
UI changes mentioned in the ticket.
Fixed specs.
failures:
> [CPDNPQ-1272] Updated UI according to the changes mentioned in the ticket

- app/views/accounts/user_registrations/show.html.erb
Managed condition for message displayed on the registration page to update npq registration.
Message were displayed on every registration. Now it will only display for those application which course status has value e.g; passed or failed.
> Conditional rendering update request message on registration

- Makefile
- terraform/application/application.tf
- terraform/application/database.tf
- terraform/application/variables.tf
**Follows on from #888**
Prepare the review app.
- Name the review app after the pull request number
> Deploying review apps

- config/webpacker.yml
Just copied the dev one for now.
> Add webpacker config for review

- docs/environments.md
We are in the process of migrating to Azure, and as we are making our 
environments very similar to [ECF][1], I am updating the documentation to reflect it.
Post-migration we will need to remove the `Dev` environment from this document.
[1]: https://github.com/DFE-Digital/early-careers-framework
> Update environments doc with Staging environment with Azure

- .github/workflows/specs.yml
Investigate permissions issue for dependabot PRs and resolve it.
https://dfedigital.atlassian.net/browse/CPDNPQ-1335
Added new action with github_token
> - name: Push changes
>   uses: ad-m/github-push-action@master
>   with:
>     github_token: ${{ secrets.GITHUB_TOKEN }}
> Added github token in actions

- .github/workflows/specs.yml
Investigate permissions issue for dependabot PRs and resolve it.
https://dfedigital.atlassian.net/browse/CPDNPQ-1335
Updated permissions for dependabot for complete job scope.
> Added token with step and added write permissions in action

- Makefile
The copy data from PaaS to Azure task (#913) needed [Konduit](https://github.com/DFE-Digital/teacher-services-cloud/blob/main/scripts/konduit.sh) to be installed. When it's present the process works 🎉
> Add install-konduit make step

- .github/actions/backup-paas-database/action.yml
- .github/actions/restore-paas-database/action.yml
- .github/workflows/copy-paas-database-to-azure.yml
Adds the steps to restore the sandbox database in Azure
[Appears to be fully working](https://github.com/DFE-Digital/npq-registration/actions/runs/6430328311) ✅
> Add sandbox config for database backup/restore

- .github/actions/backup-paas-database/action.yml
- .github/actions/restore-paas-database/action.yml
- .github/workflows/copy-paas-database-to-azure.yml
Follows on from #920, rebase this after that's been merged.
> Add production config for database backup and restore

- .github/actions/backup-paas-database/action.yml
Some final adjustments to get the production backup/restore working.
[Confirmed working with this branch here](https://github.com/DFE-Digital/npq-registration/actions/runs/6458007075).
> Fix prod / production inconsistency 😠

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
We'll just use this to 'register' the flows on GitHub and we can then iterate in a branch.
It's a start 😅
> Add the deployment flow and linting step

- .github/actions/deploy-environment-to-aks/action.yml
- .github/workflows/deploy.yml
- terraform/application/application.tf
[Jira ticket](https://dfedigital.atlassian.net/browse/CPDNPQ-1396)
Related to #936 
Testing out automatic review app deployments
> Azure: automatic deploy of review apps 

- .github/actions/backup-paas-database/action.yml
- .github/workflows/copy-paas-database-to-azure.yml
It looks like staging in PaaS is no longer used so use development instead.
> Copy PaaS dev db to staging

- .github/workflows/deploy.yml
- Add workflow steps for sandbox and production
This follows on from #937, rebase from `main` once it's merged.
> Deploy to sandbox and production

- .github/workflows/deploy.yml
- .github/workflows/rspec.yml
Rename the deploy steps with dashes instead of underscores.
> Rename the deploy steps

- .github/workflows/update_application_statuses.yml
- app/lib/services/ecf/ecf_application_synchronization.rb
- spec/lib/services/ecf/ecf_application_synchronization_spec.rb
update provider application status logic to cater to historic applications
https://dfedigital.atlassian.net/browse/CPDNPQ-1381
- Updated ecf_application_synchronization_job
- added limited ecf_ids to uri.query
> Add logic to cater historic applications/statuses

- app/views/registration_wizard/dont_have_teacher_reference_number.html.erb
- app/views/registration_wizard/start.html.erb
- app/views/registration_wizard/teacher_reference_number.html.erb
- config/locales/en.yml
- spec/features/journeys/happy_paths/when_get_an_identity_returns_no_trn_spec.rb
[Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-000](https://dfedigital.atlassian.net/browse/CPDNPQ-1432)
Updates content so finding/requesting TRNs are simplified for our users.
> Update Guidances for retrieving/finding TRNs

- app/jobs/crons/update_schools_job.rb
Changes the execution of the Job to update the schools to `every day at 4:30 AM`
> Update cron for update schools job

- .github/workflows/export_dashboard_report.yml
This breaks `Export Dashboard to BigQuery` job.
Reverts DFE-Digital/npq-registration#972
> Revert "Bump google-github-actions/setup-gcloud from 0 to 1"

- .github/workflows/destroy_review_app.yml
There's currently no mechanism for deleting review apps after their branch has been merged. We should do this to Azure tidy and costs down.
> Add flow for deleting review apps post merge

- app/jobs/application_submission_job.rb
- spec/jobs/application_submission_job_spec.rb
add course to post registration email
https://dfedigital.atlassian.net/browse/CPDNPQ-1443
Used `localise_sentence_embedded_course_name` in application_submission_job to correct format for NPQ
> add course to post registration email

- app/jobs/crons/update_applications_statuses_job.rb
- app/services/ecf/ecf_application_synchronization.rb
- spec/lib/services/ecf/ecf_application_synchronization_spec.rb
Reverts DFE-Digital/npq-registration#930
> Revert "Add logic to cater historic applications/statuses"

- app/views/accounts/_application_table.html.erb
- app/views/accounts/_course_details.html.erb
- app/views/registration_wizard/start.html.erb
- config/locales/en.yml
Updated context on multiple pages
https://dfedigital.atlassian.net/browse/CPDNPQ-1385
- Add build point on start page(`check your course outcome, if you have completed your course`)
- Added translations of course outcomes in en.yml
- Used new details of outcome in required pages
> Signpost users to get certificates in user account pages

- .github/workflows/destroy_review_app.yml
- Makefile
> Amend review app deletion flow

- .github/actions/deploy-environment-to-aks/action.yml
- Makefile
- terraform/application/config/production.tfvars.json
- terraform/application/statuscake.tf
- terraform/application/terraform.tf
Ticket: https://trello.com/c/JHRXC9Qu/774-npq-turn-on-prod-monitoring
Add production statuscake and database monitoring
Update terraform config and Makefile
> Add prod statuscake and db monitoring

- app/models/user.rb
Add some debugging information to resolve GAI error.
> Further debugging of GAI error

- app/forms/questionnaires/qualified_teacher_check.rb
- app/models/registration_wizard.rb
- app/services/email_template.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1533
> Clean-up assigning Sentry issues

- app/views/pages/_choose_an_npq_and_provider_content.erb
- app/views/registration_wizard/ehco_unavailable.html.erb
- app/views/registration_wizard/ineligible_for_funding/early_years/_not_applying_for_NPQEY.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1399
Some links were not of the correct colour in the app so updated their colour in order to maintain consistency throughout the app.
> CPDNPQ-1399 Make links all the correct colour

- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1553
Adding content and link to access the certificates for passed outcomes
> CPDNPQ-1553 Add Content about Certificates under Passed Status

- app/views/accounts/_course_details.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1580
> Applied content changes

- app/forms/questionnaires/choose_private_childcare_provider.rb
- app/models/application.rb
- app/models/private_childcare_provider.rb
- app/models/registration_wizard.rb
- app/models/school.rb
- app/views/accounts/_funding_details.html.erb
- app/views/accounts/_work_details.html.erb
- spec/features/happy_journeys/js/while_working_at_private_childcare_provider_but_not_a_nursery_spec.rb
- spec/features/journeys/happy_paths/when_choose_lead_mentor_course_spec.rb
- spec/features/sad_journeys/lead_mentor_journey_with_incorrect_course_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1387
1. As a user I want to review all the answers I have submitted so I can ensure they are all correct.
2. As a UCD team we want the registration details pages to be easy to understand and consistent with the check answers pages.
> Update work details after registration

- app/models/api_token.rb
- db/migrate/20240119150601_create_api_tokens.rb
- db/schema.rb
- spec/models/api_token_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2688
* Created `ApiToken` model matching ECF
failures:
> add ApiToken domain model

- .github/actions/backup-and-restore-snapshot-database/action.yml
- .github/actions/backup-and-upload-database/action.yml
- .github/actions/deploy-environment-to-aks/action.yml
- .github/actions/refresh-migration-database/action.yml
- .github/workflows/destroy_review_app.yml
- Makefile
- terraform/application/terraform.tf
Not to be deployed until terraform modules has been updated on Monday Jan 29th.
- [Checklist](https://hedgedoc.teacherservices.cloud/FZWIycYoTDq_RwKLNg0kRg?view#Prepare-PRs-for-each-deployed-app-to-update-the-authentication)
Enable azure rbac on deployment (for when it is enabled in the cluster)
Update Makefile, terraform and workflows to use rbac if configured for the cluster.
failures:
> Enable azure rbac on deployment

- app/jobs/application_submission_job.rb
- app/services/ecf/ecf_user_updater.rb
- app/services/ecf/npq_profile_creator.rb
We have been seeing too many JsonApi errors lately, this pr is an effort to silence some of those
failures:
> Skip ConnectionError class from sentry logs

- app/models/cohort.rb
- db/migrate/20240216095511_create_cohorts.rb
- db/schema.rb
- spec/factories/cohorts.rb
- spec/models/cohort_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2827
Adds Cohort model following the work on the branch: `npq-separation`
> Add cohort model

- db/seeds.rb
It's hard to test the admin panel in review apps without admins and super admins.
> Seed admins and other users in review apps

- db/seeds.rb
We don't need to wait a few seconds to import 60k records every time we reseed in dev.
> Limit to 1000 schools/childcare providers locally

- app/controllers/api/base_controller.rb
- app/controllers/api/v1/get_an_identity/webhook_messages_controller.rb
- app/controllers/api/v3/statements_controller.rb
- app/controllers/concerns/api/token_authenticatable.rb
- app/models/api_token.rb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20240301103432_create_api_tokens.rb
- db/schema.rb
- db/seeds.rb
- spec/models/api_token_spec.rb
- spec/rails_helper.rb
- spec/requests/api/v1/applications_controller_spec.rb
- spec/requests/api/v1/declarations_controller_spec.rb
- spec/requests/api/v1/outcomes_controller_spec.rb
- spec/requests/api/v1/participants_controller_spec.rb
- spec/requests/api/v2/applications_controller_spec.rb
- spec/requests/api/v2/declarations_controller_spec.rb
- spec/requests/api/v2/enrolments_controller_spec.rb
- spec/requests/api/v2/outcomes_controller_spec.rb
- spec/requests/api/v2/participants/outcomes_controller_spec.rb
- spec/requests/api/v2/participants_controller_spec.rb
- spec/requests/api/v3/applications_controller_spec.rb
- spec/requests/api/v3/declarations_controller_spec.rb
- spec/requests/api/v3/outcomes_controller_spec.rb
- spec/requests/api/v3/participants/outcomes_controller_spec.rb
- spec/requests/api/v3/participants_controller_spec.rb
- spec/requests/api/v3/statements_spec.rb
- spec/routing/npq_separation_routes_spec.rb
- spec/support/helpers/api_helpers.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2863
* `APIToken` model added
* API routes set to default JSON
* Seed tokens for review apps
> [CPDLP-2863] TS1 - Lead provider API token authentication

- app/views/layouts/application.html.erb
- config/initializers/constants.rb
- package.json
- yarn.lock
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1725
> Use new feedback form

- app/controllers/api/base_controller.rb
- app/controllers/api/v3/statements_controller.rb
- app/controllers/concerns/api/token_authenticatable.rb
- app/services/statements/query.rb
- config/environments/test.rb
- config/initializers/blueprinter.rb
- config/initializers/oj.rb
- config/locales/en.yml
- spec/rails_helper.rb
- spec/requests/api/v3/statements_spec.rb
- spec/support/helpers/api_helpers.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2859
* `API::V3::StatementsController` updated with `index` and `show` actions
* Tests added
> [CPDLP-2859] TS1 - Statements endpoint - happy path (show/index)

- docs/environments.md
These have all changed since we moved away from GOV PAAS. We also have a migration environment as well.
> Update environment URLs for Azure

- app/controllers/api/v3/statements_controller.rb
- app/controllers/concerns/api/pagination.rb
- app/services/statements/query.rb
- config/initializers/pagy.rb
- config/locales/en.yml
- spec/requests/api/docs/v3/statements_spec.rb
- spec/requests/api/v3/statements_spec.rb
- spec/services/statements/query_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2860
* Added `API::Pagination` concern
* Updated `API::V3::StatementsController` with pagination
* Added pagination tests for statements.
> [CPDLP-2860] TS1 - Statements endpoint -  pagination

- app/controllers/admin/super_admins_controller.rb
Admins now live in the admins table rather than alongside users.
> Fix super admin promotion bug

- README.md
- app/controllers/email_updates_controller.rb
- app/views/email_updates/unsubscribe.html.erb
- app/views/email_updates/unsubscribed.html.erb
- app/views/layouts/shared/_header.html.erb
- app/views/pages/closed_registration_exception.html.erb
- app/views/registration_closed/show.html.erb
- app/views/registration_wizard/shared/_register_for_an_npq.html.erb
- config/database.yml
- config/routes.rb
- docs/emails.md
- spec/features/service_closed_spec.rb
Few fixes that are missing for closed state.
> Fix closed registration

- terraform/application/variables.tf
Added 'Teacher-Services-infra' contact group for status cake alerts. 
https://trello.com/c/Z6eliKhq/1654-review-statuscake-contact-groups
> Added contact group Teacher-Services-infra to status cake alerts

- app/models/course.rb
- spec/models/course_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-2960
- Added `name` presence validation on `Course`
- Updated rspec
> [CPDLP-2960] Course validation

- Makefile
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1766
This PR adds some commands to the Makefile which will let us copy data to and from Kubernetes pods. It will be used to sync the school metadata we hold on NPQ Applications.
I've manually tested this for both `staging` and a review app with success.
> Add aks upload and download commands to Makefile

- app/views/admin/_layout.html.erb
- app/webpacker/styles/subnav.scss
Ticket: N/A
Minor style improvements in the Admin pages to increase usability.
- Increase the title width to two thirds to avoid wrapping
- Wrap the menu items to remove the horizontal scrollbar
1. Login as a super admin
| Before | After |
|--------|--------|
| ![before](https://github.com/DFE-Digital/npq-registration/assets/951947/25565f62-b451-4e2c-bdda-790ce4c3cb6d) | ![after](https://github.com/DFE-Digital/npq-registration/assets/951947/39ced0fa-4f33-4cee-b3aa-d636bd16231e) |
> Style the admin menu

- app/services/migration/migrator.rb
- app/services/migration/migrators/course.rb
- spec/factories/users.rb
- spec/lib/services/get_an_identity_service/webhooks/user_updated_processor_spec.rb
- spec/lib/services/handle_submission_for_store_spec.rb
- spec/services/migration/migrator_spec.rb
- spec/services/migration/migrators/course_spec.rb
Ticket: [CPDLP-2962](https://dfedigital.atlassian.net/browse/CPDLP-2962)
We would like to migrate existing courses data into NPQ from ECF.
Add logic to migrate ECF npq courses data into NPQ reg app.
[CPDLP-2962]: https://dfedigital.atlassian.net/browse/CPDLP-2962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2940] Add courses migrator

- app/helpers/funding_helper.rb
- app/views/accounts/_eligible_for_funding_details.html.erb
- app/views/accounts/_funding_details.html.erb
- app/views/accounts/_in_review_funding_details.html.erb
- app/views/registration_wizard/possible_funding/_eligible_for_scholarship_funding.html.erb
- app/views/registration_wizard/possible_funding/_eligible_for_scholarship_funding_not_tsf.html.erb
- app/views/registration_wizard/possible_funding/_funding_eligibility_unclear.html.erb
- app/views/registration_wizard/possible_funding/_funding_eligible_maths.html.erb
- app/views/registration_wizard/possible_funding/_lead_mentor.html.erb
- app/views/registration_wizard/possible_funding/_private_childcare_provider.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1786
- Updates funding content on registration summarypage.
- Remove negative contraction ‘doesn’t' and replace with ‘does not’.
- Updates content about funding during wizard
**Before**
**After**
**After:**
> [CPDNPQ-1786] explain funding eligibility more clearly

- app/services/admin_service/users_search.rb
- db/migrate/20240429195521_change_ecf_id_type_to_uuid.rb
- db/schema.rb
- spec/factories/lead_providers.rb
- spec/jobs/application_submission_job_spec.rb
- spec/lib/services/ecf/ecf_user_creator_spec.rb
- spec/lib/services/ecf/npq_profile_creator_spec.rb
- spec/lib/services/ecf/npq_profile_updater_spec.rb
- spec/lib/services/importers/populate_get_identity_id_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3009
* Migration to changed `ecf_id` to `uuid` type.
> [CPDLP-3009] change ecf_id in NPQ from text to uuid

- app/controllers/api/v1/applications_controller.rb
- app/controllers/api/v2/applications_controller.rb
- db/seeds/base/add_applications.rb
- spec/factories/applications.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2966
We currently have existing seed data in NPQ for applications. However is it adequate for testing. We can beef it up to make it easier for Shahad/Fraser to test things currently in NPQ separation branch.
Improve NPQ application seed data.
> [CPDLP-2966] Improve NPQ application seed data

- app/models/application.rb
- app/models/participant_id_change.rb
- app/models/user.rb
- db/migrate/20240528103508_create_participant_id_changes.rb
- db/schema.rb
- db/seeds/base/add_applications.rb
- spec/factories/applications.rb
- spec/factories/participant_id_changes.rb
- spec/lib/services/approved_itt_providers/update_spec.rb
- spec/models/application_spec.rb
- spec/models/participant_id_change_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
Ticket: [CPDLP-3131](https://dfedigital.atlassian.net/browse/CPDLP-3131)
We will need to add the participant id changes table to surface the correct structure in the participants npq endpoint in the API.
Add participant id changes table with correct fields/validations.
[CPDLP-3131]: https://dfedigital.atlassian.net/browse/CPDLP-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3131] Add participant id changes table

- app/forms/questionnaires/ineligible_for_funding.rb
- app/forms/questionnaires/senco_in_role.rb
- app/forms/questionnaires/senco_start_date.rb
- app/models/course.rb
- app/models/registration_wizard.rb
- app/services/funding_eligibility.rb
- app/views/accounts/_work_details.html.erb
- app/views/registration_wizard/ineligible_for_funding/_not_eligible_for_scholarship_funding.html.erb
- config/locales/en.yml
- spec/features/journeys/happy_paths/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb
- spec/lib/questionnaires/senco_start_date_spec.rb
- spec/lib/services/funding_eligibility_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1459
This PR includes changes that were required following QA testing. It includes...
- Changes to funding eligibility
- Updated error messages
- Text size formatting
- Senco start date validations
> [CPDNPQ-1459] senco registration journey updates

- app/services/funding_eligibility.rb
- app/views/registration_wizard/ehco_funding_not_available.html.erb
- app/views/registration_wizard/ehco_possible_funding.html.erb
- app/views/registration_wizard/ineligible_for_funding.erb
- app/views/registration_wizard/ineligible_for_funding/_not_eligible_for_scholarship_funding.html.erb
- app/views/registration_wizard/ineligible_for_funding/_not_in_england.html.erb
- app/views/registration_wizard/ineligible_for_funding/school/_has_already_been_funded.html.erb
- app/views/registration_wizard/possible_funding/_funding_eligibility_unclear.html.erb
- spec/features/journeys/happy_paths/while_working_at_private_childcare_provider_but_not_a_nursery_spec.rb
- spec/features/journeys/happy_paths/while_working_at_private_nursery_spec.rb
- spec/lib/services/funding_eligibility_spec.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDNPQ/boards/137?isInsightsOpen=true&selectedIssue=CPDNPQ-1876
> Update funding messages

- app/forms/questionnaires/ineligible_for_funding.rb
- app/services/funding_eligibility.rb
- app/views/registration_wizard/ineligible_for_funding/_not_a_pp50_institution.html.erb
- app/views/registration_wizard/ineligible_for_funding/early_years/_not_applying_for_NPQEY.html.erb
- app/views/registration_wizard/ineligible_for_funding/lead_mentor/_not_applying_for_NPQLTD.html.erb
- config/locales/en.yml
- spec/features/journeys/happy_paths/while_working_at_private_childcare_provider_but_not_a_nursery_spec.rb
- spec/lib/services/funding_eligibility_spec.rb
Multiple fixes from testing session.
> Eligibility testing bugfixes

- app/services/funding_eligibility.rb
- app/views/registration_wizard/ineligible_for_funding/_not_a_pp50_institution.html.erb
- config/locales/en.yml
Better messages for eligiblity
> Eligiblity messages

- terraform/application/config/production.tfvars.json
- terraform/application/config/sandbox.tfvars.json
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio  
Added  enable_logit:true to  deployments for production , separatione,sandbox and migration.
After deployment , logs can be looked in to logit.io.
> Enabled logit.io for production namespace

- spec/models/cohort_spec.rb
- spec/models/statement_spec.rb
Ticket: N/A
There's a flakey test `spec/models/statement_spec.rb:29`.
Fix the flakey test.
> Fix flakey test `spec/models/statement_spec.rb:29`

- spec/lib/services/funding_eligibility_spec.rb
This test it flaky, and needs proper TLC later.
> Disable test temporairly

- app/forms/questionnaires/qualified_teacher_check.rb
- app/views/registration_wizard/dont_have_teacher_reference_number.html.erb
- app/views/registration_wizard/dqt_mismatch.html.erb
- app/views/registration_wizard/start.html.erb
- app/views/registration_wizard/teacher_reference_number.html.erb
- config/locales/en.yml
- spec/lib/questionnaires/qualified_teacher_check_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1855
> 1855 trn content changes

- app/controllers/application_controller.rb
- spec/features/service_closed_spec.rb
> Use feature flag for closed registration users

- app/models/declaration.rb
- app/models/outcome.rb
- db/migrate/20240621044020_create_outcome_table.rb
- db/schema.rb
- spec/factories/outcomes.rb
- spec/models/declaration_spec.rb
- spec/models/outcome_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3096
* Add outcomes table with the correct validations/fields after the analysis ticket 
* Add factories and required associations to other tables
> Add outcomes table

- app/services/participants/action.rb
- app/services/participants/change_schedule.rb
- config/locales/en.yml
- spec/services/participants/change_schedule_spec.rb
- spec/services/participants/defer_spec.rb
- spec/services/participants/resume_spec.rb
- spec/services/participants/withdraw_spec.rb
- spec/support/shared_examples/participant_action_support.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3089
* `Participants::ChangeSchedule` service created with tests
> [CPDLP-3089] TS6 - Add change schedule participant service

- config/locales/en.yml
- spec/features/journeys/happy_paths/able_to_receive_targeted_delivery_funding_spec.rb
- spec/features/journeys/happy_paths/basic_registration_journey_spec.rb
- spec/features/journeys/happy_paths/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb
- spec/features/journeys/happy_paths/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb
- spec/features/journeys/happy_paths/changing_from_outside_of_catchment_area_to_inside_spec.rb
- spec/features/journeys/happy_paths/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb
- spec/features/journeys/happy_paths/funded_ehco_registration_journey_spec.rb
- spec/features/journeys/happy_paths/international_teacher_npqh_journey_spec.rb
- spec/features/journeys/happy_paths/other_funded_ehco_registration_journey_spec.rb
- spec/features/journeys/happy_paths/previously_received_targeted_delivery_funding_spec.rb
- spec/features/journeys/happy_paths/via_using_old_name_and_not_headship_spec.rb
- spec/features/journeys/happy_paths/via_using_same_name_spec.rb
- spec/features/journeys/happy_paths/when_choose_lead_mentor_course_spec.rb
- spec/features/journeys/happy_paths/when_choose_maths_course_spec.rb
- spec/features/journeys/happy_paths/when_get_an_identity_returns_no_trn_spec.rb
- spec/features/journeys/happy_paths/when_outside_of_catchment_area_crown_dependencies_spec.rb
- spec/features/journeys/happy_paths/when_outside_of_catchment_area_spec.rb
- spec/features/journeys/happy_paths/when_previously_funded_spec.rb
- spec/features/journeys/happy_paths/when_working_at_an_eligible_primary_school_spec.rb
- spec/features/journeys/happy_paths/while_not_currently_working_at_school_spec.rb
- spec/features/journeys/happy_paths/while_working_at_private_childcare_provider_but_not_a_nursery_spec.rb
- spec/features/journeys/happy_paths/while_working_at_private_nursery_spec.rb
- spec/features/journeys/happy_paths/while_working_at_public_nursery_spec.rb
- spec/features/journeys/happy_paths/while_working_in_neither_a_school_nor_childcare_spec.rb
- spec/features/journeys/sad_paths/applying_for_ehco_but_not_new_headteacher_spec.rb
- spec/features/journeys/sad_paths/lead_mentor_journey_with_incorrect_course_spec.rb
- spec/features/journeys/sad_paths/not_chosen_dqt_or_provider_spec.rb
- spec/features/journeys/sad_paths/school_not_in_england_spec.rb
- spec/features/journeys/sad_paths/works_in_childcare_but_not_in_england_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1911
Updates several of the error messages from the NPQ wizard flow. It also changes the use of "an NPQ" to "a NPQ".
> [CPDNPQ-1911] updated error messages

- app/models/lead_provider.rb
- spec/lib/questionnaires/choose_your_provider_spec.rb
- spec/models/lead_provider_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1918
> Adjust lead providers offerings

- app/views/registration_wizard/choose_childcare_provider.html.erb
- app/views/registration_wizard/choose_private_childcare_provider.html.erb
- app/views/registration_wizard/choose_school.html.erb
https://dfedigital.atlassian.net/browse/CPDNPQ-1904
This PR adds dome details blocks on pages where users need to enter their workplace or URN. It notifies the user what to do if they cannot find their workplace/URN. Providing a contact us link.
> [CPDNPQ-1904] added details blocks

- spec/services/applications/accept_spec.rb
- spec/services/declarations/query_spec.rb
- spec/services/valid_test_data_generators/applications_populater_spec.rb
- spec/support/with_default_schedules.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3197
* Use `:with_default_schedules` tag for only the specific tests that require default schedules.
> [CPDLP-3197] TS7 - Generating spec and seed data

- db/seeds.rb
- db/seeds/base/add_declarations.rb
- spec/factories/applications.rb
- spec/factories/declarations.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3104
* Declarations seed that adds applications with various declarations.
> [CPDLP-3104] TS7 - Add declaration seed data

- app/models/participant_outcome.rb
- db/migrate/20240628101251_add_ecf_id_to_participant_outcomes.rb
- db/schema.rb
- spec/factories/participant_outcomes.rb
- spec/models/participant_outcome_spec.rb
We need this as we expose it in the serializer.
> Add `ecf_id` to `ParticipantOutcome`

- app/views/accounts/_eligible_for_funding_details.html.erb
https://dfedigital.atlassian.net/browse/CPDNPQ-1954
> Change message for senco

- .rspec_parallel
- Gemfile
- Gemfile.lock
- config/database.yml
- docs/specs_and_linting.md
Ticket: N/A
Enable devs to run the specs in parallel.
- Added the parallel_test gem
- Updated the database config
- Updated the specs doc
> Add parallel_test gem

- app/services/valid_test_data_generators/applications_populater.rb
- spec/services/valid_test_data_generators/applications_populater_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3105
* Updated `ValidTestDataGenerators::ApplicationsPopulater` to include declarations
> [CPDLP-3105] TS7 - Add declaration seed data to separation

- spec/models/lead_provider_spec.rb
Build is failing some times.
Fix `spec/models/lead_provider_spec.rb:27` flaley test.
> Fix `spec/models/lead_provider_spec.rb:27` flaley test

- app/controllers/api/v1/participants_controller.rb
- app/controllers/api/v2/participants_controller.rb
- app/controllers/api/v3/participants_controller.rb
- app/services/participants/change_schedule.rb
- public/api/docs/v1/swagger.yaml
- public/api/docs/v2/swagger.yaml
- public/api/docs/v3/swagger.yaml
- spec/models/lead_provider_spec.rb
- spec/requests/api/docs/v1/participants_spec.rb
- spec/requests/api/docs/v2/participants_spec.rb
- spec/requests/api/docs/v3/participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/requests/api/v2/participants_spec.rb
- spec/requests/api/v3/participants_spec.rb
- spec/support/helpers/swagger_example_parser.rb
- spec/swagger_helper.rb
- spec/swagger_schemas/requests/participant_change_schedule_request.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3173
We would like to add the NPQ participant profile change schedule endpoint to NPQ separation
Add change schedule endpoint.
> [CPDLP-3173] Add change schedule endpoint

- app/models/school.rb
- spec/features/journeys/happy_paths/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1977
> Allow EYL for PP50 schools

- spec/lib/services/funding_eligibility_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1917
> Fix flaky spec

- db/seeds/base/add_declarations.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3101
Now we've added outcomes we need to ensure that the seed data for review environments is up to date with this data.
- Ensure we have a few accepted applications with a completed declaration with an outcome that could have passed/failed
- Please ensure the completion date matches the declaration date
> [CPDLP-3101] Add outcomes to review app seed data

- app/models/lead_provider.rb
- spec/lib/questionnaires/choose_your_provider_spec.rb
- spec/models/lead_provider_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1985
New providers to be added to EHCO registration flow: 
- LLSE
- TDT
- UCL
> [CPDNPQ-1985] added providers to ehco

- lib/private_childcare_providers/2024-06-25/childminder_agencies.csv
- lib/private_childcare_providers/2024-07-17/childminder_agencies.csv
https://dfedigital.atlassian.net/browse/CPDNPQ-1908
Updated private childcate provider data CSVs
This precedes the import task which is going to be run https://github.com/DFE-Digital/npq-registration/blob/main/docs/importing_data.md#importing-private-childcare-provider-data
> [CPDNPQ-1908] Updated private childcare provider data CSVs

- app/serializers/api/applications_csv_serializer.rb
- public/api/docs/v1/swagger.yaml
- public/api/docs/v2/swagger.yaml
- spec/serializers/api/applications_csv_serializer_spec.rb
- spec/swagger_schemas/models/application_csv.rb
- spec/swagger_schemas/responses/applications_csv.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3338
* Updated `API::ApplicationsCsvSerializer` to include `funded_place`
* Updated swagger docs
> [CPDLP-3338] MVP NPQ Prep - Add missing funded place to NPQ applications csv

- app/models/application.rb
- app/models/declaration.rb
- app/services/applications/accept.rb
- app/services/valid_test_data_generators/applications_populater.rb
- config/locales/en.yml
- db/seeds/base/add_declarations.rb
- spec/factories/applications.rb
- spec/factories/schedules.rb
- spec/models/application_spec.rb
- spec/models/declaration_spec.rb
- spec/requests/api/docs/v3/applications_spec.rb
- spec/services/applications/change_funded_place_spec.rb
- spec/services/participant_outcomes/create_spec.rb
- spec/services/participants/change_schedule_spec.rb
- spec/support/matchers/error_matcher.rb
This PR is a copy another PR that's not deployed to review app correctly: https://github.com/DFE-Digital/npq-registration/pull/1544
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3282
* Moved validations from service classes to the model related to the specific columns.
* Updated factories to be valid
> [CPDLP-3282] NPQ MVP Prep - Review and add missing validations for services and models

- public/api/docs/v1/swagger.yaml
- public/api/docs/v2/swagger.yaml
- public/api/docs/v3/swagger.yaml
- spec/requests/api/docs/v1/applications_spec.rb
- spec/requests/api/docs/v1/declarations_spec.rb
- spec/requests/api/docs/v2/applications_spec.rb
- spec/requests/api/docs/v2/declarations_spec.rb
- spec/requests/api/docs/v3/applications_spec.rb
- spec/requests/api/docs/v3/declarations_spec.rb
- spec/requests/api/docs/v3/participants_spec.rb
- spec/support/shared_examples/api_index_endpoint_documentation_support.rb
- spec/swagger_schemas/models/application.rb
- spec/swagger_schemas/models/application_csv.rb
- spec/swagger_schemas/models/enrolment_csv.rb
- spec/swagger_schemas/models/participant.rb
- spec/swagger_schemas/models/participant_outcome.rb
- spec/swagger_schemas/requests/application_accept_request.rb
- spec/swagger_schemas/requests/application_change_funded_place_request.rb
- spec/swagger_schemas/requests/participant_declaration_request.rb
- spec/swagger_schemas/requests/participant_outcome_create_request.rb
- spec/swagger_schemas/responses/unprocessable_entity.rb
[Jira-3351](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3351)
There are a number of bugs/discrepancies in the swagger documentation that we want to address.
- Fix funded_place description/add missing funded_place
- Update change-funded-place response example
- Make UnprocessableEntityResponse schema generic
- Fix enrolled typo in swagger docs
- Restrict sorting swagger docs to endpoints that support it
- Add missing data attribute to declaration request
- Add request filters to v1/2 declarations CSV endpoint
- Set clawback_statement_id to nil in v3 void response
- Add voided state to ParticipantOutcome response schema
- Fix error on collapsing participant outcomes swagger accordion
- Fix completion_date format in swagger docs
Best reviewed by-commit.
> Various Swagger doc fixes

- public/api/docs/v1/swagger.yaml
- public/api/docs/v2/swagger.yaml
- public/api/docs/v3/swagger.yaml
- spec/swagger_schemas/requests/application_change_funded_place_request.rb
- spec/swagger_schemas/requests/participant_declaration_completed_request.rb
- spec/swagger_schemas/requests/participant_declaration_retained_request.rb
- spec/swagger_schemas/requests/participant_declaration_started_request.rb
Ticket: [CPDLP-3350](https://dfedigital.atlassian.net/browse/CPDLP-3350)
Currently in our swagger docs required/nullable fields are not consistent with ECF/the real values we need to do a full sweep of all fields/requests and ensure they align correctly if they are required vs not.
Review nullable values in swagger docs.
[CPDLP-3350]: https://dfedigital.atlassian.net/browse/CPDLP-3350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3350] Review nullable values in swagger docs

- app/controllers/api/base_controller.rb
- app/controllers/concerns/api/logger_payload.rb
- config/environments/production.rb
- config/environments/review.rb
- spec/controllers/concerns/api/logger_payload_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3293
* Added `append_info_to_payload` to `Api::BaseController` to track metadata for logit.
* [Search for the review app log in the last 10 min](https://kibana-uk1.logit.io/s/b2876053-0173-44fc-983d-99567292ba31/app/data-explorer/discover#?_a=(discover:(columns:!(app.host,url.original,url.path),isDirty:!t,sort:!()),metadata:(indexPattern:'8ac115c0-aac1-11e8-88ea-0383c11b333a',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-10m,to:now))&_q=(filters:!(),query:(language:kuery,query:'*npq-registration-review-1568-*')))
> [CPDLP-3293] NPQExit - Configure logit

- public/api/docs/v2/swagger.yaml
- public/api/docs/v3/swagger.yaml
- spec/swagger_schemas/models/enrolment_csv.rb
- spec/swagger_schemas/models/participant.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3392
* `funded_place` not required for enrolment csv
* removed duplication in `PARTICIPANT` for swagger
> [CPDLP-3392] Fix nullable swagger docs

- app/helpers/application_helper.rb
- app/models/application.rb
- app/models/application_state.rb
- app/models/ecf_sync_request_log.rb
- app/models/get_an_identity/webhook_message.rb
- app/serializers/api/participant_serializer.rb
- app/services/applications/accept.rb
- app/services/applications/change_funded_place.rb
- app/services/applications/reject.rb
- app/services/get_an_identity_service/webhooks/user_updated_processor.rb
- app/services/participants/change_schedule.rb
- app/services/participants/defer.rb
- app/services/participants/resume.rb
- app/services/participants/withdraw.rb
- app/validators/participant_not_withdrawn_validator.rb
- app/views/admin/application_submissions/_ecf_sync_request_log.html.erb
- spec/models/application_spec.rb
- spec/models/application_state_spec.rb
- spec/models/declaration_spec.rb
- spec/models/ecf_sync_request_log_spec.rb
- spec/models/get_an_identity/webhook_message_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/docs/v1/participants_spec.rb
- spec/requests/api/docs/v2/participants_spec.rb
- spec/requests/api/docs/v3/participants_spec.rb
- spec/services/applications/accept_spec.rb
- spec/services/declarations/create_spec.rb
- spec/services/valid_test_data_generators/applications_populater_spec.rb
- spec/validators/participant_not_withdrawn_validator_spec.rb
Ticket: [CPDLP-3252](https://dfedigital.atlassian.net/browse/CPDLP-3252)
We added a lot of enums to our models in the new NPQ world. We agreed it would be better to add suffixes to ensure we don’t mix up fields in lookups
Add suffixes to all field enums and amend any look up methods/specs.
[CPDLP-3252]: https://dfedigital.atlassian.net/browse/CPDLP-3252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3252] All model enums should include `_suffix: true`

- terraform/application/config/migration.tfvars.json
We want to be able to see migration logs so that we can debug the migration process more easily.
> Enable Logit for the migration environment

- README.md
- docs/npq_contracts.md
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3449
* Created doc `docs/npq_contracts.md`
> [CPDLP-3449] NPQ Contracts design doc

- terraform/application/config/migration.tfvars.json
Ticket: [CPDLP-3481](https://dfedigital.atlassian.net/browse/CPDLP-3481)
The current migration environment is not scaled up and not performant when migrations run
Scale up migration env.
[CPDLP-3481]: https://dfedigital.atlassian.net/browse/CPDLP-3481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3481] Scale up migration env

- terraform/application/config/migration.tfvars.json
One container keeps crashing, so best scale up a bit for now so we don't overload the one
Bump up the webapp to 3 for now
failures:
> Bump up webapp pods for migration

- app/models/migration/ecf/npq_contract.rb
- app/models/migration/ecf/npq_lead_provider.rb
- app/services/migration/migrators/contract.rb
- spec/factories/migration/ecf/npq_contracts.rb
- spec/models/migration/ecf/npq_contract_spec.rb
- spec/services/migration/migrators/contract_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3450
* Created `Migration::Ecf::NpqContract` model
* Created `Migration::Migrators::Contract` migrator
* Created tests and factories.
> [CPDLP-3450] NPQ Contracts migration from ECF to NPQ

- app/views/registration_wizard/start.html.erb
Duplicate paragraph needs removing
> Removed duplicate paragraph

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/mermaid.scss
- app/javascript/application.js
- package.json
- yarn.lock
[Jira-3592](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3592)
We want to be able to render Mermaid sequence diagrams in the API guidance.
- Add Mermaid support to API guidance
Add `mermaid.js` pcakge and initialize on all pages. Override the default style to make it more in keeping with the rest of our website.
We wanted to style notes in different colours, but this doesn't appear to be possible. Similarly, the text was start/ending right on the note border and there's not an easy way to add padding globally. A work around is to use `#nbsp;` before/after the text to give additional spacing.
Example test page:
```
A test page to demonstrate a Mermaid process diagram:
<div …
```
> Add Mermaid support to API guidance

- .github/actions/backup-and-restore-snapshot-database/action.yml
- .github/actions/backup-and-upload-database/action.yml
- .github/actions/refresh-migration-database/action.yml
Updated actions to use shared kubectl action
Updated actions to use shared kubectl action
failures:
> Updated pipeline to use shared action

- .github/workflows/report-migration-results.yml
[Jira-3512](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=unassigned%2C712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3512)
I couldn't test this action until it was merged into main, so there were inevitably a _few_ issues 🙂 
Contains various fixes and minor tweaks:
- Pass `production` environment instead of `migration` (`az login` fails with `migration` - something probably off with the GitHub secret here)
- Install `kubectl` and run commands directly instead of via `make` (the `make` commands output a load of other info that messes up the comparisons/output we want)
- Add step for Slack webhook secret
- Add duration to post and format failures 
Screenshots of the Slack messages below - I can't seem to change the Slack user it …
> Fix migration report GitHub action

- app/services/migration/migrators/user.rb
- spec/services/migration/migrators/user_spec.rb
[Jira-3515](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=unassigned%2C712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3515)
If we only have unverified TRNs on the ECF user we want to fallback to these, prioritising them over the NPQ user TRN (even if it is verified).
- Fallback to unverified ECF TRNs in user migration
| Main | This branch |
| -- | -- |
| <img width="1006" alt="Screenshot 2024-10-03 at 08 43 23" src="https://github.com/user-attachments/assets/9b9b4338-bb8e-48aa-9572-c82daa104b72"> | <img width="1022" alt="Screenshot 2024-10-03 at 10 53 59" src="https://github.com/user-attachments/assets/eb5b75cd-63df-4b92-a170-0f898bfac9fe"> |
> Fallback to unverified ECF TRNs in user migration

- app/views/pages/accessibility.html.erb
[Update accessibility statement](https://dfedigital.atlassian.net/jira/software/projects/CPDNPQ/boards/137?assignee=70121%3Ab01fb7c9-60af-4b96-80c8-e647556514be&selectedIssue=CPDNPQ-2008)
Main change is adding in the non compliances.
> update accessibility statement following audit

- app/services/migration/migrators/application.rb
- spec/services/migration/migrators/application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3538
* Initialize new application on NPQ when it does not exist during migration.
> [CPDLP-3538] Data cleanup - Create Application in NPQ in migration

- app/views/accounts/_active_application_table.html.erb
- app/views/accounts/_course_details.html.erb
- app/views/accounts/_in_review_funding_details.html.erb
- app/views/accounts/_provider_pending_status.html.erb
- app/views/accounts/show.html.erb
- app/views/accounts/user_registrations/show.html.erb
- config/locales/en.yml
- spec/features/journeys/happy_paths/when_choose_maths_course_spec.rb
- spec/support/helpers/journey_step_helper.rb
[Fix 4 out of 5 accessibility issues](https://dfedigital.atlassian.net/jira/software/projects/CPDNPQ/boards/137?assignee=70121%3Ab01fb7c9-60af-4b96-80c8-e647556514be&selectedIssue=CPDNPQ-1998). I will address issue no. 4 as a separate ticket/PR. Also fix n+1 queries. 
| Before | After |
| --- | ----------- |
| ![Screenshot 2024-10-16 at 11 07 51](https://github.com/user-attachments/assets/8658543c-3736-4809-888c-95d8eac5ee42) | ![Screenshot 2024-10-16 at 11 08 25](https://github.com/user-attachments/assets/18da0f21-bb02-4afd-be91-c02de86269e3) |
| ![Screenshot 2024-10-16 at 11 09 05](https://github.com/user-attachments/assets/60ac0fc7-7968-4c99-b763-c633f8ddee52) | ![Screenshot 2024-10-16 at 11 09 58](https://github.com/user-attachments/assets/2024fff9-eb7a-4a54-aab0-7137b27da6c9) |
| …
> Accessibility changes

- app/serializers/api/application_serializer.rb
- app/serializers/api/applications_csv_serializer.rb
- app/services/migration/migrators/application.rb
- spec/factories/applications.rb
- spec/serializers/api/application_serializer_spec.rb
- spec/serializers/api/applications_csv_serializer_spec.rb
- spec/services/migration/migrators/application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3680
* Removed migrator validation for `ukprn` on `Application`
* Set `ukprn` from ECF
* Updated `ApplicationSerializer` and `ApplicationsCsvSerializer` to use `application.ukprn` instead of `application.school.ukprn`
> [CPDLP-3680] Data cleanup - Fix school ukprn mismatch

- Dockerfile
Ticket: N/A
There's a code scanning alert. 
https://github.com/DFE-Digital/npq-registration/security/code-scanning/1
Fix the above alert.
> Fix code scanning alert: arguments in long RUN instructions should be sorted

- config/parity_check_endpoints.yml
Ticket: [CPDLP-3672](https://dfedigital.atlassian.net/browse/CPDLP-3672)
The ability to filter has been implemented, however we have not added all filters for all endpoints, only statements
- Add to the comparison yaml file all endpoint filters;
- Add them on their own and with conjunction with other filters;
Note:
- Hardcoded some filter values for ease but could make it dynamic if required (happy to discuss).
[CPDLP-3672]: https://dfedigital.atlassian.net/browse/CPDLP-3672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3672] Add parity check filter options to all endpoints

- app/services/migration/migrators/cohort.rb
- spec/services/migration/migrators/cohort_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3692
* Cohort migrator will set `funding_cap` true for 2024
> [CPDLP-3692] Data cleanup - Update cohort funded cap in migrator

- app/services/migration/migrators/school.rb
- spec/services/migration/migrators/school_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3710
* Updated `School` migrator to find based on `urn` only.
> [CPDLP-3710] Parity check - Look up school by URN only

- app/views/npq_separation/admin/applications/index.html.erb
- app/views/npq_separation/admin/applications/show.html.erb
- app/views/npq_separation/admin/users/_application.html.erb
- spec/views/npq_separation/admin/applications/index.html.erb_spec.rb
- spec/views/npq_separation/admin/applications/show.html.erb_spec.rb
- spec/views/npq_separation/admin/users/_application.html.erb_spec.rb
Ticket: [2184](https://dfedigital.atlassian.net/browse/CPDNPQ-2184)
The new admin screen listing applications errors out if any applications in the list are missing a school
* Added a view spec for the applications listing screen + fixed the assumption of a school being present
* Added a view spec for the _application partial + fixed the assumption of a school being present
failures:
> [CPDNPQ-2184] fix missing school

- terraform/application/config/production.tfvars.json
Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3523
We are adding an API to NPQ and need to upgrade our resources
Upgrade db tier in production
This will be applied outside hours on Friday 8/11/2024
failures:
> [CPDLP-3634] Upgrade database tier in NPQ production

- terraform/application/config/migration.tfvars.json
Upgrade the migration DB and webapp instance counts to match production for the performance testing.
> Bump migration env to match production

- .github/workflows/backup_production_database.yml
- .github/workflows/restore_azure_database.yml
- terraform/application/.terraform.lock.hcl
- terraform/application/config/migration.tfvars.json
Ticket: https://trello.com/c/drLgfoCB/2114-add-dr-workflows-to-cpd
Adding backup and restore workflows for Azure
https://github.com/DFE-Digital/npq-registration/actions/runs/11820207925/job/32931969356
https://github.com/DFE-Digital/npq-registration/actions/runs/11818530511/job/32926289949
> Adding restore for database

- app/controllers/application_controller.rb
- app/controllers/monitoring_controller.rb
- app/controllers/omniauth_controller.rb
- app/models/user.rb
- spec/models/user_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CPDNPQ-2229
> Optimize opening registration for ClosedRegistrationUsers

- app/views/registration_wizard/choose_childcare_provider.html.erb
- app/views/registration_wizard/choose_private_childcare_provider.html.erb
- app/views/registration_wizard/choose_school.html.erb
- config/locales/en.yml
- spec/features/journeys/happy_paths/when_choose_maths_course_spec.rb
- spec/features/journeys/sad_paths/school_not_in_england_spec.rb
- spec/support/helpers/journey_step_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2275
content updates to workplace and URN questions.
> [CPDNPQ-2275] content updates

- app/controllers/npq_separation/admin/applications/change_funding_eligibilities_controller.rb
- app/services/applications/change_funding_eligibility.rb
- app/views/npq_separation/admin/applications/change_funding_eligibilities/new.html.erb
- app/views/npq_separation/admin/applications/change_training_statuses/new.html.erb
- app/views/npq_separation/admin/applications/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/npq_separation/admin/applications_spec.rb
- spec/requests/npq_separation/admin/applications/change_funding_eligibilities_controller_spec.rb
- spec/services/applications/change_funding_eligibility_spec.rb
- spec/views/npq_separation/admin/applications/change_funding_eligibilities/new.html.erb_spec.rb
Ticket: [CPDNPQ-2155](https://dfedigital.atlassian.net/browse/CPDNPQ-2155)
As an admin user I need to update the funding eligibility on an application
1. Add a service + specs to validate and update the change to the training
2. Added a controller + view + specs to utilise the service to update the training status
3. Added a feature spec to verify the workflow
[CPDNPQ-2155]: https://dfedigital.atlassian.net/browse/CPDNPQ-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDNPQ-2155] Manage funding eligibility

- lib/tasks/one_off/create_contract.rake
- spec/lib/tasks/one_off/create_contract_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2363
EHCO contract missing for LLSE in 2023 cohort
new rake task - as existing `update_contracts_2350.rake` rake task only updates existing contract values
> [CPDNPQ-2363] one off rake task to create contract

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
Reverts DFE-Digital/npq-registration#2089
Put staging back to how it was
> Revert "[CPDNPQ-2357] Make staging auth operate like production"

- app/controllers/application_controller.rb
- app/controllers/session_wizard_controller.rb
- config/environments/review.rb
- config/environments/sandbox.rb
- config/environments/staging.rb
- config/initializers/rack_attack.rb
- spec/requests/npq_separation/admin_controller_spec.rb
- spec/requests/rate_limiting_spec.rb
Ticket: [CPDNPQ-2482](https://dfedigital.atlassian.net/browse/CPDNPQ-2482)
We don't want users to login regularly rather than maintaining long-lived sessions
1. Set a maximum session lifetime of 12 hours
2. Fix the rate limiting on the session login end points
3. Enable rate limiting in `review`, `staging`, and `sandbox` environments
[CPDNPQ-2482]: https://dfedigital.atlassian.net/browse/CPDNPQ-2482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CPDNPQ-2482 Expire sessions

- spec/services/statements/query_spec.rb
No ticket as it's so tiny, but I've seen this one fail a few times — this should fix it!
> Fix intermittent duplicate statement test failure

- .github/workflows/deploy.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2336
slack notification for deployment failure on sandbox, staging and production
> [CPDNPQ-2336] notify slack on deploy failure

- lib/tasks/one_off/create_contract.rake
- spec/lib/tasks/one_off/create_contract_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2538
contract needs to be created for Feb 2025 statement, 2023 cohort
amend existing rake task
> [CPDNPQ-2538] make task work for Feb-25 statement

- terraform/application/config/production.tfvars.json
Ticket: [CPDNPQ-2596](https://dfedigital.atlassian.net/browse/CPDNPQ-2596)
To test the scaling up and to allow for the potential surge on monday
1. Increase the number of webapps from 12 to 16
failures:
[CPDNPQ-2596]: https://dfedigital.atlassian.net/browse/CPDNPQ-2596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDNPQ-2596] Pre-emptively scale up the service

- app/views/accounts/_eligible_for_funding_details.html.erb
- app/views/accounts/_funding_details.html.erb
- app/views/accounts/_in_review_funding_details.html.erb
- app/views/registration_wizard/ehco_possible_funding.html.erb
- app/views/registration_wizard/possible_funding/_eligible_for_scholarship_funding.html.erb
- app/views/registration_wizard/possible_funding/_eligible_for_scholarship_funding_not_tsf.html.erb
- app/views/registration_wizard/possible_funding/_funding_eligibility_senco.html.erb
- app/views/registration_wizard/possible_funding/_funding_eligibility_unclear.html.erb
- app/views/registration_wizard/possible_funding/_funding_eligible_maths.html.erb
- app/views/registration_wizard/possible_funding/_lead_mentor.html.erb
- app/views/registration_wizard/possible_funding/_private_childcare_provider.html.erb
- config/locales/en.yml
- spec/features/journeys/happy_paths/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb
- spec/features/journeys/happy_paths/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb
- spec/features/journeys/happy_paths/when_choose_maths_course_spec.rb
- spec/features/journeys/happy_paths/while_not_currently_working_at_school_spec.rb
- spec/features/journeys/happy_paths/while_working_in_neither_a_school_nor_childcare_spec.rb
- spec/support/helpers/journey_step_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2540
> Wording changes for wizard and registration summary

- Gemfile
- Gemfile.lock
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2592
we are not on the latest version of the DfE analytics gem - this could mean some events are not being sent.
update to `v1.15.4`
> [CPDNPQ-2592] update dfe-analytics gem

- app/views/accounts/_eligible_for_funding_details.html.erb
- app/views/registration_wizard/start.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2591
Change `space` to `place`.
Also, fix a typo: `chosed` -> `chosen`
> [CPDNPQ-2591] change space to place

- app/services/funding_eligibility.rb
- spec/services/funding_eligibility_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2631
Basically rolling back the change from https://dfedigital.atlassian.net/browse/CPDNPQ-2533.
All schools should be eligible for funding for EYL
> [CPDNPQ-2631] schools are always eligible for npq-early-years-leadership

- app/helpers/application_helper.rb
- spec/features/course_start_date_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2616
> Use hardcoded course start date

- lib/tasks/update_application.rake
- spec/lib/tasks/update_application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2626
new rake task: `rake 'update_application:change_cohort[<application_ecf_id>,<cohort_start_year>]'`
> [CPDNPQ-2626-] rake task to update application cohort

- app/services/funding_eligibility.rb
- spec/services/funding_eligibility_spec.rb
There was a bug that prevented LA from accessing EYL.
> Local Authority (LA) disadvantaged nurseries are eligible for all courses

- spec/rails_helper.rb
Ticket: BAU
PRs are still timing out connecting to chrome
1. Increased timeouts further
> [BAU] increase process timeout for cuprite

- app/services/exporters/tad_data_request.rb
- lib/tasks/tad_requests/autumn_2023.rake
- lib/tasks/tad_requests/spring_2022.rake
- spec/services/exporters/tad_data_request_spec.rb
[Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1757](https://dfedigital.atlassian.net/browse/CPDNPQ-1757)
> Create service class for TAD request and 2 rake tasks for execution

- app/models/user.rb
- spec/models/user_spec.rb
- spec/support/shared_contexts/with_activerecord_flipper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2510
Change how feature flagged users are retrieved to improve performance and reduce the likelihood of nil values, and write associated tests.
> Fix feature flags bug

- .github/actions/backup-and-restore-snapshot-database/action.yml
Ticket: BAU
Snapshot DB updating was left commented out in the github action
1. Uncomment it
> [BAU] re-enable rebuilding the snapshot db

- app/forms/questionnaires/possible_funding.rb
- app/services/funding_eligibility.rb
- spec/forms/questionnaires/possible_funding_spec.rb
- spec/services/funding_eligibility_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2715
> All young offender and hospital schools applications should be in review

- app/models/registration_wizard.rb
Ticket: [BAU]
Currently we check the step via several code paths but inconsistently
1. Push all checks through the same point to ensure InvalidStep gets raised where appropriate
> [BAU] Raise InvalidStep when accessing unknown steps

- lib/tasks/tad_requests/autumn_2023_npqll.rake
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2752
> Create TAD request for NPQLL

- app/views/api/guidance/release-notes.md
Updating the API release notes with changes to the sandbox environment.
Release notes for 14 April 2025 have been added.
failures:
> 14 April 2025 release notes

- docs/swagger.md
- public/api/docs/v3/swagger.yaml
- spec/requests/api/docs/v3/delivery_partners_spec.rb
- spec/requests/api/v3/delivery_partners_spec.rb
- spec/support/shared_examples/api_index_endpoint_documentation_support.rb
- spec/support/shared_examples/api_index_endpoint_support.rb
- spec/swagger_helper.rb
- spec/swagger_schemas/filters/list_delivery_partners.rb
- spec/swagger_schemas/models/delivery_partner.rb
- spec/swagger_schemas/responses/delivery_partner.rb
- spec/swagger_schemas/responses/delivery_partners.rb
- spec/swagger_schemas/sorting/delivery_partners.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2469
> [CPDNPQ-2469] delivery partner API swagger docs

- docs/connecting-to-azure.md
The URL for pending requests in the doc goes to the wrong place
update the URL to the correct one
> update URL to pending requests

- lib/tasks/update_application.rake
- spec/lib/tasks/update_application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2743
Need to update the schedule of an application in production
Add update_schedule task to update_application rake task
> [CPDNPQ-2743] add update_schedule task to update_application rake task

- app/views/api/guidance/get-started.md
We need to help users understand how to use the API whilst avoiding problems with syncing, polling and rate limits.
Added more details about what rate limits to use.
Added a new section on syncing data best practices, including how/when to poll the API and perform a full sync, as well as changing a funded place.
failures:
> Rate limits and  syncing data best practice info added

- .github/workflows/backup_production_database.yml
- .github/workflows/postgres-ptr.yml
- .github/workflows/restore_azure_database.yml
- terraform/application/config/sandbox.tfvars.json
There is a requirement for applications to be DR ready.
This PR add/enhances db related workflows
Database restore point in time workflow - new
DB PTR workflow run
TBD
https://trello.com/c/jLEVHLPd/2232-npq-plan-for-dr-test-april-2025
> Adding the DB PTR workflow, sandbox env for DR testing

- app/components/npq_separation/admin/course_payment_overview_component.html.erb
- app/components/npq_separation/admin/statement_selector_component.html.erb
- app/components/npq_separation/admin/statement_summary_component.html.erb
- app/components/npq_separation/admin/statement_summary_component.rb
- app/services/statements/summary_calculator.rb
- app/views/npq_separation/admin/finance/statements/show.html.erb
- config/locales/en.yml
- spec/components/npq_separation/admin/course_payment_overview_component_spec.rb
- spec/components/npq_separation/admin/statement_summary_component_spec.rb
- spec/features/npq_separation/admin/finance/statement_payment_spec.rb
- spec/features/npq_separation/admin/finance/statement_spec.rb
- spec/services/statements/summary_calculator_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2766
new design for statement page
- design updates only - no change to functionality, other than showing adjustments
- The only significant change to the content, is Participants is now Users within each course details card.
- updated `summary_calculator_spec.rb` to fully test `#total_payment`
> [CPDNPQ-2766] admin statement page updates

- app/models/user.rb
- spec/models/user_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2744
Adding missing specs to the `User` model, and removing a few unused methods.
> Add missing specs

- config/application.rb
Reverts DFE-Digital/npq-registration#2481
> Revert "[BAU] Use rails 7.1 defaults"

- app/views/api/guidance/index.html.erb
- app/views/api/guidance/schedules-and-milestone-all-course.md
We need to explain how schedules and milestones work and give a timeline of when each will happen/has happened for each given cohort. 
We've introduced a new page which goes into detail about when each schedule will happen and when each milestone will take place for each cohort (from 2021 - 2025)
> Added 'Schedules and milestone dates for NPQs' page.

- app/views/npq_separation/admin/applications/reviews/show.html.erb
- spec/features/npq_separation/admin/applications_in_review_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2565
Use consistent terminology when referring to application.user.ecf_id in the Applications in review section:
| ![Screenshot 2025-05-15 at 16 19 09](https://github.com/user-attachments/assets/9260c5ff-3597-4352-8dd2-17f6892a36e3) |   ![Screenshot 2025-05-15 at 16 22 31](https://github.com/user-attachments/assets/13eefe25-2331-4a00-a6d1-9e7a2303ed94)   |
| ![Screenshot 2025-05-15 at 16 19 49](https://github.com/user-attachments/assets/733fa2ce-d5fe-4a36-9b96-ad572b90da28)  | ![Screenshot 2025-05-15 at 16 24 04](https://github.com/user-attachments/assets/f14c731a-677a-45e2-8238-ea42e5716eed)    |
> Change 'Applicant ID' and 'Participant ID' to 'User ID'.

- app/services/applications/accept.rb
- spec/services/applications/accept_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2841
Currently, it is not possible to accept an application if there is already an accepted application with the same course and cohort.
When validating an accept request, we currently disallow it if there is already an application with the same course.
This PR adds cohort to that check, so we only disallow if there is already an application with the same course _and_ cohort.
> [CPDNPQ-2841] allow accepts if application is in same course but different cohort

- terraform/application/config/staging.tfvars.json
Ticket: https://trello.com/c/L7uN4Zsx
All services will be migrated to the workload identity federation for improved security on staging env
Enable federated authentication for Google Big query
**NA**
failures:
> Enable BQ on staging

- terraform/application/config/sandbox.tfvars.json
Ticket: https://trello.com/c/L7uN4Zsx
All services will be migrated to the workload identity federation for improved security on sandbox env
Enable federated authentication for Google Big query
**NA**
failures:
> Enable BQ on sandbox

- terraform/application/config/production.tfvars.json
Ticket: https://trello.com/c/L7uN4Zsx
All services will be migrated to the workload identity federation for improved security on production env
Enable federated authentication for Google Big query
**NA**
failures:
> Enable BQ on production

- app/services/one_off/migrate_declarations_between_statements.rb
- lib/tasks/one_off/move_declarations_from_jul25_to_jun25.rake
- spec/services/one_off/migrate_declarations_between_statements_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2900
Use existing `OneOff::MigrateDeclarationsBetweenStatements` to create rake task to move declarations and update `output_fee`.
Also improved output of rake task.
> [CPDNPQ-2900] move declarations

- app/models/financial_change_log.rb
- lib/tasks/one_off/add_missing_contracts_2896.rake
- spec/lib/tasks/one_off/add_missing_contracts_2896_spec.rb
One off rake task to create missing contracts.
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2896
> Create missing contracts for UCL

- app/services/one_off/migrate_declarations_between_statements.rb
- lib/tasks/one_off/move_declarations_from_jan26_to_jun25.rake
- spec/services/one_off/migrate_declarations_between_statements_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2939
Rake task to move UCL declarations - from Jan 2026 to June 2025
> [CPDNPQ-2939] move declarations

- app/components/npq_separation/navigation_structures/admin_navigation_structure.rb
- app/components/npq_separation/sub_navigation_component.rb
- app/controllers/npq_separation/admin/lead_provider_cohort_controller.rb
- app/controllers/npq_separation/admin/lead_providers_controller.rb
- app/views/layouts/admin.html.erb
- app/views/npq_separation/admin/lead_provider_cohort/show.html.erb
- app/views/npq_separation/admin/lead_providers/index.html.erb
- app/views/npq_separation/admin/lead_providers/show.html.erb
- config/routes.rb
- spec/components/npq_separation/sub_navigation_component_spec.rb
- spec/features/npq_separation/admin/lead_providers_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2904
Instead of showing a list of statements for each course provider,
show delivery partners for each course provider / cohort.
Updated side nav to match prototype.
> [CPDNPQ-2904] course provider pages

- app/controllers/npq_separation/admin/delivery_partners_controller.rb
- app/services/admin_service/delivery_partners_search.rb
- app/views/npq_separation/admin/delivery_partners/index.html.erb
- spec/features/npq_separation/admin/delivery_partners_spec.rb
- spec/services/admin_service/delivery_partners_search_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2906
search box for delivery partners
> [CPDNPQ-2906] delivery partner search

- app/views/npq_separation/admin/delivery_partners/index.html.erb
- spec/features/npq_separation/admin/delivery_partners_spec.rb
- spec/features/npq_separation/admin/delivery_partnerships_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2907
Before:
After:
> Copy changes

- app/views/npq_separation/admin/users/index.html.erb
- spec/features/npq_separation/admin/users_spec.rb
Ticket: 
https://dfedigital.atlassian.net/browse/CPDNPQ-2572
Content edits for consistency with rest of site
| ![Screenshot 2025-06-17 at 12 09 00](https://github.com/user-attachments/assets/a86b548a-a2bc-4e39-8e2e-61127c62f7a5)  | ![Screenshot 2025-06-17 at 12 08 31](https://github.com/user-attachments/assets/5e7feb3b-ae81-43bc-8b6a-eee774106481)    |
> Update content on users index page

- app/models/declaration.rb
- app/views/npq_separation/admin/users/_application.html.erb
- spec/features/npq_separation/admin/users_spec.rb
- spec/models/declaration_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2862
Adds `Training milestone reached` row.
> Display the highest attained milestone on the user overview page

- app/components/npq_separation/navigation_structures/admin_navigation_structure.rb
- app/views/npq_separation/admin/bulk_operations/index.html.erb
- config/routes.rb
- spec/components/npq_separation/navigation_structures/admin_navigation_structure_spec.rb
- spec/features/admin/bulk_operations/reject_applications_spec.rb
- spec/features/admin/bulk_operations/revert_applications_to_pending_spec.rb
- spec/features/admin/bulk_operations/update_and_verify_trns_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3042 (the description in the ticket is no longer correct - refer to the lucid board attached to the ticket for updated designs.)
**Before**
**After**
> Change 'Bulk operations' to 'Bulk changes'

- app/components/npq_separation/admin/statement_summary_component.html.erb
- app/controllers/npq_separation/admin/finance/statements/change_deadline_date_controller.rb
- app/controllers/npq_separation/admin/finance/statements/change_payment_date_controller.rb
- app/models/statement.rb
- app/services/statements/change_deadline_date.rb
- app/services/statements/change_payment_date.rb
- app/views/npq_separation/admin/finance/statements/change_deadline_date/show.html.erb
- app/views/npq_separation/admin/finance/statements/change_payment_date/show.html.erb
- app/views/npq_separation/admin/finance/statements/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/factories/statements.rb
- spec/features/npq_separation/admin/finance/statement_change_deadline_date_spec.rb
- spec/features/npq_separation/admin/finance/statement_change_payment_date_spec.rb
- spec/models/statement_spec.rb
- spec/services/one_off/migrate_declarations_between_statements_spec.rb
- spec/services/statements/change_deadline_date_spec.rb
- spec/services/statements/change_payment_date_spec.rb
- spec/services/statements/query_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3074
Allow statement payment date and deadline date to be changed via the admin console
e.g.
> [CPDNPQ-3074] admin update statement deadline and payment dates

- app/models/application.rb
- spec/models/application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3049
We have instances where previously funded applications are marked funded by policy. In such case, we need to make them fundable.
> Applications marked funded by policy are eligible even if previously funded

- app/views/api/guidance/release-notes.md
- app/views/api/guidance/roadmap.md
Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDNPQ/boards/137?assignee=61d42643ce3652006ab6cd2a&selectedIssue=CPDNPQ-3084
Making improvements to the API guidance so content is more accessible for users.
Roadmap has been edited with up and coming tasks added and the opening paragraphs have been improved.
Release notes have been given descriptive headings.
failures:
Release notes:
Roadmap:
> Release notes headings and Roadmap updated

- app/services/exporters/tad_senco_data_request.rb
- lib/tasks/tad_requests/autumn_2024_senco.rake
- lib/tasks/tad_requests/spring_2025_senco.rake
- spec/services/exporters/tad_senco_data_request_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3133
a new exporter: `TadSencoDataRequest` because this request is different to the previous requests.
> [CPDNPQ-3133] TAD request for SENCO

- db/seeds/base/add_childcare_providers.rb
- db/seeds/base/add_schools.rb
Ticket: BAU
It will make it easier to test parts of the registration wizard such as Funding Eligibility
1. Import all schools and childcare providers
failures:
> [BAU] Import all schools instead of a subset

- app/services/feature.rb
- spec/services/feature_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3115
Feature flag to hide potentially breaking api changes.
> Add LP_SELF_SERVE feature flag

- lib/tasks/tad_requests/autumn_2023_npqeyl.rake
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1758
TAD request for NPQEYL. Uses an argument to specify the cohort.
> Add rake task for npqeyl tad request. 

- app/controllers/npq_separation/admin/schedules_controller.rb
- app/models/schedule.rb
- app/views/npq_separation/admin/schedules/destroy.html.erb
- config/locales/en.yml
- spec/features/npq_separation/admin/schedules_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3152
currently an unhandled error is raised
> [CPDNPQ-3152] show error when trying to delete schedule with applications
