DFE-Digital/npq-registration

config/application.rb, config/initializers/secure_headers.rb
Changes in application config are overridden by secure_headers
=> Set x-xss-protection using secure_headers

config/manifests/staging-manifest.yml
Reverts DFE-Digital/npq-registration#44
Pentest has now finished so we can revert this.
=> Revert "Temporarily use ECF test environment"

app/lib/forms/contact_details.rb, spec/lib/forms/contact_details_spec.rb
- In sandbox env we do not send out emails
- So providers can enter data and complete the journey in sandbox we display the confirmation code on the screen instead of sending them an email
- Existing journey outside to sandbox should be identical
=> display email confirmation code in sandbox

app/lib/forms/check_answers.rb, app/lib/services/npq_profile_creator.rb, db/migrate/20210715092732_add_ni_number_to_users.rb, db/schema.rb, spec/features/happy_journeys_spec.rb, spec/features/sad_journeys_spec.rb, spec/lib/services/npq_profile_creator_spec.rb
- We need to persist NI number for validation if users cannot be validated automatically. It will be used for manual validation
- Persist NI number if TRN cannot be automatically be validated
- Send NI Number to ECF if record could not be automatically be validated assuming user has entered it
- Depends on https://github.com/DFE-Digital/early-careers-framework/pull/699 being deployed to production
=> Persist and send NINO

app/webpacker/packs/school-picker.js
- This allows IE10 user to complete a journey successfully with JS
- IE10 does not support `dataset` and use `getAttribute` instead
- none
=> Allow IE10 user to use JS school picker

README.md, app/controllers/registration_wizard_controller.rb, app/lib/forms/base.rb, app/lib/forms/check_answers.rb, spec/features/short_circuiting_pages_spec.rb
- users are submitting their application the hitting the browser back button back to the check answers page
- to prevent them visiting this page again which causes an error we do a basic check which then redirects them back to the root_path
=> Fix visiting check answers page directly

app/lib/forms/qualified_teacher_check.rb, spec/lib/forms/qualified_teacher_check_spec.rb
- users are entering their titles in full names
- we remove this as it negatively impacts auto validation
=> strip of title prefixes from full_name

.rubocop.yml, app/lib/services/importers/manual_validation.rb, spec/factories/applications.rb, spec/lib/services/importers/manual_validation_spec.rb
- Import manual validation CSV
- Double entry required. Meaning this data also needs to be applied to ECF
- As there is no mechanism at the moment to sync
=> add csv importer for manual validation

app/lib/services/import_gias_schools.rb, app/models/school.rb, db/migrate/20210730094220_add_postcode_without_spaces.rb, db/schema.rb, spec/lib/services/import_gias_schools_spec.rb, spec/requests/schools_spec.rb
- My first attempt was using a `GENERATED` postgres column introduced in postgres 12. However Rails don't seem to support this out the box and caused more pain than not
- So this is the basic fix of simply duping the postcode and we have to maintain this application side
- After deployment I will hotfix data on all environments to ensure this feature is available
=> Spaceless postcodes

app/views/registration_wizard/qualified_teacher_check.html.erb
- Users seem to be chopping the first 2 numbers of TRNs
- hoping a copy change should rectify this problem
- however under the hood it allows 5 to 7
- Copy change
- none
=> Revert copy to exactly 7 digit TRN

app/lib/services/funding_eligibility.rb, spec/lib/services/funding_eligibility_spec.rb
- `Academy alternative provision sponsor led` (coded as `43`) are now eligible for funding
- Make schools with `establishment_type_code` `43` now eligible for funding
- Tweak tests so they run through every single scenario as opposed to sampling an example to test
- Any applications with this type will be retrospectively be given funding if there are any such applications
- none
=> add eligibility for school establishment type 43

app/lib/forms/qualified_teacher_check.rb, spec/lib/forms/qualified_teacher_check_spec.rb
- There are still cases of users entering titles into their full name and slipping through
- Adds additional case where we strip the title from the name
- none
=> extra cases for removing titles from names

app/views/registration_wizard/contact_details.html.erb
- this matches the prototype
- account area was never finished so is more of a dead end than of use
- some using are clicking this link to the dead end which is proving problematic
- Remove link to sign in when asking for email address
- none
=> remove link to sign in

.rubocop.yml, app/lib/forms/check_answers.rb, spec/lib/forms/check_answers_spec.rb
- reporting is not capable of treating falsey (nil/false) as being the same
- so reporting is adding an extra slice when falsey should be grouped together
- ensure truthy/falsey `trn_auto_verified` is persisted as a boolean value
- none
=> Persist trn_auto_verified as boolean

Gemfile, Gemfile.lock, app/lib/forms/base.rb, app/lib/forms/check_answers.rb, app/lib/forms/confirmation.rb, app/lib/forms/provider_check.rb, app/lib/forms/start.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, db/migrate/20210831105602_add_sessions_table.rb, db/schema.rb, spec/features/happy_journeys_spec.rb
- This is needed as there will be a breaking change over form data stored in the session in the future
- This would render existing data to be incompatible, causing errors
- Using a server side store we are able to reset sessions when we want
- This is not easy with a cookie based store
- Switch over from cookie store to databased backed store
- If the form data is missing for registration bounce users to the root path
- We can deploy this out of hours so direct effect so someone mid journey is minimised
- However those who come back to their journey will have to start again
- Those who hit submit `Continue` mid journey will get invalid authenticity csrf token. theres not much i can do about that
=> Use database sessions instead of cookie sessions

.github/workflows/export_dashboard_report.yml, .github/workflows/generate_dashboard_report.yml, app/lib/services/report.rb
- At the moment reporting is from NPQ only
- We want to join this up with ECF reporting
- We now export the id used in ECF for applications
- This allows joins in big query to made across datasets
- Able to run reporting on ad-hoc basis via workflow dispatch
- Exporting application_ecf_id in reporting
- none
=> Add ECF foreign key to reporting

app/lib/forms/qualified_teacher_check.rb, spec/lib/forms/qualified_teacher_check_spec.rb
- Users are entering their names with smart quotes and not "normal" apostrophes
- This causes an error on encoding when sending off to the API
- This is also how they appear to DQT so want to send "correct" name
- Convert smart apostrophes into "normal" apostrophes
- none
=> convert names with smart quotes to apostrophes

app/views/registration_wizard/funding_your_npq.html.erb
- Funding page radio labels were bold which does not match govuk component
- Unbold to match govuk component
Before
After
- none
=> funding radio labels no longer bold

app/models/application.rb, spec/models/application_spec.rb
- Changes to policy may affecting funding eligibility
- Support queries to create new applications on users behalf, this allows for a quick mechanism to workout the funding eligibility for an application
- Add convenience method that wraps a service to use on the command line as quick way to check funding eligibility for an application
- none
=> add convenience method on Application

app/lib/forms/check_answers.rb, app/lib/forms/choose_school.rb, app/lib/forms/possible_funding.rb, app/models/registration_wizard.rb, app/views/registration_wizard/possible_funding.html.erb, spec/features/happy_journeys_non_js_spec.rb, spec/lib/forms/check_answers_spec.rb, spec/lib/forms/choose_school_spec.rb, spec/lib/forms/possible_funding_spec.rb
- If we think user is eligible for funding we now show possible funding screen before the user checks their answers
- If they are not eligible for funding they would get the "Choose your funding" page instead
- Add extra page to journey
- Fixed back button on check answers page, now goes to where it should
- none
=> add possible funding page

app/models/registration_wizard.rb, spec/models/registration_wizard_spec.rb
- On ASO journey when user selects non DfE funding then backtracks to changes answers so DfE funding kicks in. The incorrect answers were shown on the check answers page
- Correctly identify when ASO needs funding and only then show funding choice on the check answers page 
- none
=> Only show ASO funding choice if it needs funding

app/models/registration_wizard.rb, app/views/registration_wizard/dqt_mismatch.html.erb, spec/features/happy_journeys_non_js_spec.rb, spec/features/happy_journeys_spec.rb, spec/features/sad_journeys_spec.rb, spec/views/registration_wizard/dqt_mismatch.html.erb_spec.rb
- https://trello.com/c/3Qt9d1hQ/576-playback-details-on-validation-failed-page
- After TRN auto validation failure playback entered data
- Slightly different content depending if optional NI number was entered or not
- Also fixed playing back of dates so they conform to govuk formatting
- none
=> playback data after TRN auto validation failure

.rubocop.yml, app/components/npq_panel.html.erb, app/components/npq_panel.rb, app/controllers/registration_wizard_controller.rb, app/lib/forms/base.rb, app/lib/forms/check_answers.rb, app/lib/forms/confirmation.rb, app/models/registration_wizard.rb, app/views/registration_wizard/confirmation.html.erb, spec/features/happy_journeys_non_js_spec.rb, spec/features/happy_journeys_spec.rb
- https://trello.com/c/c2B9Qrlx/597-playback-what-was-registered-for-on-the-confirmation-page
- To improve the confirmation page after user has completed their transaction
- Confirmation page panel playbacks chosen course and provider
- The component library does not support classes on the body of the panel component, so a custom component is used
=> confirmation panel playbacks course and provider

.rubocop.yml, app/controllers/admin/applications_controller.rb, app/lib/services/admin/applications_search.rb, app/views/admin/applications/index.html.erb, spec/lib/services/admin/applications_search_spec.rb
- Admins want to the ability to locate applications more easily when users provider guids
- Admins can search for application via user guid or application guid
- none
=> grant admins ability to search by GUIDS

app/views/registration_wizard/dont_have_teacher_reference_number.html.erb
Ticket [1148](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDRP-1148)
Updated content for the 'dont-have-a-teacher-reference-number' page
Content taken from [npq prototype](https://npq-prototype.herokuapp.com/register/get-a-trn)
The prototype doesn't have links that open in new tabs but i've done it as we've had a ticket that added them in for all links that took you away from the service.
=> Update dont have a trn content

.rubocop.yml, app/lib/services/npq_profile_updater.rb, lib/tasks/sync_applications.rb, spec/lib/services/npq_profile_updater_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-852
Corresponding PR: https://github.com/DFE-Digital/early-careers-framework/pull/1622
Adds a rake task to sync all the `eligible_for_funding` statuses with ecf
=> Add rake task for syncing applications to ecf

lib/tasks/sync_applications.rake
- Rename file to .rake extension so it actually gets picked up by rake
- only select applications where the ecf_id is not null, there isn't a constraint on this and there is no point making a request without an id, it won't work
- Add a 100ms sleep between each iteration to reduce the chance of overloading ecf
- Add an order by so the task can be resumed from that point if it needs to be terminated for any reason
Previous PR: https://github.com/DFE-Digital/npq-registration/pull/285
=> Application sync task improvements

app/lib/services/report.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-858
We need a way of linking participant declarations and the applications in this report in bigquery. The participant declarations table already has the user id for ecf.
The join table proposed in the ticket isn't simple as the existing user id and participant ids are in different serviced. I spoke to Will and this approach is sufficient.
=> [CPDLP-838] Add ecf_user_id to report

app/controllers/interest_notification_sign_up_controller.rb, app/controllers/registration_interest_controller.rb, app/controllers/registration_wizard_controller.rb, app/lib/forms/chosen_start_date.rb, app/lib/forms/provider_check.rb, app/lib/forms/registration_interest_notification.rb, app/models/registration_interest.rb, app/models/registration_wizard.rb, app/views/interest_notification_sign_up/confirm.html.erb, app/views/interest_notification_sign_up/new.html.erb, app/views/registration_interest/confirm.html.erb, app/views/registration_interest/new.html.erb, app/views/registration_interest/no_notification.html.erb, app/views/registration_wizard/chosen_start_date.html.erb, app/views/registration_wizard/start.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20220125143328_create_registration_interests.rb, db/schema.rb, spec/factories/registration_interest.rb, spec/features/back_links_spec.rb, spec/features/email_confirmation_spec.rb, spec/features/happy_journeys_non_js_spec.rb, spec/features/happy_journeys_spec.rb, spec/features/registration_interest_spec.rb, spec/features/sad_journeys_spec.rb, spec/lib/forms/provider_check_spec.rb, spec/lib/forms/registration_interest_notification_spec.rb, spec/models/registration_interest_spec.rb
We want to create an EOI for those who haven't agreed a February start date with an NPQ provider. 
This will be done in 2 stages, soft close and hard close. 
Soft close - Go to NPQ registration site and start journey, they don't have an agreed start date and so submit an EOI to be notified when registrations reopen.
Hard close - Users go straight to `registration-interest/sign-up`. 
Both routes are being shown at the same time for a brief period. One linking via registration path, another from the gov uk page. 
- Updated routes for soft and hard close path
- New registration interests table to capture email addresses
- New first page after starting registration journey
- Notification sign up via the registration journey route(soft-close)
- Notification sign up via direct route, which will …
=> [CST-252] EOI for autumn 2022 

public/location-autocomplete-graph.json
6e2dbde attempted to remove some historic countries from the autocomplete graph but it was only partially done. You need to delete the sub-alias countries when a top-level country code is removed.
=> Fix removal of historic countries

package.json, yarn.lock
There was an error when trying to run the webpack dev server after a fresh install. This is because webpack-dev-server 4.x is no longer compatible with webpacker 5.x.
https://github.com/rails/rails/issues/43062#issuecomment-905755202
webpacker 6 doesn't have a stable release yet so it is not an option to upgrade, we need to downgrade webpack-dev-server
=> Downgrade webpack-dev-server to version 3

app/lib/services/handle_submission_for_store.rb, spec/lib/services/handle_submission_for_store_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-364
The only way a non-nil value can be here is if the user originally originally selected an ineligible route, selected a funding choice and then backtracked to an eligible one, so the value should be discarded.
=> CST-364 Clear funding choice on submission for funding eligible applications

config/initializers/sentry.rb
We are reaching our transaction limits so we can safely reduce the sampler rate.
=> Lower Sentry sample rate 0.1 to 0.01

app/lib/services/handle_submission_for_store.rb, app/lib/services/npq_profile_creator.rb, db/migrate/20220224121536_add_work_information_to_applications.rb, db/schema.rb, spec/lib/services/npq_profile_creator_spec.rb
All the employment questions are currently only stored in session and the answers are lost on submission. This PR is to fix this.
=> Storing employment details on applications

app/controllers/registration_wizard_controller.rb, app/lib/forms/base.rb, app/lib/forms/closed.rb, app/lib/services/feature.rb, app/models/registration_wizard.rb, app/views/interest_notification_sign_up/new.html.erb, app/views/registration_wizard/closed.html.erb, spec/features/registration_interest_spec.rb, spec/features/service_closed_spec.rb, spec/lib/services/feature_spec.rb, spec/models/registration_wizard_spec.rb
We need to close NPQ registration journey in time for the ‘hard close’ deadline of 11th March 2022. Registration should close at March 12th 00:00:00. 
At this time the registration wizard will stop working and all pages within it will become the close page.
This PR allows some flexibility to add a time to reopen registrations later.
=> Add ability to close registrations

app/lib/services/feature.rb, spec/features/service_closed_spec.rb, spec/lib/services/feature_spec.rb, spec/models/registration_wizard_spec.rb
We recently closed the NPQ reg service after a certain date had passed. This date has passed and the service is closed. However, we would still like to test on other environments as if the service is still open.
This PR closes the service _only_ in the actual prod environment.
=> Enable features only in production

.github/workflows/export_dashboard_report.yml
[This](https://github.com/DFE-Digital/npq-registration/runs/5638135417?check_suite_focus=true) action was failing jobs with:
```
Warning: google-github-actions/setup-gcloud is pinned at "master". We strongly advise against pinning to "@master" as it may be unstable. Please update your GitHub Action YAML from:
uses: 'google-github-actions/setup-gcloud@master'
to:
uses: 'google-github-actions/setup-gcloud@v0'
Alternatively, you can pin to any git tag or git SHA in the repository.
```
I have followed the advice and pinned to v0.
=> Pin GitHub action setup-gcloud

app/lib/forms/childcare_provider_not_in_england.rb, app/lib/forms/choose_childcare_provider.rb, app/lib/forms/dqt_mismatch.rb, app/lib/forms/find_childcare_provider.rb, app/lib/forms/helpers/institution.rb, app/lib/forms/qualified_teacher_check.rb, app/lib/services/query_store.rb, app/models/registration_wizard.rb, app/views/registration_wizard/childcare_provider_not_in_england.html.erb, app/views/registration_wizard/choose_childcare_provider.html.erb, app/views/registration_wizard/find_childcare_provider.html.erb, app/webpacker/packs/application.js, app/webpacker/packs/institution-picker.js, config/locales/en.yml, spec/lib/forms/dqt_mismatch_spec.rb, spec/lib/forms/qualified_teacher_check_spec.rb
https://dfedigital.atlassian.net/browse/CN-110
Users who mark themselves as working in a public nursery rather than a school should be directed to a find/choose your nursery path. We want to use the same data for both rather than showing just schools in the school path and just nurseries in the nursery path. This is because which path you end up going down depends in some cases on your perception of whether you’re a part of a school or a nursery. Where these are the same entity it can be unclear which path someone will pick. To resolve that we let people pick either regardless of the path they take.
- Add `/registration/find-childcare-provider` page for selecting nursery location
- Add `/registration/choose-childcare-provider` page for searching nursery within location from find page
=> [CN-110] Add "Choose Nursery" pathway for public nurseries

app/views/admin/applications/show.html.erb, spec/page_objects/admin/application_page.rb, spec/views/admin/applications/show.html.erb_spec.rb
- Admins are not able to see `Targeted support funding eligibility` flag
- Adding this will enable this and also help with PO review to ensure everything is working as expected
- In admin area surface `Targeted support funding eligibility` when viewing an application
- Login as an admin
- View applications
- Should be a field labelled `Targeted support funding eligibility` which correctly mirrors that of the viewed application
=> add Targeted support funding eligibility to admin

app/views/admin/applications/show.html.erb, config/locales/en.yml, spec/views/admin/applications/show.html.erb_spec.rb
- https://dfedigital.atlassian.net/browse/CN-46
- Support are struggling to identify when applications were made to help with helping support queries
- Expose `created_at` of an applications in admin area
- Login into admin area
- View an application
- Should see when application was created
=> add application created at to admin area

app/lib/services/handle_submission_for_store.rb, spec/lib/services/handle_submission_for_store_spec.rb
- Bug when a headteacher of over five years applies, headteacher status would be incorrect
- When headteacher of over five year applies headteacher status is now correctly set to `yes_over_five_years`
- Apply for ECHO as headteacher with over 5 years as headteacher
- Application should result in headteacher status of `yes_over_five_years`
=> fix headteacher_status when over five years

app/lib/services/ecf/npq_profile_creator.rb, spec/lib/services/ecf/npq_profile_creator_spec.rb
- https://dfedigital.atlassian.net/browse/CPDLP-1336
- Depends on https://github.com/DFE-Digital/early-careers-framework/pull/2082
- When sending over application to ECF the cohort is not currently included
- Therefore ECF is not able to determine which cohort the application is associated with
- On submission of application send over the cohort to ECF
- Locally you can run this branch with mainline of ECF
- Point NPQ app to ECF app
- Submit an application
- Should see new application with specified cohort, defaults to `2022`
=> [CPDLP-1336] Send cohort to ECF on submission

app/lib/forms/funding_your_npq.rb, config/locales/en.yml, spec/features/happy_journeys_spec.rb
We want to update the copy in the funding your npq page
Updated the copy based on the latest lucid flows.
I could see the same copy in the lucid flows for the `funding your aso` page too, so both pages were updated to keep the answers consistent.
=> [CN-97] Update the copy in the funding your npq page

app/lib/forms/choose_your_npq.rb, spec/lib/forms/choose_your_npq_spec.rb
All applicants should see the EHCO NPQ on the choose your NPQ page.
- Remove exception that removed the EHCO NPQ from the list of available NPQs
- Add specs to verify correctness of choose your NPQ options
1. Select a non-england catchment or say "No" to the "Do you work in a school question"
2. Continue through the form till the Choose your NPQ page
3. Confirm that EHCO is present
=> [CN-101] Display EHCO NPQ to all applicants

app/lib/forms/confirmation.rb, app/views/registration_wizard/confirmation.html.erb, spec/features/happy_journeys_non_js_spec.rb, spec/features/happy_journeys_spec.rb
This was displaying for the wrong applicants.
Display for the correct applicants.
Go through the flow applying for the NPQH NPQ and see that the NPQH information is displayed on the confirmation page.
=> [CN-91] Fix bug where NPQH info showed for EHCO applicants

app/lib/forms/choose_your_provider.rb, app/models/course.rb, app/models/lead_provider.rb, spec/lib/forms/choose_your_provider_spec.rb, spec/lib/services/handle_submission_for_store_spec.rb
Not all providers provider all NPQs. NPQEYL and NPQLL only have a subset of providers available to them.
- Add infrastructure for reducing available providers based on course selection
- Use new course provider selection system to restrict providers for NPQEYL and NPQLL course.
- Add in backend validation for lead provider selection.
1. Attempt to sign up for NPQEYL or NPQLL
2. Reach provider selection screen
3. Check that list is reduced to list of providers from ticket.
=> [CN-95] Show reduced list of LeadProviders for NPQEYL and NPQLL NPQs

app/lib/forms/ineligible_for_funding.rb, app/lib/services/funding_eligibility.rb, spec/lib/services/funding_eligibility_spec.rb
What `inside_catchment?` means has and will change over time. Referring to specifics of what this means within status codes could lead to them becoming misleading.
- Changes `school_outside_england_or_crown_dependencies` to `school_outside_catchment`
- Changes `early_years_outside_england_or_crown_dependencies` to `early_years_outside_catchment`
Apply for NPQ in a school/private childcare provider outside England, see that status code from rejection is one of the above new errors.
=> Remove references to England/Crown Dependencies in catchment related funding eligibility status codes

app/lib/services/funding_eligibility.rb, app/lib/services/handle_submission_for_store.rb, app/models/application.rb, app/models/registration_wizard.rb, spec/features/sad_journeys_spec.rb
Currently the calculation only checks for ASO when performing the new headteacher check, it should also perform this check for EHCO.
- Check if applicant is a new headteacher when applying for EHCO
Run through the EHCO flow and check that your funding is rejected if you say you're not in your first 5 years of headship.
=> [CN-72] Ensure EHCO rejection when not in first 5 years of headship

app/models/course.rb, db/seeds.rb, lib/tasks/courses.rake, spec/features/happy_journeys_non_js_spec.rb, spec/features/happy_journeys_spec.rb, spec/lib/forms/choose_your_npq_spec.rb, spec/models/course_spec.rb
[Ticket CN-160](https://dfedigital.atlassian.net/browse/CN-160)
We want to update the course names and their order to:
```
NPQ for Leading Teaching (NPQLT)
NPQ for Leading Behaviour and Culture (NPQLBC)
NPQ for Leading Teacher Development (NPQLTD)
NPQ for Leading Literacy (NPQLL)
NPQ for Senior Leadership (NPQSL)
NPQ for Headship (NPQH)
NPQ for Executive Leadership (NPQEL)
NPQ for Early Years Leadership (NPQEYL)
Early Headship Coaching Offer
```
1. update the course names in the Course model
2. update the seeds file
1. re-seed your local DBs with `rails db:seed:replant` and `RAILS_ENV=test rails db:seed:replant`. Warning: It will wipe out data from all the tables in your local envs and you may need to re-run the imports (see [README](https://github.com/DFE-Digital/npq-registration/blob/cou …
=> Update the Course names and positions

app/lib/services/funding_eligibility.rb, spec/lib/services/funding_eligibility_spec.rb
[Ticket CN-65](https://dfedigital.atlassian.net/browse/CN-65)
All schools with GIAS code 10 will be eligible for funding from 1st of June 2022.
Add code 10 to the `eligible_establishment_type_codes`.
The registration on production will open on 6 June which covers the 1st June 2022 requirement, so I didn't have to use any feature flags. In all other envs (dev/staging/sandboz) code 10 schools will be eligible the moment we merge this PR.
How to test it:
Go through the eligible school journey and make sure you choose a GIAS code 10 school (you can find one in your local db `School.where(establishment_type_code: 10)`). After choose an NPQ, you should see the funding eligibility page.
=> Flip GIAS code ten schools to funded for all NPQs

app/lib/forms/have_ofsted_urn.rb
If you said “Yes” to this question, then entered a URN, then came back and said no, it would act forever as if you had said Yes, because your institution identifier would remain. By wiping it out if you say no, we can be sure that your no answer is respected.
- Clear institution_identifier and institution_name if you say "no" to have_ofsted_urn question. 
1. Reach this page as a, so far, eligible for funding applicant
2. Say yes
3. Enter URN and select private childcare provider
4. Return to have_ofsted_urn page
5. Say no
6. On choose_your_npq page, select any NPQEYL
7. See ineligible for funding page instead of successful funding page
=> [CN-99] Fix bug related to changing answers

app/lib/ecf_api/base.rb, app/lib/ecf_api/npq_funding.rb, app/lib/forms/aso_new_headteacher.rb, app/lib/forms/aso_previously_funded.rb, app/lib/forms/choose_your_npq.rb, app/lib/forms/choose_your_provider.rb, app/lib/forms/ineligible_for_funding.rb, app/lib/services/funding_eligibility.rb, app/lib/services/handle_submission_for_store.rb, app/models/application.rb, app/models/course.rb, app/models/registration_wizard.rb, app/views/registration_wizard/aso_previously_funded.html.erb, app/views/registration_wizard/ineligible_for_funding/school/_has_already_been_funded.html.erb, spec/features/happy_journeys_non_js_spec.rb, spec/features/happy_journeys_spec.rb, spec/features/sad_journeys_spec.rb, spec/lib/forms/check_answers_spec.rb, spec/lib/forms/choose_your_npq_spec.rb, spec/lib/services/funding_eligibility_spec.rb, spec/lib/services/handle_submission_for_store_spec.rb, spec/models/application_spec.rb, spec/models/course_spec.rb, spec/models/registration_wizard_spec.rb, spec/support/api_responses.rb
[Ticket CN-22](https://dfedigital.atlassian.net/browse/CN-22)
We want users to not be eligible for scholarship funding for the same NPQ, if they have already received one in the past.
- Added the NpqFunding class to handle the api call
- Added a custom parser for the NpqFunding to parse the response from the ECF API
- Update the ineligibility copy
- Add an ineligibility page for the EHCO NPQ (a.k.a ASO)
- Update the funding eligibility service to require a TRN
- Added course mappings for the ECF course identifiers
The previously funded eligibility check is institution agnostic - will run for Schools, Early Years etc.
Also, the npq funding endpoint in the ECF API requires a TRN and a course identifier, but the NPQ service only knows the `ecf_id`. It make sense to update the ECF API at some …
=> Reject funded NPQs

app/lib/forms/choose_your_npq.rb, app/lib/services/query_store.rb, app/models/registration_wizard.rb, spec/features/happy_journeys_spec.rb, spec/lib/forms/choose_your_npq_spec.rb
There was a workaround within the system that allowed you to apply for an NPQ with a LeadProvider that didn't supply that NPQ. If you selected an NPQ they did provide, select the provider and then go back and change your NPQ, then you could submit with an invalid lead provider.
- Check LeadProvider on the choose_your_npq form object after save and clear the lead provider if it is no longer valid.
- Check for if LeadProvider is invalid during choose_your_npq next step to ensure user is asked to continue the flow from there and select a new provider.
1. Select NPQLBC
2. Progress to Choose Your Provider page
3. Select "Best Practice Network (home of Outstanding Leaders Partnership)" provider
4. Progress to Check answers page
5. Choose to change your NPQ
6. Select NPQLTD
7. See that you …
=> [CN-200] Invalid lead provider clearing

app/controllers/registration_wizard_controller.rb, app/lib/forms/ineligible_for_funding.rb
This was put in place for testing purposes, it is no longer needed and would be undesirable after release so I'm removing it.
- Remove param being passed through to registration wizard show pages
- Remove versions param from app/lib/forms/ineligible_for_funding.rb
=> Remove ability to show specific ineligibility page

app/lib/services/feature.rb, spec/lib/services/feature_spec.rb
In preparation for the relaunch next month I'm preparing this PR that will reopen registration once merged and deployed.
- Removes permanent closing
- Adds in an env variable for closing registration arbitrarily if required.
=> [CN-122] Turn registration back on

app/jobs/registration_open_notification_job.rb, app/lib/forms/contact_details.rb, app/lib/forms/registration_interest_notification.rb, app/models/registration_interest.rb, config/locales/en.yml, lib/tasks/registration_interest.rake, spec/lib/forms/registration_interest_notification_spec.rb
https://dfedigital.atlassian.net/browse/CN-47
- Add email validation to RegistrationInterests
- Remove non-breaking space from test domains array
- Add ability to send notification to all emails
=> [CN-47] Validate registration interest emails and allow sending to all remaining recipients

app/jobs/registration_open_notification_job.rb
We want to mark them notified regardless of validity so that they don’t get pulled up during future notification rounds.
=> [CN-47] Fix bug where invalid records are not marked as notified

app/models/application.rb, spec/factories/applications.rb, spec/models/application_spec.rb
Minor bug, found whilst working on CN-217. calculate_funding_eligibility did not use the correct institution. As calculate_funding_eligibility isn't actually used anywhere other than the specs, this has not impacted any applications.
- Rename Application.calculate_funding_eligbility to Application.calculate_funding_eligibility
- Use the correct institution in Application.calculate_funding_eligibility
=> [CN-217] Look up correct institution when calling Application.calculate_funding_eligibility

app/models/private_childcare_provider.rb, app/models/registration_wizard.rb, spec/factories/private_childcare_provider.rb, spec/features/happy_journeys_spec.rb, spec/models/private_childcare_provider_spec.rb, spec/models/registration_wizard_spec.rb
in the check your answers page for EY users working in private nurseries
Ticket [CN-204](https://dfedigital.atlassian.net/browse/CN-204)
We want to replace the Nursery row in the check your answers page for EY users who work in private nurseries, with
- `Ofstead description details` when answering `yes` to the "Do you have a URN?" question. The value should be the same with the one displayed in the dropdown in the "Enter your or your employer's URN" page
- `Do you have a URN?` when answering `no` to the "Do you have a URN?" question
Introduce the `PrivateChildcareProvider#registration_details` method to return the ofsted registration details in the required format (`UNR - provider name - provider address`). The method respects providers with redacted info.
Add the required rows in the …
=> [CN-204] Display the Ofsted description instead of the private nursery name

app/controllers/session_wizard_controller.rb, app/lib/services/query_store.rb, app/models/registration_wizard.rb, app/views/registration_wizard/dqt_mismatch.html.erb
https://dfedigital.atlassian.net/browse/CN-234
I have attempted to track down how this is occurring but haven't been able to get a firm answer. Regardless of how this situation is reached, this PR will prevent a 500 error and allow the user to proceed. Adding in blocks to ensure this data is present before submission will be left up to a future ticket.
=> [CN-234] Add safe navigator for rendering date of birth

app/controllers/registration_wizard_controller.rb, app/lib/forms/base.rb, app/lib/forms/teacher_catchment.rb, app/lib/forms/work_in_childcare.rb, app/lib/forms/work_in_school.rb, spec/features/happy_journeys_spec.rb
https://dfedigital.atlassian.net/browse/CN-232
https://dfedigital.atlassian.net/browse/CN-230
This fixes a bug highlighted by sentry:
1. Say you don’t work in a school
2. Say you work in england
3. Say you don’t work in childcare
4. Reach the check your answers page without choosing a school
5. Click change on the do you work in a school question
6. Change your answer to yes
7. Attempt to finish your application
Instead of being asked what school you work at and appropriate other questions it will instead attempt to take you back to the check answers screen after the email entry question. At this stage it hits a 500 error because it doesn’t have a school name to output.
So what I’ve done is made it so that certain key questions that determine flow will direct you to the regular flow …
=> [CN-232] [CN-230] Return applicants to flow when core data changed

app/models/private_childcare_provider.rb, spec/features/happy_journeys_spec.rb, spec/models/private_childcare_provider_spec.rb
We want to hide the full address from the Ofsted description in the Check your answers page
Update the `PrivateChildcareProvider#registration_details` method to return the `urn and name` when info is not redacted and `urn - region` when info is redacted
=>   [CN-204] Hide the school full address in the Check your answers page

app/models/registration_wizard.rb
Ticket [CN-270](https://dfedigital.atlassian.net/browse/CN-270)
We want to re-arrange the rows in the Check your answers page to be in the following order:
```
- Where do you work
- Do you work in a school, academy trust, or 16 to 19 educational setting?”
- Full name
- TRN
- Date of birth
- National insurance number
- Email address
[Variable rows depending on where they work ]
- Course
[Variable if the user chooses EHCO]
[Variable for non-funded users]
- Provider
```
Move around the answers to match the desired results.
=> [CN-270] Update the answers order in the Check your answers page

Gemfile, Gemfile.lock, app/models/registration_interest.rb, app/validators/notify_email_validator.rb, spec/spec_helper.rb, spec/validators/notify_email_validator_spec.rb
- https://sentry.io/organizations/dfe-teacher-services/issues/3333847739
- Port ECF email validator for use with registration interest emails
=> Port ECF email validator for use with registration interest emails

app/lib/services/handle_submission_for_store.rb, app/models/application.rb, db/migrate/20220628094940_add_default_cohort_to_courses.rb, db/schema.rb, db/seeds.rb, spec/features/happy_journeys_non_js_spec.rb, spec/features/happy_journeys_spec.rb, spec/features/sad_journeys_spec.rb, spec/lib/services/handle_submission_for_store_spec.rb
- https://dfedigital.atlassian.net/browse/CPDLP-1472
- The business and providers and EHCO declarations to be paid for ASAP
- Therefore we will apply EHCO to the 2021 cohort so they can be paid out before the 2022 cohort starts
- All new EHCO applications will be applied the 2021 cohort
- Everything else remains the same with 2022 cohort
- none
=> new ehco applications applied 2021 cohort

app/lib/services/report.rb, spec/lib/services/report_spec.rb
Ticket [CPDLP-1466](https://dfedigital.atlassian.net/browse/CPDLP-1466)
There's a request to add the following application fields to data piped to BigQuery:
- targeted_delivery_funding_eligibility
- works_in_nursery
- works_in_childcare
- kind_of_nursery
- cohort
- private_childcare_provider_urn
- funding_eligibility_status_code
Add the fields to the `Report` service 
We have this [github workflow](https://github.com/DFE-Digital/npq-registration/actions/workflows/export_dashboard_report.yml) that pushes prod data to BigQuery every hour (can be also triggered manually). Check the new fields are in the `applications` BigQuery table after the workflow finishes.
=> Send additional NPQ fields to BigQuery

app/lib/services/eligibility/targeted_delivery_funding.rb, app/lib/services/handle_submission_for_store.rb, app/models/course.rb, spec/features/happy_journeys_non_js_spec.rb, spec/lib/services/eligibility/targeted_delivery_funding_spec.rb
[CN-237](https://dfedigital.atlassian.net/browse/CN-237)
`targeted_delivery_funding_eligibility` no longer ever returns true for EHCO or ASO courses.
=> [CN-237] Don’t mark EHCO courses as eligible for funding

Gemfile, Gemfile.lock
When moving to Ruby 3.1 some parts of the standard library [were moved to default gems](https://bugs.ruby-lang.org/issues/17873). While we're on Rails 6.x they need to be included in the gem file, as discussed in [this GitHub issue](https://github.com/mikel/mail/pull/1439#issuecomment-1002792758).
```
gem 'net-smtp'
gem 'net-imap'
gem 'net-pop'
```
Once we upgrade to Rails 7 these requirments can be dropped.
The relevant part of the log:
```
$ cf logs npq-registration-dev --recent
...
2022-07-20T11:26:40.86+0100 [APP/PROC/WEB/0] ERR /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require': cannot load such file -- net/pop
```
=> Attempted deployment fix by requiring default gems

app/lib/services/ehco/targeted_delivery_funding_eligibility_updater.rb, lib/tasks/ehco/update_targeted_delivery_funding_eligibility.rake, spec/lib/services/ehco/targeted_delivery_funding_eligibility_updater_spec.rb
https://dfedigital.atlassian.net/browse/CN-308
Adds rake task that updates `targeted_delivery_funding_eligibility` to false for all Application records with the EHCO course, `targeted_delivery_funding_eligibility` set to true, and where created after the relaunch.
1. Create an Application record with these attributes:
```
course == Course.ehco.first
created_at >= Services::Feature::REGISTRATION_OPEN_DATE
targeted_delivery_funding_eligibility == true
```
2. Run ehco:update_targeted_delivery_funding_eligibility:dry_run 
3. See that it has shown that this record will be updated
4. Check that targeted_delivery_funding_eligibility change has not been persisted.
5. Run ehco:update_targeted_delivery_funding_eligibility:run
6. Check that targeted_delivery_funding_eligibility change has been …
=> [CN-308] Retrospectively remove ECHO from targeted support funding eligibility

app/lib/forms/work_setting.rb, app/lib/forms/your_work.rb, app/lib/services/query_store.rb, app/models/registration_wizard.rb, spec/features/happy_journeys/js/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb, spec/features/happy_journeys/js/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb, spec/features/happy_journeys/js/while_not_currently_working_at_school_spec.rb, spec/features/happy_journeys/js/while_working_in_neither_a_school_nor_childcare_spec.rb
Follows on from #475
Jira Ticket: [CN-432](https://dfedigital.atlassian.net/browse/CN-432)
The 'how are you paying' page could confuse non-school users so it has been removed. The corresponding answer has been removed on the check your answers page for any users who don't work in a school or in early years.
The original ticket states:
> A user selects ‘no’ to both the ‘works in a school’ 'works in early years childcare’ questions
These questions were combined into a single page ('what setting do you work in?') in #475 so this has been interpreted to mean the user picked 'Other'.
=> [CN-432] Remove 'how are you paying' page from non-school flow

app/lib/forms/choose_childcare_provider.rb, app/lib/forms/choose_private_childcare_provider.rb, app/lib/forms/choose_school.rb, app/views/registration_wizard/choose_childcare_provider.html.erb, app/views/registration_wizard/choose_private_childcare_provider.html.erb, app/views/registration_wizard/choose_school.html.erb, app/views/registration_wizard/find_childcare_provider.html.erb, app/views/registration_wizard/find_school.html.erb, app/webpacker/packs/application.js, spec/features/happy_journeys/js/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb, spec/features/happy_journeys/js/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb, spec/features/happy_journeys/js/changing_from_outside_of_catchment_area_to_inside_spec.rb, spec/features/happy_journeys/js/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb, spec/features/happy_journeys/js/via_using_old_name_and_not_headship_spec.rb, spec/features/happy_journeys/js/via_using_same_name_spec.rb, spec/features/happy_journeys/js/while_working_at_public_nursery_spec.rb, spec/features/happy_journeys/non_js/able_to_receive_targeted_delivery_funding_spec.rb, spec/features/happy_journeys/non_js/funded_ehco_registration_journey_spec.rb, spec/features/happy_journeys/non_js/other_funded_ehco_registration_journey_spec.rb, spec/features/happy_journeys/non_js/via_using_old_name_and_not_headship_spec.rb, spec/features/happy_journeys/non_js/via_using_same_name_spec.rb, spec/features/sad_journeys/applying_for_ehco_but_not_new_headteacher_spec.rb, spec/features/sad_journeys/dqt_mismatch_spec.rb, spec/features/sad_journeys/school_not_in_england_spec.rb
https://dfedigital.atlassian.net/browse/CN-391
- Update copy on find-school page
- Update copy on choose-school page
- Update copy on find-childcare-provider page
- Update copy on choose childcare provider page
- Rename the display_…? methods to be descriptive
I renamed the display_schools? and display_childcare_providers? methods to display_no_javascript_fallback_form?. I did this to make it immediately obvious what they control. That these sections of code are in place to enable to no-js fallback for selecting your institution.
- Fix copy on choose-private-childcare-provider page
- Add no-JS flow to private childcare provider form
Ticket on Jira details the required copy and has links to the prototype. Compare copy on find-school , choose-school, find-childcare-provider, and …
=> [CN-391] Update copy for School and Public Nursery flows

config/locales/en.yml
Removes the `work_in_school` entry from the locales file, it should have been dropped in #475
=> Remove unneeded work in school localisation

package.json, yarn.lock
I was running into this issue when I ran under the latest upgrade when webpack-dev-server version was set to ~4:
```
✗ ./bin/webpack-dev-server
../node_modules/webpack-cli/bin/utils/prompt-command.js:46
return func(...args);
^
TypeError: Class constructor ServeCommand cannot be invoked without 'new'
```
Peter confirmed that upgrading caused this to start occuring.
- Fix version to ~3.
=> Fix webpack-dev-server to ~3

.github/workflows/deploy_to_review_app.yml, .github/workflows/destroy_review_app.yml, config/manifests/review-app-manifest.yml
Adds two Github actions:
- Push PR to Review App: On PR opening, reopening, or push deploys branch as a dedicated app, uses the shared review-app DB for storage.
- Destroy Review App: On PR closing deletes review app.
You can see below the message posted by Github actions linking to the reivew app.
=> Add Github Workflow for creating review apps when PRs are filed

.github/workflows/deploy_to_sandbox.yml, .github/workflows/deploy_to_staging.yml
Tests the tagging
Tests swapping manual deploy environments to automatic deploys
Brings new system live
Removes unnecessary tags
Staging will no longer be relevant as a staging ground once we are going live automatically.
Start auto-deploying staging/sandbox
=> Automatically deploy main to staging and sandbox

.github/workflows/deploy_to_production.yml
Tests the tagging
Tests swapping manual deploy environments to automatic deploys
Brings new system live
Removes unnecessary tags
Staging will no longer be relevant as a staging ground once we are going live automatically.
Start auto-deploying production
=> Automatically deploy to production

app/lib/forms/choose_private_childcare_provider.rb, config/locales/en.yml, spec/lib/forms/choose_private_childcare_provider_spec.rb
[This bug](https://sentry.io/organizations/dfe-teacher-services/issues/3294833521/?project=5817541) has popped up a few times in Sentry over the last few months. The error message is
```
I18n::MissingInterpolationArgument: missing interpolation argument :urn in "No private
childcare providers with the URN %{urn} were found, please try again" ({:model=>
"Choose private childcare provider", :attribute=>"Institution identifier", :value=>
"School-123456"} given)
```
It happens because the `:invalid` error message in the locales file expects a `urn:` argument, which it received from the custom error message but not from the validates format macro.
- Add choose private childcare provider step specs
- Move institution identifier validation to method
=> Solve missing interpolation argument bug when validating institution identifiers

app/lib/forms/aso_headteacher.rb, app/lib/forms/aso_new_headteacher.rb, app/lib/forms/funding_your_aso.rb, app/views/registration_wizard/about_ehco.html.erb, app/views/registration_wizard/aso_funding_not_available.html.erb, app/views/registration_wizard/aso_headteacher.html.erb, app/views/registration_wizard/aso_new_headteacher.html.erb, app/views/registration_wizard/aso_possible_funding.html.erb, app/views/registration_wizard/aso_previously_funded.html.erb, app/views/registration_wizard/aso_unavailable.html.erb, app/views/registration_wizard/funding_your_aso.html.erb, app/views/registration_wizard/shared/_copy_page.html.erb, config/locales/en.yml, spec/features/happy_journeys/non_js/funded_ehco_registration_journey_spec.rb, spec/features/happy_journeys/non_js/other_funded_ehco_registration_journey_spec.rb, spec/features/sad_journeys/applying_for_ehco_but_not_new_headteacher_spec.rb, spec/support/helpers/journey_assertion_helper.rb
#512 continued the work of refactoring the question flow to use the new question_page shared templating system to improve code reuse and cut down on repetition.
This PR is aimed at expanding that system to the entire EHCO flow.
- Move EHCO questions to use the question_page template and use the `Forms::QuestionTypes` classes for their questions.
- Introduce app/views/registration_wizard/shared/_copy_page template for sharing logic between pure copy pages.
- Use copy_page template for all EHCO question free steps.
- https://npq-registration-review-app-522.london.cloudapps.digital/registration/aso_headteacher
- https://npq-registration-review-app-522.london.cloudapps.digital/registration/aso_new_headteacher
- https://npq-registration-review-app-522.london.cloudapps.digital/registration/fundi …
=> Refactor EHCO questions to use question_page templates introduced in #512

app/lib/services/admin/dashboard_stats.rb, spec/lib/services/admin/dashboard_stats_spec.rb
Noticed that figures oscillated through the day due to timing of when previous applications were made.
Fix the "last 7 days" cut off to midnight.
=> Use beginning of day for dashboard calculations

app/controllers/omniauth_controller.rb, app/lib/services/feature.rb
There’s an odd interaction at the moment.
If you’re not logged into an account when you return from the GAI flow it’ll create one for you in the database. It’ll then copy your feature flag ID from your session into that new user record so your flags remain consistent.
However, if you’re already logged in you’ll be using the feature flag ID off of your user record for determining whether you're in the pilot. If you then go through the GAI flow but register with a different email address it’ll create a new user in the database and it’ll get a new feature flag ID rather than having it copied over (because we don't want two users with the same flag ID). 
This can then mean that you’re on an account that isn’t in the pilot. This has happened during testing so we know it isn't just theoretical. …
=> Make sure users returning from GAI are in the GAI pilot

app/controllers/omniauth_controller.rb, app/lib/forms/confirmation.rb, lib/omniauth/strategies/tra_openid_connect.rb
For testing, and shared computers, we want to make sure that if you complete an application people can't re-use your TRA login. 
Mark session as needing to tell TRA to use a fresh session when NPQ applications completed.
=> Prompt TRA to clear login when application created

app/controllers/admin/unsynced_applications_controller.rb, app/models/application.rb, app/views/admin/_application_details.html.erb, app/views/admin/_layout.html.erb, app/views/admin/unsynced_applications/index.html.erb, app/views/admin/unsynced_applications/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/admin_spec.rb, spec/models/application_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-656
Unsynced users are users who have completed their application but we failed to link their record with an ECF user. This usually happens because they've used more than one email address and we already have their `ecf_id` on record.
| List of unsynced applications | Viewing an unsynced application |
| ----------- | ----------------- |
| ![image](https://user-images.githubusercontent.com/128088/202751318-5c62be6c-dfa8-488d-9f06-f0e7d44e730e.png) | ![image](https://user-images.githubusercontent.com/128088/202751193-e3c5107c-cba3-458e-8efe-fb7253433940.png) |
=> Add an unsynced user list to the admin section

app/components/status_box.html.erb, app/views/admin/show.html.erb
- Only capitalise first letter in dashboard sections as per [style guide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#capitalisation)
- Format dashboard counts with `#number_with_delimiter` so they are [easier to read](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#numbers)
e/a-to-z-of-gov-uk-style#numbers)
=> Format big numbers with commas on the dashboard

db/migrate/20221118124435_drop_unique_index_from_users_ecf_id.rb, db/schema.rb
I don't think this column needs to be unique. It tells us which user in the ECF application this record belongs to, but ECF users can have multiple email addresses (via their participant identities).
It causes problems when a person applies more than once with different email addresses. When submitting the NPQ application to ECF we hit an error caused the unique index on `users.ecf_id`, which was assigned to their original user record when they completed their first application.
The current solution is to manually 'move' the applications to their original user account and re-trigger the submission manually.
* users don't need to worry about which of their email addresses they use when applying for an NPQ
* it simplifies our submission process and avoids any manual intervention
* we'll end …
=> Remove the unique index from `User#ecf_id`

app/views/registration_wizard/confirmation.html.erb
We're no longer running UR sessions. 
Make copy more general about giving us feedback, rather than about getting called for research. 
This includes removing any reference to an incentive.
=> Remove amazon voucher incentive

app/views/pages/privacy_policy.html.erb, spec/features/disabled_get_an_identity_integration/privacy_policy_spec.rb, spec/features/privacy_policy_spec.rb
- Add 2 paras to the 'How we use your data' section to better encompass what we do with peoples data 
- Be clearer about what we mean re. 'informing government policy'
- Include 'run our services' in the 'improve our services' section - i.e. we need your information to make our services work (e.g. sharing information across services etc)
- be more user centred in the opening para - e.g. this is what happens when **you** register for an NPQ
Review the content: https://npq-registration-review-app-589.london.cloudapps.digital/privacy-policy
=> expand on how we use your data

app/lib/services/eligibility/targeted_delivery_funding.rb, app/lib/services/funding_eligibility.rb, app/lib/services/handle_submission_for_store.rb, spec/features/disabled_get_an_identity_integration/happy_journeys/js/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb, spec/features/disabled_get_an_identity_integration/happy_journeys/js/when_previously_funded_spec.rb, spec/features/disabled_get_an_identity_integration/happy_journeys/js/while_working_at_public_nursery_spec.rb, spec/features/disabled_get_an_identity_integration/happy_journeys/non_js/able_to_receive_targeted_delivery_funding_spec.rb, spec/features/disabled_get_an_identity_integration/happy_journeys/non_js/via_using_old_name_and_not_headship_spec.rb, spec/features/disabled_get_an_identity_integration/happy_journeys/non_js/via_using_same_name_spec.rb, spec/features/happy_journeys/js/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb, spec/features/happy_journeys/js/when_previously_funded_spec.rb, spec/features/happy_journeys/js/while_working_at_public_nursery_spec.rb, spec/features/happy_journeys/non_js/previously_received_targeted_delivery_funding_spec.rb, spec/features/happy_journeys/non_js/via_using_old_name_and_not_headship_spec.rb, spec/features/happy_journeys/non_js/via_using_same_name_spec.rb, spec/lib/forms/check_answers_spec.rb, spec/lib/forms/choose_your_npq_spec.rb, spec/lib/services/funding_eligibility_spec.rb, spec/lib/services/handle_submission_for_store_spec.rb, spec/models/registration_wizard_spec.rb, spec/support/api_responses.rb, spec/support/shared_contexts/stub_course_ecf_to_identifier_mappings.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-723
`targeted_delivery_funding_eligibility` is now filtered through a check to the ECF DB for whether the user has already been received targeted delivery funding for the course they have selected on an accepted application. If they have, they won't be funded.
I've moved the check for this into Services::FundingEligibility to make sure we don't make multiple queries to the ECF API.
=> [CPDNPQ-723] Only allow targeted delivery funding once

spec/features/happy_journeys/non_js/previously_received_targeted_delivery_funding_spec.rb
All the other mentions are now `nil` and the field no longer appears to be used.
For reference, all the assertions in the test prior to this change:
```bash
$ ag --nofilename works_in_nursery spec/ | strip-blank-lines | trim | sort | uniq -c
1 "works_in_nursery" => false,
50 "works_in_nursery" => nil,
```
=> Expect works_in_nursery to be nil not false

app/lib/services/ecf/ecf_user_creator.rb, app/lib/services/ecf/npq_profile_creator.rb, app/models/application.rb, app/models/ecf_sync_request_log.rb, app/models/user.rb, db/migrate/20221213151804_create_ecf_sync_request_logs.rb, db/schema.rb, spec/lib/services/ecf/ecf_user_creator_spec.rb, spec/lib/services/ecf/npq_profile_creator_spec.rb, spec/models/ecf_sync_request_log_spec.rb
We are building out a set of tools in the admin interface for making sure users are properly synced to the ECF DB. Right now there isn't explicit logging of the results of syncing, making it harder to see when and why a sync attempt failed.
- Add in DB logging for sync requests
=> [CPDNPQ-655] Record logs to the DB of sync requests to the ECF DB

app/lib/services/report.rb, spec/lib/services/report_spec.rb
We encountered a problem in BigQuery where the alignment of columns and headers had fallen out of sync. This PR removes the extra column.
It's difficult to see from the list how many of each there are so we're adding a test to ensure the numbers of headers and columns are equal.
- Add a spec that ensures columns and rows match up
- Remove the `works_in_nursery` column from the CSV
=> Make the headers and columns match in report CSV

config/manifests/prod-manifest.yml
We had some 'out of memory' crashes in prod. It looked like the Dashboard job might've been hungrier than expected. Boosting to 2G is a short term fix, we really should ensure the heavy lifting jobs are more efficient in the long run.
=> Increase worker memory to 2G

app/views/pages/_choose_an_npq_and_provider_content.erb, app/views/registration_wizard/start.html.erb
Update this link destination. 
| Current destination | Proposed destination |
| ------------- |:-------------:|
| <img width="602" alt="Screenshot 2022-12-28 at 12 57 42" src="https://user-images.githubusercontent.com/56349171/209815858-9ba9e762-e9c7-4d0f-b9f2-a2dc98398bcd.png">      | <img width="854" alt="Screenshot 2022-12-28 at 13 01 56" src="https://user-images.githubusercontent.com/56349171/209816367-74c3bcd1-168a-4378-b7ca-569542c520d1.png">     |
The 'Choose an NPQ and provider' page duplicates content on the PDTL site. The PDTL now lists providers. 
The 'Choose and NPQ and provider' page also shows if you answer 'No' to the question 'Have you already chosen an NPQ and provider?' 
I've proposed removing the provider list on this page for now, to avoid duplication with the PDTL …
=> link to PDTL site from home page

lib/private_childcare_providers/2022-08-31/childminder_agencies.csv
The files in the repo are actually from the March file. They should be the August file from https://www.gov.uk/government/statistics/childcare-providers-and-inspections-as-at-31-august-2022.
Update the files.
=> Update 2022-08-31 private childcare provider CSV files

.github/workflows/export_dashboard_report.yml
When we try to install postgresql-client without having run `apt-get update` first we try to pull an old version that's no longer in the repository, and get the following error:
```
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/postgresql-13/postgresql-client-13_13.8-0%2bdeb11u1_amd64.deb
```
Running apt-get update first should resolve it and pull the latest available one.
=> Run update before trying to install any packages

.github/workflows/export_dashboard_report.yml
We need to re-run `apt-get update` after adding a new source too other wise it won't find packages from the new repo.
=> Run apt-get update before installing cf7-cli

.github/workflows/export_dashboard_report.yml
So my previous attempt #634 wasn't quite right 🤦🏽‍♂️ 
The export dashboard report job failed for various reasons including:
```
gpg: no valid OpenPGP data found.
```
It seems that installing the `ca-certificates` helps.
This approach [definitely works](https://github.com/DFE-Digital/npq-registration/actions/runs/3839356212/jobs/6537007682) and has been tested.
=> Install ca-certificates before adding keys when running export dashboard report

app/controllers/admin/unsynced_users_controller.rb, spec/features/admin_spec.rb
They shouldn’t be synced since users and applications are only synced once an application is completed. To prevent confusion we should hide these in the interface.
Hide unsynced users that don't have applications from the unsynced users application interface.
=> Hide users without applications from unsynced users list

app/controllers/admin/unsynced_users_controller.rb, spec/features/admin_spec.rb
Without a distinct users appear twice due to the join
Apply distinct to the query
=> Only display users once in the unsynced users list

app/lib/forms/confirm_email.rb, app/models/user.rb, spec/features/happy_journeys/js/entering_different_email_in_get_an_identity_and_outside_pilot_spec.rb
The spec in this PR was created to replicate a bug that’s triggered 80 times over about 3 months ([viewable on Sentry here](https://sentry.io/organizations/dfe-teacher-services/issues/3792837223/?)) and leads to a full error page for users who encounter it that blocks progress. This flow seems like such an extreme edge-case that I'm not convinced that this is the trigger that lead to all 80 of those errors, but it is definitely *a* path to it triggering, so closing it is a positive change.
1. Go through the GAI flow without a verified TRN, return and be removed from the pilot as no TRN is returned.
2. Go through the non-GAI flow until you reach the email input, enter a different email to the one you used on GAI for a user that already exists that doesn’t have a TRN on the record. You will …
=> Copy feature flags to all users on login

.github/workflows/deploy_to_dev.yml, .github/workflows/deploy_to_production.yml, .github/workflows/deploy_to_review_app.yml, .github/workflows/deploy_to_sandbox.yml
https://github.com/moby/buildkit/issues/2251
=> Trying a build without any caching

.github/dependabot.yml
Dependabot can manage bumping e.g. `actions/checkout@v2` to `actions/checkout@v3` on our behalf, saving us time.
=> Automatically update github-actions with dependabot

app/controllers/omniauth_controller.rb
This change will detect issues preventing user records from updating. An example is this:
1. A user registered before the GAI pilot with email “mail@example.com”, this creates user A with email “mail@example.com” and no GAI ID.
2. After the pilot they registered via the GAI service with email “user@example.com”. This creates user B with the email “user@example.com” and a GAI ID.
3. The user then returns later to register again, entering user@example.com into GAI and logging into the GAI account with the ID corresponding to user B in our DB.
4. The user changes their email to “mail@example.com” in the GAI interface and proceeds back to NPQ.
5. The NPQ app tries to change the email on User B to “mail@example.com”. An error is encountered due to the uniqueness validation.
Currently this …
=> Raise GAI error if changes fail to persist

app/views/registration_wizard/start.html.erb
In user research, a user clicked on the 'choose an NPQ and provider' link when she had already chosen an NPQ and provider. 
Hypothesis:
Editing the link text and placement may help prevent people clicking the link when they don't need to. 
| Before  | After |
| ------------- |:-------------:|
| <img width="521" alt="Screenshot 2023-01-23 at 16 21 18" src="https://user-images.githubusercontent.com/56349171/214092384-639d6cc7-83cf-4ef7-b7be-cdd3bdda8430.png">     | <img width="561" alt="Screenshot 2023-01-23 at 16 21 45" src="https://user-images.githubusercontent.com/56349171/214092498-9fdb9b75-4efc-44ef-9081-ba99e024e281.png">     |
=> Edit start page in line with prototype

.github/workflows/deploy_to_review_app.yml
Revert "Merge pull request #657 from DFE-Digital/dependabot/github_actions/unsplash/comment-on-pr-1.3.1"
This reverts commit cbad78f3ea668d303d3eb77c334d1e4e3fb3dc93, reversing changes made to f90d7d6aa8f549d425a7d93e935c3c5af2a7a77f.
I need to look into why this was preventing proper commenting. Seems the minor update was not backwards compatible.
=> Revert #657 

.github/workflows/export_dashboard_report.yml
Reverts DFE-Digital/npq-registration#659
This PR also needs a corresponding change to the 'Export results to BigQuery action', the scheduled action has [started failing](https://github.com/DFE-Digital/npq-registration/actions/workflows/export_dashboard_report.yml).
=> Revert "Bump google-github-actions/setup-gcloud from 0 to 1"

app/lib/ecf_api/npq/base.rb, app/lib/ecf_api/npq/user.rb, app/lib/services/ecf/ecf_user_creator.rb, app/models/user.rb, app/views/admin/applications/_application_details.html.erb, app/views/admin/applications/index.html.erb, app/views/admin/unsynced_users/index.html.erb, app/views/admin/users/_user_details.html.erb, app/views/admin/users/index.html.erb, spec/lib/services/ecf/ecf_user_creator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-713
We need to sync GAI IDs across to the ECF DB during user creation. https://github.com/DFE-Digital/early-careers-framework/pull/2919 has added in a new API that replaces the old one, accepting the same params as the previous API along with get_an_identity_id.
Use the above mentioned new API when syncing users, sending a get_an_identity_id when available.
Flows we need to test: 
- Regular flow where you return from the Get an Identity interface with a TRN. This will leave your NPQ user account with a get an identity ID which should then get synced when you complete your application.
- Alterntive flow where you return from the Get an Identity interface without a TRN. This leaves your NPQ user account without a GAI ID, which should …
=> Use new NPQ API for syncing users

app/jobs/application_submission_job.rb, spec/factories/users.rb, spec/jobs/application_submission_job_spec.rb, spec/lib/services/admin/dashboard_stats_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-910
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-788
CPDNPQ-910 relates to a bug where pre-existing users that have acquired a get_an_identity_id would not have this new ID sync to the ECF database.
CPDNPQ-788 relates to an issue where once created new user information (email/full_name) would not be synced to the ECF database.
This PR updates the ApplicationSubmissionJob so that a user's information (get_an_identity_id, full_name, email) is always synced across to the ECF database.
- Update ECF with new user details on application submission for:
- Already synced and linked users
- Newly linked users where the ECF user already exists
=> [CPDNPQ-788] [CPDNPQ-910] Update ECF with user details in ApplicationSubmissionJob even when not creating a new user

config/initializers/courses.rb, config/locales/en.yml
Following merging this ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDNPQ/boards/137?assignee=637b9f9cf6c85b343c082909&selectedIssue=CPDNPQ-808
I've noticed that the hint text isn't as intended.
This hint text should be the same as in the prototype:
=> Update EHCO hint text in line with prototype

.github/workflows/update_course_definitions.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-808
Currently you have to log into the server to run these tasks. We should be working to avoid entering the console as much as possible and providing structured interfaces for interacting with data.
Adds a Github action to trigger a rake task on each environment that will update course definitions.
=> Add github action to run courses:update in all envs

app/views/registration_wizard/choose_your_npq.html.erb, config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-808
The styling on this page wasn't correct, the text overflow didn't match up along the page.
- Wrap hint text at 2/3rds.
- Move text into locales
- Use govuk classes for styling
| Before | After |
| - | - |
| <img width="984" alt="Screenshot 2023-02-27 at 14 37 11" src="https://user-images.githubusercontent.com/1465268/221592784-00bd5366-26aa-4fec-8606-ee0f0898b30a.png"> | <img width="983" alt="Screenshot 2023-02-27 at 14 38 03" src="https://user-images.githubusercontent.com/1465268/221592768-831fd6cf-42fe-44f9-95a0-9a619fe97460.png"> |
=> [CPDNPQ-808] Use govuk classes for styling ChooseYourNPQ page

.devcontainer/Dockerfile, .devcontainer/boot.sh, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, README.md
Enabled Codespaces for the app.
This should let content/interaction designers run the application without having to go through the process of getting Ruby, Node, PostgreSQL etc running locally. I've tested it and it works with a single click. Managed to get this going while on a call!
Code/approach borrowed from [this starter repo](https://github.com/luizkowalski/devcontainer-rails).
=> Enable Codespaces for NPQ

.github/workflows/test.yml, package.json
Bump node version for when docker build uses version 16 on yarn install
=> Bump node version in package.json

db/migrate/20230331120924_drop_unused_column_flipper_admin_access.rb, db/schema.rb, spec/lib/services/handle_submission_for_store_spec.rb, spec/support/helpers/journey_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-806
This column been replaced with super_admin, it needs removing now that it is not used by any code.
- Drop flipper_admin_access column and remove references to it within the codebase
=> [CPDNPQ-806] Drops flipper_admin_access column from uses table

app/lib/services/report.rb, spec/lib/services/report_spec.rb
We need this to be able to isolate non-school records in queries.
The corresponding column is ready and waiting in BigQuery:
=> Add employment_type to BigQuery upload

app/models/registration_wizard.rb, app/views/registration_wizard/childcare_provider_not_in_england.html.erb, config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1088
We are standardising on one page format across the app.
- Forms::ChildcareProviderNotInEngland moved to use copy_page template
=> [CPDNPQ-1088] Update childcare-provider-not-in-engalnd to use copy_page template

Gemfile, Gemfile.lock, app/lib/forms/question_types/check_box.rb, app/lib/forms/share_provider.rb, app/views/registration_wizard/share_provider.html.erb, app/views/registration_wizard/shared/questions/_check_box.html.erb, config/locales/en.yml, spec/lib/forms/share_provider_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1104
Just another part of the question_page migration
- Replaced the share_provider view with a common question partial.
- Created new type of question - check box
I was playing with an idea of CheckBoxGroup as well, however it seems there are some significant conceptual differences between a group and a single checkbox and in the end decided to write CheckBox as a standalone type of question rather than a very specific type of CheckBoxGroup.
=> Move share_provider to question_page system

app/views/registration_wizard/ineligible_for_funding.erb, config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1124
- Forms::IneligibleForFunding moved to use copy_page template
=> Update IneligibleForFunding Page to Use New Shared CopyPage Template

app/helpers/forms/flow_helper.rb, app/lib/forms/dont_have_teacher_reference_number.rb, app/lib/forms/get_an_identity_callback.rb, app/lib/forms/start.rb, app/lib/forms/teacher_reference_number.rb, app/models/registration_wizard.rb, app/views/registration_wizard/dont_have_teacher_reference_number.html.erb, app/views/registration_wizard/teacher_reference_number.html.erb, config/locales/en.yml, spec/features/journeys/happy_paths/when_get_an_identity_returns_no_trn_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1092
Faisal highlighted that the flow isn't fully clear without this and Jackie and Diana agreed. 
This PR adds the TRN question back in after the GAI flow and before the qualified_teacher_check question.
=> [CPDNPQ-1092] Add teacher reference number question back in

app/models/user.rb, lib/omniauth/strategies/tra_openid_connect.rb, spec/support/shared_contexts/stub_gai_oauth.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1094
- The oauth scopes sent to GAI via the tra_openid_connect provider now sends preferred_name as a scope.
- full_name in the NPQ database is set to preferred name if present when saving data from the GAI oauth response If it is not present, full_name is stored instead.
=> CPDNPQ-1094 Implement Logic in API Accommodating GAI Name Changes

lib/omniauth/strategies/tra_openid_connect.rb
This scope has stopped being recognised, we need to remove that so that the app starts working again.
=> Stop sending preferred_name scope

.github/workflows/deploy_to_dev.yml, .github/workflows/deploy_to_production.yml, .github/workflows/deploy_to_review_app.yml, .github/workflows/deploy_to_sandbox.yml, .github/workflows/destroy_review_app.yml, .github/workflows/export_dashboard_report.yml, .github/workflows/generate_dashboard_report.yml, .github/workflows/get_an_identity_data_sync_all.yml, .github/workflows/get_an_identity_data_sync_unsynced.yml, .github/workflows/get_an_identity_data_sync_user.yml, .github/workflows/schedule_sweep_stale_sessions.yml, .github/workflows/update_all_schools.yml, .github/workflows/update_all_schools_test_run.yml, .github/workflows/update_course_definitions.yml, .github/workflows/update_schools.yml
Almost every job in the repo had the name "deploy". Most of them aren't deployments.
Updates all job ids to be appropriate to the job and gives them proper names.
=> Use proper job names in Github Actions

app/views/accounts/user_registrations/show.html.erb, app/views/registration_wizard/confirmation.html.erb, spec/features/journeys/happy_paths/when_choose_lead_mentor_course_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1095
The success banner depends on the URL param which is not ideal, but there is no straightforward way to do it via redirection at the moment.
=> Add redirect button to confirmation page

app/lib/services/ecf/ecf_application_synchronization.rb
update only synced applications with ecf
https://github.com/DFE-Digital/npq-registration/pull/819
We are not raising an exception, we will be updating any ID's that are present in the npq space.
```
For example, application A and B got updated in the ECF. But in the NPQ, we have only application A and application B has not synced yet.
It should update only application A since it is synced with Ecf.
```
=> CPDNPQ-1188: Update only synced application with ecf

.gitignore, .tool-versions, Makefile, global_config/domains.sh, global_config/production.sh, terraform/domains/environment_domains/.terraform.lock.hcl, terraform/domains/environment_domains/config/production.tfvars.json, terraform/domains/environment_domains/config/production_Terrafile, terraform/domains/environment_domains/main.tf, terraform/domains/environment_domains/terraform.tf, terraform/domains/environment_domains/variables.tf, terraform/domains/infrastructure/.terraform.lock.hcl, terraform/domains/infrastructure/config/zones.tfvars.json, terraform/domains/infrastructure/config/zones_Terrafile, terraform/domains/infrastructure/main.tf, terraform/domains/infrastructure/terraform.tf, terraform/domains/infrastructure/variables.tf
Ticket: https://trello.com/c/i1HAQLBe
Manage the services domain from within the services code and move it from AWS Route 53 to Azure DNS and Front Door.
Add relevant code to allow the manual deployment of the DNS infrastructure and configuration using `Makefile` commands.
On MacOS:
Follow - https://vninja.net/2020/02/06/macos-custom-dns-resolvers
cd /etc
sudo mkdir resolver
cd resolver
sudo touch register-national-professional-qualifications.education.gov.uk
sudo vi register-national-professional-qualifications.education.gov.uk
Add the following lines and save:
```
domain register-national-professional-qualifications.education.gov.uk
search register-national-professional-qualifications.education.gov.uk
nameserver 13.107.236.4
nameserver 150.171.21.4
nameserver 204.14.183.4
nameserver …
```
=> Add code to support DNS management

.github/actions/build-and-push-docker-image/action.yml, .github/workflows/deploy_to_dev.yml, .github/workflows/deploy_to_production.yml, .github/workflows/deploy_to_review_app.yml, .github/workflows/deploy_to_sandbox.yml
We'll soon be moving the NPQ app from GOV.UK PaaS to Azure and to stay in line with how other projects/teams are deploying, we'll be switching from Dockerhub to GitHub's container registry. This helps simplify deployment by reducing the number of credentials required.
- Create an action that pushes to DockerHub
- Push images to GitHub container registry too
- Call docker push action from deployment workflows
=> Move docker build and push to its own action

.github/actions/build-and-push-docker-image/action.yml
When the action is triggered by a non-pull-request event there's no sha at the head of the PR branch. Instead use github.sha which is the SHA that triggered the event.
=> Fallback to github.sha in Docker push action

.env.template, config/manifests/dev-manifest.yml, config/manifests/review-app-manifest.yml, config/manifests/staging-manifest.yml
We are moving off PaaS, point dev NPQ to staging ECF (the new dev)
Change all references of ecf-dev to new staging AKS environment
failures:
=> Point NPQ reg app to ECF AKS instead of PaaS

config/manifests/sandbox-manifest.yml
Ticket: n/a
We're turning off PaaS sandbox ECF instance, and migrating over to Azure which requires a different URL
Point ECF base URL for Sandbox to new Azure URL for sandbox
failures:
=> Update Sandbox ECF Base URL to new azure URL

app/models/lead_provider.rb, config/initializers/courses.rb, spec/lib/forms/choose_your_provider_spec.rb
Mapping provider with math npq course
https://dfedigital.atlassian.net/browse/CPDNPQ-1257
Created a mapping for successful lead_providers that we can show for our maths npq course.
List of lead providers to show:
- Ambition Institute
-  Church of England
- Education Development Trust
- LLSE
- Teach First
- UCL Institute of Education
=> Mapping provider with math npq course

app/helpers/identity_account_helper.rb, spec/helpers/identity_account_helper_spec.rb, spec/support/helpers/journey_helper.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1305
Following on the work for #867 I am updating the GAI link (Identity service) 
by url encoding the `redirect_uri` according to [the specs](https://github.com/DFE-Digital/get-an-identity/blob/main/docs/account-page.md#example-url) from the Get-an-identity
service team.
=> Update GAI link to match Get an Identity service standards

config/database.yml, config/environments/review.rb
When we move the NPQ reg application to Azure we'll be moving to the model used in ECF where we have a Rails environment per actual (deployed) environment, plus a `development` one for working locally.
I also cleaned up the database config by removing the unnecessary comments.
- Add the review env config
- Remove the noise from the database config
- Add review database config
=> Introduce the review environment

config/environments/production.rb
This has been set to :development for a long time but we're logging too much that way, we only care about the important things in production.
=> Set production log level to `:warn`

Gemfile
On Azure we'll be seeding review apps when generating them (rather than copying a template db like we did in PaaS) so we need `faker`.
=> Add group for dev, test and review for faker

Gemfile, Gemfile.lock
Updated required gem versions other then groups
https://dfedigital.atlassian.net/browse/CPDNPQ-1261
Update outdated gems to versions that are most compatible with the current version of Rails and Ruby.
=> Clean up gem files in code to ensure that correct versions are being used.

app/lib/services/feature.rb
Enabled maths_npq feature flag for all environments
https://dfedigital.atlassian.net/browse/CPDNPQ-1257
In feature.rb file removes sandbox condition for maths_npq flag. Now maths_npq needs to be live. So, enabled maths_npq feature_flag for all environments.
=> Enabled maths_npq feature flag for all environments

terraform/application/application.tf, terraform/application/config/production.tfvars.json, terraform/application/database.tf, terraform/application/variables.tf
Set up the number of nodes for the web and worker apps and set the PostgreSQL database size and high availability to true.
- Fix indentation
- Set the webapp and worker replicas
- Set postgres server sku and high availability
=> Configure AKS plans and memory

.github/actions/backup-paas-database/action.yml, .github/actions/restore-paas-database/action.yml, .github/workflows/copy-paas-database-to-azure.yml
Prior to the move from GOV.UK PaaS to Azure we need to ensure our environments work properly with 'real' data. This PR introduces actions that copy it, environment by environment.
These actions will be reusable across environments, starting with staging. It uses the same process we used in ECF.
=> Add actions for copying data from PaaS to Azure

.github/workflows/deploy.yml, .github/workflows/rspec.yml
This follows on from #925 and should be ignored until that's merged 😄
It adds a workflow that _just_ runs RSpec that we can call from the main Deploy flow.
=> Add RSpec workflow to new deployment

app/models/lead_provider.rb
National Institute of Teaching (NIoT) also won the bid to supply Maths NPQ; however, this bid was completed after all the other providers and it looks like NPQ Reg was not notified of NIoT winning the bid. Now added NIoT to Math_npq course provider list.
https://dfedigital.atlassian.net/browse/CPDNPQ-1397
Just mapped NIoT to math_npq lead_provider list.
=> Added NIoT to Math_npq course provider list

.github/workflows/deploy.yml
The 'needs' directive can only access the things directly needed by the current step, so must refer to deploy_staging instead of docker.
=> Make sandbox and prod use staging's docker image

.github/workflows/rspec.yml, .github/workflows/specs.yml, app/lib/services/feature.rb, app/views/accounts/user_registrations/show.html.erb, app/views/layouts/application.html.erb, app/views/registration_wizard/start.html.erb, global_config/review.sh, package.json
For the Azure migration, we would like to disable registrations and inform user.
To disable the registration, either switch the flag in console or web admin. To switch flag in console, simply use `Services::Feature.disable_registration!` and to enable it back `Services::Feature.enable_registration!`
=> Allow to disable registration in Flipper

.github/workflows/deploy.yml
The full workflow was used in testing but we want to restrict it before the migration.
=> Re-enable main checks before migration

terraform/domains/environment_domains/config/production.tfvars.json
Change Azure front door origin for migration from PaaS to AKS
Update production env domain configuration file, and point to AKS 
(this has already been manually applied to production during the migration)
=> Change fd origin for aks migration

Makefile
This can be used when the lockfile is left locked by a failed/aborted
deploy or other odd circumstances. It should be used very carefully
anywhere except on review apps
Get the LOCK_ID from the error output:
```
│ Error: Error acquiring the state lock
│
│ Error message: state blob is already locked
│ Lock Info:
│   ID:        60302718-88ca-73d7-7feb-7c7dbe35be11
│   Path:      terraform-state/963.tfstate
│   Operation: OperationTypeApply
│   Who:       runner@fv-az574-93
│   Version:   1.5.4
│   Created:   2023-10-25 06:59:29.495925764 +0000 UTC
│   Info:
```
=> Add a terraform-unlock step to the Makefile

app/jobs/application_job.rb, app/jobs/crons/sentry_checker_job.rb
I can't see any error collected in Sentry for our Jobs, so I am assuming that
this is because we are not rescuing and sending explicitly.
It also includes a Temporary Job to track the correct execution in all environments.
=> Capture Sentry errors in ActiveJob

app/jobs/crons/sentry_checker_job.rb
We are not using Raven by Sentry, hence we need to rename it.
=> Rename Raven to Sentry

app/lib/services/report.rb, spec/lib/services/report_spec.rb
We are debugging issues with Delayed::Job after the migration from PAAS to Azure. It seems that the jobs related to this report are not finishing in `delayed_jobs`. We are exploring if this could be related to a memory issue as we are loading all Application (with some includes) via Active Record.
This PR uses `find_each` which is a lighter approach.
=> Replace map with find_each for reporting

app/forms/questionnaires/base.rb, app/forms/questionnaires/flow_helper.rb, app/services/registration_wizard_visualiser.rb
Fixed registration_wizard:visualise[png] rake task and moved FlowHelper to refactored forms folder.
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1338
Fixed registration_wizard:visualise[png] rake task
=> Fixed registration_wizard:visualise[png] rake task

app/models/user.rb, db/migrate/20231109124740_remove_uniquenes_from_users_email.rb, db/schema.rb, spec/features/happy_journeys/non_js/able_to_receive_targeted_delivery_funding_spec.rb, spec/lib/services/get_an_identity_service/webhooks/user_updated_processor_spec.rb, spec/models/user_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1470
There are several instances where users can not log in because email validation failed. As now we are relaying on GAI for authentication, we decided to use only GAI `uid` as unique identifier for user.
=> Disable email uniquenes checks for Users

app/jobs/crons/generate_dashboard_report_job.rb, app/jobs/crons/sweep_stale_sessions_job.rb, app/jobs/crons/update_applications_statuses_job.rb, app/jobs/crons/update_schools_job.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1466
This pull request introduces four new monitors to make sure that the jobs are executed as intended:
1. `Crons::UpdateApplicationsStatusesJob`: Updates application statuses every two hours.
2. `Crons::UpdateSchoolsJob`: Performs daily updates of school data at 4:30 AM.
3. `Crons::SweepStaleSessionsJob`: Clears stale user sessions daily at 3:30 AM
4. `Crons::GenerateDashboardReportJob`: Generates hourly dashboard reports .
By incorporating Sentry monitoring into these cron jobs, we can proactively identify and address any potential errors or exceptions, ensuring the reliability and stability of these critical tasks.
Thanks @slawosz for suggesting it.
=> Add sentry monitor for cron Jobs

app/forms/questionnaires/base.rb, app/forms/questionnaires/change_your_course_or_provider.rb, app/models/registration_wizard.rb, app/views/accounts/_course_details.html.erb, app/views/accounts/user_registrations/show.html.erb, app/views/registration_wizard/change_your_course_or_provider.html.erb, config/locales/en.yml
content changes to account screen so users can change course or provider
https://dfedigital.atlassian.net/browse/CPDNPQ-1473
Enable users to change their course or provider via the account screen by telling them that they need to submit a new registration.
Clicking the link to change course or provider should take you to a new interstitial page.
=> Modifications regarding course provider on the account screen 

app/services/feature.rb, app/views/accounts/_funding_details.html.erb, app/views/registration_wizard/ineligible_for_funding/already_funded/_not_eligible_scholarship_funding.html.erb, app/views/registration_wizard/possible_funding/_eligible_for_scholarship_funding.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1378
Remove targeted support funding.
Put targeted support funding under a feature flag :targeted_support_funding which is disabled by default.
failures:
=> Added feature flag for targeted support funding

.github/actions/backup-and-restore-snapshot-database/action.yml, .github/workflows/restore_snapshot_database.yml, .gitignore, Makefile, terraform/application/config/production.tfvars.json, terraform/application/database.tf, terraform/application/variables.tf
As part of the work to pull NPQ out of the ECF application we want to perform a number of data integrity checks. In order to do this we ideally need safe access to production data.
- Add snapshot database backup/restore actions
Add a GitHub action and associated workflow to generate a snapshot of the production database, that we can then use `konduit` to access.
Add a make command to create the `konduit` and update the development database config with the resulting connection string.
Successful snapshot creation is [here](https://github.com/DFE-Digital/npq-registration/actions/runs/7048219760/job/19183879927)
failures: …
=> Add snapshot database backup/restore actions

config/database.yml, config/environments/migration.rb, config/webpacker.yml
This environment will sit alongside production and sandbox and will be used to test the import process for ECF data.
=> Add `migration` environment to Rails

.tool-versions, app/models/user.rb
As we moved to GAI, we don't need email validation anymore. With each login, we receive the most recent user email and we update the database accordingly. With validation, we are having a clash when the GAI email is changed and we can not update the GAI user due to having a non-GAI account with the current GAI email. This change will cause duplicated identities on the ECF side, but it does not happen often and we can easily track those.
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1570
=> Disable validation of user email

app/controllers/omniauth_controller.rb, app/jobs/ecf_user_updater_job.rb
As we are not validating emails in the NPQ (we rely on GAI), we are allowing to have 2 users with the same emails. This causes problems with ECF synchronization. This is an intermediate fix, as we need to solve the actual issue.
=> Synchronize users in separate job

.github/workflows/deploy.yml, Makefile, global_config/migration.sh, terraform/application/config/migration.tfvars.json, terraform/application/config/migration_Terrafile
**This follows on from #1046**
This PR adds a new migration environment in Azure that sits alongside the sandbox. It's intended to be used to test the data migration of NPQ data from ECF to NPQ and will work alongside the corresponding environment there, see DFE-Digital/early-careers-framework/pull/4376.
The NPQ environment will connect to the ECF database and pull data directly.
we can do this by adding this `command` attribute to the tfvars:
```json
"command": ["RAILS_ENV=migration", "bundle", "exec", "rails", "db:schema:load", "&&", "RAILS_ENV=migration", "bundle", "exec", "db:seed", "&&", "RAILS_ENV=migration", "bundle", "exec", "rails", "server"]
````
=> Setup migration environment in Azure

app/controllers/admin/applications_controller.rb, app/models/application.rb, app/services/feature.rb, app/views/accounts/_course_details.html.erb, config/routes.rb, db/seeds.rb, spec/controllers/admin/applications_controller_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1343
In user accounts screen we can only ever see the “Apply with provider” status due to having no LP to accept the registrations.
This pr helps add a button that mimics the behaviour according to lead provider output. 
Note: This feature is only available for the review apps and is hidden behind a feature flag. In order to avail this functionality, a user needs to be a super admin and enable the feature flag first and then create an application and on the accounts screen where the application is displayed, the statuses and the course outcomes can be changed i.e (accept/reject a registration & passed/failed)
=> CPDNPQ-1343 mimic external Inputs & improve testing in review apps

.rspec
Turn off rspec profiling by default, it adds too much noise.
=> Disable rspec profiling by default

.github/actions/refresh-migration-database/action.yml, .github/workflows/refresh_migration_database.yml, Makefile
We have amigration environment that we will be using for the ECF -> NPQ migration testing. Prior to running this in production we want to test it in a production-like environment.
- Add task to refresh migration DB from production
Add a GitHub action to allow us to populate the migration database from the production database. Update `Makefile` to include command to connect to the migration DB.
I've ran the GitHub action manually as part of this PR so the migration DB is populated. You can connect to it with the new make commands:
```
make migration konduit
```
You can also connect to the snapshot DB:
```
CONFIRM_PRODUCTION=yes make production konduit-snapshot
```
=> Add task to refresh migration DB from production

app/views/accounts/_course_details.html.erb, config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1580
We want to make users aware that registrations will expire if not used in the next course start, in Feb. We are sending emails to tell them about expiring, which could then nudge them to sign in to their NPQ account, so we want their account to have a consistent message. 
For all registrations with the ‘provider application’ status of ‘pending' (which displays as ‘apply with provider’)
On the registration details page there is a new ‘Course start’ row. 
If the user is eligible for scholarship funding, the text for this row is:
February 2024
If you do not to join the February course, your registration will expire. You can register again later, but your funding may change.
If the user is not eligible (or it is in review) for …
=> CPDNPQ-1580 Add Course Start Row to Registration Details

spec/features/happy_journeys/js/when_working_at_an_eligible_primary_school_spec.rb, spec/features/happy_journeys/js/while_not_currently_working_at_school_spec.rb, spec/features/happy_journeys/js/while_working_at_private_childcare_provider_but_not_a_nursery_spec.rb, spec/features/happy_journeys/js/while_working_at_private_nursery_spec.rb, spec/features/happy_journeys/js/while_working_at_public_nursery_spec.rb, spec/features/happy_journeys/js/while_working_in_neither_a_school_nor_childcare_spec.rb, spec/features/happy_journeys/non_js/able_to_receive_targeted_delivery_funding_spec.rb, spec/features/happy_journeys/non_js/funded_ehco_registration_journey_spec.rb, spec/features/happy_journeys/non_js/international_teacher_npqh_journey_spec.rb, spec/features/happy_journeys/non_js/other_funded_ehco_registration_journey_spec.rb, spec/features/happy_journeys/non_js/previously_received_targeted_delivery_funding_spec.rb, spec/features/happy_journeys/non_js/via_using_old_name_and_not_headship_spec.rb, spec/features/happy_journeys/non_js/via_using_same_name_spec.rb, spec/features/journeys/happy_paths/basic_registration_journey_spec.rb, spec/features/journeys/happy_paths/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb, spec/features/journeys/happy_paths/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb, spec/features/journeys/happy_paths/changing_from_outside_of_catchment_area_to_inside_spec.rb, spec/features/journeys/happy_paths/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb, spec/features/journeys/happy_paths/via_using_old_name_and_not_headship_spec.rb, spec/features/journeys/happy_paths/when_choose_lead_mentor_course_spec.rb, spec/features/journeys/happy_paths/when_choose_maths_course_spec.rb, spec/features/journeys/happy_paths/when_get_an_identity_returns_no_trn_spec.rb, spec/features/journeys/happy_paths/when_outside_of_catchment_area_crown_dependencies_spec.rb, spec/features/journeys/happy_paths/when_outside_of_catchment_area_spec.rb, spec/features/journeys/happy_paths/when_previously_funded_spec.rb, spec/features/sad_journeys/applying_for_ehco_but_not_new_headteacher_spec.rb, spec/features/sad_journeys/lead_mentor_journey_with_incorrect_course_spec.rb, spec/features/sad_journeys/not_chosen_dqt_or_provider_spec.rb, spec/features/sad_journeys/school_not_in_england_spec.rb, spec/features/sad_journeys/works_in_childcare_but_not_in_england_spec.rb
The feature specs are failing because we've replaced `cohort_id` with `schedule_id`. I've disabled the legacy feature specs for now and updated the new (js/no_js) ones accordingly. We should put in some time to move the other legacy ones over and remove duplications where needed.
- Disable the old happy/sad journey specs
- Replace cohort_id with schedule_id in journey specs
=> Sort out feature specs

.github/actions/backup-and-upload-database/action.yml, .github/workflows/backup_production_database.yml
The process is copied from ECF's. It uses pg_dump and then uploads the resulting file to a storage account. Unlike ECF's which runs at 03:00 this runs at 03:30.
=> Add a nightly production backup that runs at 03:30

app/models/participant_id_change.rb, app/models/user.rb, db/migrate/20240115204129_create_participant_id_changes.rb, db/schema.rb, spec/models/participant_id_change_spec.rb
This will capture any user records being merged, to preserve the participant id journey in the API for a participant.
Add new participant ID changes model, similar to ECF
failures:
=> Add participant id changes model

app/models/application.rb, app/views/accounts/_active_application_table.html.erb, app/views/accounts/_course_details.html.erb, app/views/accounts/_expired_application_table.html.erb, app/views/accounts/show.html.erb, config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1579
When a registration status is changed to ‘Expired’ the tag next to ‘provider application’ displays as ‘Expired’. And has a grey background.
If the service is closed, this text displays below the tag:
Your registration has expired but you can register again for future courses when registrations open.
If the service is open, this text displays below the tag: 
Submit a new registration if you still want to take this course. 
‘Submit a new registration’ text links to the registration flow (the same as the ‘Register for another NPQ’ button at the bottom of the account page). 
All the expired registrations are grouped together on the account page. 
Above the expired registrations is a h3, large size heading ‘Expired registrations’ …
=> CPDNPQ-1579 Show Expired Info on Registrations in Account

db/migrate/20240115034236_create_enum_for_outcome_state.rb, db/migrate/20240115034348_change_outcome_state_column_type.rb, db/schema.rb
We are decided to use PostgreSQL native enum types to store the different 
types (statuses) of a number of entities within NPQ.
In this PR I am updating Outcomes so it validates at the DB level:
```ruby
STATES = %w[passed failed voided].freeze
validates :state, inclusion: { in: STATES }
```
=> Update state type with PostgreSQL native enum type: Outcomes

terraform/application/variables.tf
This should make any alerts that fire go to all the people assigned to the CPD group (`291418`) on StatusCake
=> Set the default `statuscake_contact_groups` to CPD

db/migrate/20240115032403_create_declaration_status_enum.rb, db/migrate/20240115032446_change_declaration_and_statement_item_columns.rb, db/migrate/20240123085818_rename_declaration_status_enum.rb, db/schema.rb, spec/factories/declarations.rb
We are decided to use PostgreSQL native enum types to store the different types (statuses) of a number of entities within NPQ.
In this PR I am updating Outcomes so it validates at the DB level:
```ruby
STATES = %w[submitted eligible ineligible payable voided paid awaiting_clawback clawed_back].freeze
validates :state, inclusion: { in: STATES }
```
=> Update state type with PostgreSQL native enum type

.github/workflows/deploy.yml
This isn't needed as we always build review apps now instead of just building them when the `review-app` label is present. The defaults are synchronize, reopened, opened so we don't need to specify anything here.
=> Removed 'labeled' trigger from PR deploy run

.github/workflows/deploy.yml
This is required so the build occurs when PRs are queued up.
=> Add merge-group to deploy flow

db/seeds.rb
I introduced this yesterday under the assumption envs were a list of labels rather than strings 🙈
=> Fix seeding bug where we check multiple envs

app/helpers/funding_helper.rb, app/views/accounts/_funding_details.html.erb, config/initializers/constants.rb, config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1678
- Use the existing TSF feature flag 
- On the registration details pages, if the person is marked as eligible for TSF a row should display under the Scholarship funding row. 
- When TSF is shown, an ‘eligible’ green tag should display and below the tag the content: 
- Your workplace will receive a targeted support funding payment to support you to do this NPQ.
- If they are not eligible for TSF or the registration is submitted post-April 2024 no info about TSF should display.
=> CPDNPQ-1678 Retain TSF Info on Registration Details for Past Registrations

app/models/migration/data_migration.rb, app/services/migration/migrator.rb, db/migrate/20240228140211_create_data_migration.rb, db/migrate/20240301152723_add_total_count_to_data_migrations.rb, db/schema.rb, spec/lib/services/migration/migrator_spec.rb, spec/models/migration/data_migration_spec.rb
[Jira-2853](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2853)
We want to introduce the skeleton migration service that we can build on going forward. Initially, we want to simulate a migration so that we can more easily create a UI off the resulting `DataMigration` models.
- Add skeleton Migrator service with dummy migration run
Add the skeleton `Migrator` service, ensuring it can only run on environments where the data migration feature is enabled.
Run a dummy migration for `LeadProvider`, `Cohort` and `Statement`. The dummy migration will simulate processing up to 1,000 records per model and each will take less than a minute to complete. Failures are added at random (with a 1 in 50 change of occurring).
- Add DataMigration model
We …
=> Add skeleton Migrator service with dummy migration run

app/views/shared/cookies/_accepted.html.erb, app/views/shared/cookies/_not_set.html.erb, app/views/shared/cookies/_rejected.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1703
Font in the description text of the cookies banner is not displaying in the GDS style font.
Post fix:
=> CPDNPQ-1703 Update Cookies Banner to GDS Font

.tool-versions, app/controllers/npq_separation/migration/migrations_controller.rb, app/helpers/migration_helper.rb, app/jobs/migration_job.rb, app/models/migration/data_migration.rb, app/services/migration/migrator.rb, app/views/npq_separation/migration/migrations/_completed_migration.html.erb, app/views/npq_separation/migration/migrations/_in_progress_migration.html.erb, app/views/npq_separation/migration/migrations/index.html.erb, app/views/session_wizard/sign_in.html.erb, config/routes.rb, spec/controllers/npq_separation/migration/migrations_controller_spec.rb, spec/factories/migration/data_migrations.rb, spec/features/admin_spec.rb, spec/features/journeys/happy_paths/able_to_receive_targeted_delivery_funding_spec.rb, spec/features/journeys/happy_paths/funded_ehco_registration_journey_spec.rb, spec/features/journeys/happy_paths/international_teacher_npqh_journey_spec.rb, spec/features/journeys/happy_paths/other_funded_ehco_registration_journey_spec.rb, spec/features/journeys/happy_paths/previously_received_targeted_delivery_funding_spec.rb, spec/features/journeys/happy_paths/via_using_same_name_spec.rb, spec/features/migration_spec.rb, spec/helpers/migration_helper_spec.rb, spec/jobs/migration_job_spec.rb, spec/lib/services/migration/migrator_spec.rb, spec/models/migration/data_migration_spec.rb, spec/models/migration/ecf/base_record_spec.rb, spec/rails_helper.rb, spec/support/helpers/npq_separation_admin_login.rb
[Jira-2854](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2854)
We want to a simple user interface available to super administrators where we can kick off a new migration, keep track of the progress and view the outcome.
- Add convenience methods to DataMigration
In order to render the state more easily in the UI we want to add some convenience methods to the `DataMigration` model for determining the state of the migration and the outcome.
- Add MigrationJob
Add job for kicking off a migration. Split out the preparation logic on the `Migrator` service so that we can create the `DataMigration` instances in-band and therefore render the state more easily in the UI (if we did this in the job itself it may not happen before the page …
=> Add UI for ECF migration

terraform/application/config/production.tfvars.json
Ticket: https://trello.com/c/9WQqXVn8/1647-review-all-ssl-monitors
Add missing statuscake monitoring to terraform
(then remove manually added ones)
Add external_url for prod, so we get uptime and ssl checks for the education.gov.uk domain
make production terraform-plan CONFIRM_PRODUCTION=yes
=> Add statuscake checks for external_url

app/forms/questionnaires/qualified_teacher_check.rb, config/locales/en.yml, spec/lib/questionnaires/qualified_teacher_check_spec.rb
Unvalidate trn user should not be bypass
https://dfedigital.atlassian.net.mcas.ms/browse/CPDNPQ-1697
This PR includes essential updates to the `qualification_teacher_check` questionnaire, specifically focusing on the `processed_trn` validations. The modifications encompass both the questionnaire itself and the associated spec file to ensure accurate and reliable validation processes.
**Note**
It's important to note that, due to certain constraints, we are refraining from updating model-level validations in this iteration. The reason behind this decision is that implementing model-level validations at this stage could lead to failures in cases where user information is being updated for individuals with unverified TRNs, such as "/", are present in the previously stored data within the …
=> CPDNPQ-1697 Add form-level validation for trns to only be numerical

.github/workflows/deploy.yml
Queues make dealing with a large number of PRs easier. It's most apparent on the first of the month when Dependabot opens lots of small version bumps.
In order to enable them we need to:
=> Prepare the project for GitHub work queues

Makefile, app/models/migration/data_migration.rb, app/services/migration/migrator.rb, app/views/npq_separation/migration/migrations/_completed_migration.html.erb, app/views/npq_separation/migration/migrations/_in_progress_migration.html.erb, spec/features/migration_spec.rb, spec/lib/services/migration/migrator_spec.rb, spec/models/migration/data_migration_spec.rb
[Jira-2856](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2856)
As part of the NPQ separation work we want to migrate all `NPQLeadProvider` records from ECF into NPQ reg. In an ideal world the records should already exist in NPQ reg, so this will consist of making integrity checks and recording a failure if a lead provider exists in ECF but not in NPQ reg.
- Migrate lead providers from ECF to NPQ reg
- Fix adding konduit URL to database config
When we moved to multiple databases (to connect to ECF) we should have updated the indentation on this make command.
| Migration running    | Migration complete 
| <img width="1372" alt="Screenshot 2024-03-06 at 11 08 26" …
=> Migrate lead providers from ECF to NPQ registration

app/controllers/api/base_controller.rb, app/services/api/errors/response.rb, config/locales/en.yml, spec/requests/api/v3/statements_spec.rb, spec/services/api/errors/response_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2866
* Added error handling for `BaseController`
* Created `API::Errors::Response` service class to render errors as JSON
=> [CPDLP-2866] TS1 - Statements endpoint - API base and error handling

config/routes.rb
I originally left "admin" outside of the admin_portal_enabled constraint so the route didn't end up being `admin_admin`.
Instead we can switch to [the block syntax](https://guides.rubyonrails.org/routing.html#constraints-in-a-block-form) and put it inside without affecting routes.
Much easier to review with whitespace disabled.
=> Switch from constraints keyword arg to block

app/models/statement.rb, app/services/migration/migrator.rb, config/environments/development.rb, spec/features/migration_spec.rb, spec/lib/services/migration/migrator_spec.rb, spec/models/statement_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2855
We want to migrate cohorts and statements from ECF into NPQ reg. These models are grouped together as they don’t currently exist in NPQ reg (so its all new data coming across/nothing to clash into).
Add logic to migrate cohorts and statements.
=> [CPDLP-2855] Add logic to migrate cohorts and statements

.github/workflows/rspec.yml, .rspec_parallel, Gemfile, Gemfile.lock
The test suite is now fast enough (since #707, #1115) to run sequentially. This simplifies our setup, makes the test output clearer and removes a dependency.
The entire run is 1 minute slower, from 6 mins to 7 mins.
We could make the whole thing *a lot faster* by testing the JavaScript pages on their own rather than as part of the end-to-end runs.
=> Remove `parallel_tests` gem and all config

spec/factories/lead_providers.rb
We've had some flakey tests example https://github.com/DFE-Digital/npq-registration/actions/runs/8255008175/job/22581317202 due to the provider factory finding existing providers or creating them which might set lead providers in specs to the same one causing failures
Revert factory to use faker again
failures:
=> Set lead provider factory to use faker

config/database.yml, spec/spec_helper.rb
Remove `TEST_ENV_NUMBER` from database setup as parallel gem was removed in the following pr https://github.com/DFE-Digital/npq-registration/pull/1216
failures:
=> Cleanup parallel test setup

.github/CODEOWNERS
This will make managing who gets notifications easier in the long term as it can be done via GitHub's interface rather than via commits.
=> Change CODEOWNERS to use CPD NPQ team

Makefile
Ticket: n/a
A change to how we authenticate with AKS has been implemented, and konduit script has now been updated.
Since we have make commands that use this script, we have to now pass in a namespace option to konduit
Pass in namespace option to both konduit commands to connect to dbs
failures:
=> Add namespace to konduit commands

app/models/statement.rb, app/serializers/api/v3/statement_serializer.rb, app/services/migration/migrator.rb, db/ecf_schema.rb, db/migrate/20240312212008_add_ecf_id_to_statements.rb, db/schema.rb, spec/factories/statements.rb, spec/models/statement_spec.rb, spec/requests/api/v3/statements_spec.rb, spec/serializers/api/v3/statement_serializer_spec.rb
Ticket: [CPDLP-2879](https://dfedigital.atlassian.net/browse/CPDLP-2879)
We need to maintain all existing ecf ids in the API. This also applies to statements.
- Add `ecf_id` to the statements table
- Migrate the `ecf_id` when copying over statement data
- Surface `ecf_id` and the id of the statement in the API
- Add to seeds as well as a generated UUID
[CPDLP-2879]: https://dfedigital.atlassian.net/browse/CPDLP-2879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2879] Add missing `ecf_id` to statements

app/components/npq_separation/navigation_structures/admin_navigation_structure.rb, spec/components/npq_separation/navigation_structures/admin_navigation_structure_spec.rb
Ticket: n/a
We have a build interface for the lead provider npq separation admin. Add link back to structure
failures:
=> Add lead provider admin path

app/components/npq_separation/navigation_structures/admin_navigation_structure.rb, app/controllers/npq_separation/admin/users_controller.rb, app/services/users/find.rb, app/views/npq_separation/admin/users/index.html.erb, app/views/npq_separation/admin/users/show.html.erb, config/routes.rb, spec/components/npq_separation/navigation_structures/admin_navigation_structure_spec.rb, spec/features/npq_separation/admin/users_spec.rb, spec/rails_helper.rb, spec/requests/npq_separation/admin/users_controller_spec.rb, spec/services/users/find_spec.rb
We want to be able to view the basic user information in the NPQ separation admin area.
- Add users section to NPQ separation admin area
Add index/show actions for users. List all users with pagination and display details when clicking through.
[Link to users in admin dashboard](https://npq-registration-review-1240-web.test.teacherservices.cloud/npq-separation/admin/users)
| All Participants    | Participant |
| <img width="1388" alt="Screenshot 2024-03-21 at 08 07 05" src="https://github.com/DFE-Digital/npq-registration/assets/29867726/b48f2c0d-7107-4cfa-94fe-5af1697befb0">  | <img width="1432" alt="Screenshot 2024-03-21 at 08 07 12" src="https://github.com/DFE-Digital/npq-registration/assets/29867726/f6079999-dfdb-4749-a630-f96039ed1d2f">   |
=> Add users section to NPQ separation admin area

.github/workflows/deploy.yml
We need a simpler way of deploying a specific branch/PR to a specific environment.
Add workflow params to `deploy` Github action like we have in ECF app.
=> Add workflow params to deploy github actions

.github/workflows/deploy.yml, .rubocop.yml, Makefile, config/database.yml, config/environments/separation.rb, config/webpacker.yml, db/migrate/20221130142333_add_hint_to_lead_providers.rb, db/seeds.rb, docs/environments.md, global_config/separation.sh, terraform/application/config/separation.tfvars.json, terraform/application/config/separation_Terrafile
[Jira-2939](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2939)
We want to add an additional environment for providers to be able to test against the new endpoints added as part of the NPQ separation work.
- Add new Rails env for separation
Add a new Rails environment for the separation work and enable separation features (apart from migration as there is no corresponding ECF environment to reference yet). Clean up the `webpacker.yml` file.
- Add terraform for separation environment
Adds terraform configuration for separation environment in the production space.
- Deploy to separation environment on merge to main
We want to deploy to the separation environment when merging to `main`, alongside the `sandbox` and `migration` …
=> Add separation environmnent

app/models/application.rb, db/migrate/20240412131057_create_headteacher_statuses_enum.rb, db/migrate/20240412131141_change_applications_headteacher_status_to_enum.rb, db/migrate/20240415103921_create_funding_choices_enum.rb, db/migrate/20240415104228_change_applications_funding_choice_to_enum.rb, db/migrate/20240415104435_create_lead_provider_approval_statuses_enum.rb, db/migrate/20240415104534_change_applications_lead_provider_approval_status_to_enum.rb, db/schema.rb, spec/models/application_spec.rb
After the investigation in https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2932, we've found that a number of fields are enums in ECF but not in NPQ.
We need to change those fields to enums in NPQ.
Change the following fields to enums in NPQ applications table:
- headteacher_status
- funding_choice
- lead_provider_approval_status
Note: I'm using migrations `up/down` instead of `change` method so migrations can be reversible.
=> [CPDLP-2992] Amend application fields to enums

app/models/admin.rb, app/models/statement.rb, app/models/user.rb, spec/models/admin_spec.rb, spec/models/statement_spec.rb, spec/models/user_spec.rb, spec/services/migration/migrators/statement_spec.rb
This change adds validation messages that will make sense in the user interface (when we build it). Setting the trend early should encourage developers to continue adding them as we implement more validation rules. This prevents Rails' default error messages from unintentionally appearing in the UI, and they don't work with the GOV.UK error summary because they don't include the field name and aren't very helpful to users.
- **Add validation messages for Statement month**
- **Add validation messages for Statement year**
- **Add validation messages for Statement ecf_id**
- **Add validation messages for Statement output_fee**
- **Make statement items validation message friendlier**
- **Add validation message for User full_name**
- **Add validation message for User email**
- **Add validation …
=> Add human readable messages for validations

app/helpers/admin_management_helper.rb, app/helpers/application_helper.rb, app/helpers/webhook_messages_helper.rb, spec/helpers/application_helper_spec.rb, spec/views/admin/applications/show.html.erb_spec.rb
We have a couple of spots where we're manually doing things which are already covered by govuk-components.
- **Capitalise 'Yes' and 'No' and use govuk_tag helper**
- **Replace other manual tag building with component**
=> Refactor tag helpers

db/migrate/20240422135109_change_flipper_gates_value_to_text.rb, db/schema.rb, db/seeds.rb, db/seeds/base/add_feature_flags.rb
Flipper wasn't working in review apps because we weren't initializing the config when seeding the database.
In order to initialize properly we had to switch Flipper's `value` column from `varchar` to `text`, [see here](https://github.com/flippercloud/flipper/pull/790).
- **Change flipper value column from varchar to text**
- **Initialize feature flags during seeding**
=> Get Flipper working in review apps

app/forms/email_updates.rb, app/forms/questionnaires/choose_your_npq.rb, app/forms/questionnaires/course_start_date.rb, app/forms/questionnaires/maths_eligibility_teaching_for_mastery.rb, app/forms/questionnaires/npqh_status.rb, app/forms/questionnaires/teacher_reference_number.rb, app/views/accounts/_active_application_table.html.erb, app/views/accounts/_course_details.html.erb, app/views/accounts/_expired_application_table.html.erb, app/views/accounts/_funding_details.html.erb, app/views/admin/closed_registration_users/index.html.erb, app/views/registration_wizard/shared/questions/_radio_button_group.html.erb, spec/features/journeys/happy_paths/funded_ehco_registration_journey_spec.rb, spec/features/journeys/happy_paths/other_funded_ehco_registration_journey_spec.rb, spec/features/journeys/sad_paths/applying_for_ehco_but_not_new_headteacher_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1752
- Tags should be sentence case.
- Questions should be h2.
- Questions should have medium text if there is an XL title above them.
Question text configuration was already set but was being overridden in `_radio_button_group.html.erb` because of the ordering of arguments. They also needed changing from h1 to h2.
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> [CPDNPQ-1752] Styling fixes after frontend update

app/components/npq_separation/navigation_structures/admin_navigation_structure.rb, app/controllers/npq_separation/admin/courses_controller.rb, app/controllers/npq_separation/admin/schools_controller.rb, app/helpers/admin_helper.rb, app/services/courses/query.rb, app/services/schools/query.rb, app/views/npq_separation/admin/courses/index.html.erb, app/views/npq_separation/admin/courses/show.html.erb, app/views/npq_separation/admin/schools/index.html.erb, app/views/npq_separation/admin/schools/show.html.erb, config/routes.rb, spec/components/npq_separation/navigation_structures/admin_navigation_structure_spec.rb, spec/factories/schools.rb, spec/helpers/admin_helper_spec.rb, spec/requests/npq_separation/admin/courses_controller_spec.rb, spec/requests/npq_separation/admin/schools_controller_spec.rb, spec/services/courses/query_spec.rb, spec/services/schools/query_spec.rb
[Jira-2968](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2968)
We want to add a list of schools and courses to the new admin dashboard in NPQ reg, along with detail pages that contain the details of a course/school.
- Add schools to the admin dashboard
Add a page to list schools and show details of a school in the admin dashboard.
- Add courses to the admin dashboard
Add a page to list courses and show details of a course in the admin dashboard.
For some reason the Faker town/county translations are missing and it complains, so I've hardecoded these values in the factory for now.
| All courses    | Course | All schools | School |
| -------- | ------- | -------- | ------- |
| ![all-courses](https://github.com/DFE-Digital/npq-registratio …
=> Add schools/courses to admin dashboard

app/controllers/api/v3/statements_controller.rb, config/routes.rb
There's a source of potential confusion where we're dealing with ecf_id and referring to it as id. I think it's clearer if we override param so it's clear exactly what we're referring to.
=> Set param to ecf_id for new API routes

app/controllers/api/concerns/filter_by_updated_since.rb, app/controllers/api/v1/applications_controller.rb, app/controllers/api/v2/applications_controller.rb, app/controllers/api/v3/applications_controller.rb, app/controllers/api/v3/statements_controller.rb, app/services/api/concerns/orderable.rb, app/services/applications/query.rb, spec/factories/users.rb, spec/features/admin_spec.rb, spec/features/npq_separation/admin/users_spec.rb, spec/jobs/application_submission_job_spec.rb, spec/lib/services/handle_submission_for_store_spec.rb, spec/requests/api/v1/applications_spec.rb, spec/requests/api/v2/applications_spec.rb, spec/requests/api/v3/applications_spec.rb, spec/requests/api/v3/statements_spec.rb, spec/services/api/concerns/orderable_spec.rb, spec/services/applications/query_spec.rb, spec/support/shared_examples/api_index_endpoint_support.rb, spec/support/shared_examples/api_show_endpoint_support.rb
Follow on PR from #1305 to add the implementation for the GET `/applications` endpoint across all API versions.
- Add filtering to Applications::Query
We need to support filtering by cohort and updated since for the GET `/applications` endpoint.
- Add applications endpoint
Update the `Applications::Query` to support filtering. 
Add GET `/applications` actions to each version of the `ApplicationsController`. 
Extract index tests into shared examples to DRY up. 
Update users factory to set `ecf_id` by default as this is the default state.
=> Add applications endpoint

spec/features/course_start_date_spec.rb
Ticket: N/A
`spec/features/course_start_date_spec.rb:33` is failing due the `course_start_date` being set to 1st of May 24.
`course_start_date` is now dynamically set to `Date.tomorrow`.
=> Fix `spec/features/course_start_date_spec.rb:33` flakey test

app/views/npq_separation/admin/lead_providers/show.html.erb, spec/features/npq_separation/admin/lead_providers_spec.rb
[Jira-3005](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3005)
This was previously a placeholder but we can now populate it to take the user to all statements.
=> Fix link to view all statements

config/environments/test.rb, config/locales/en.yml
Some translations are missing and we're unaware. Hopefully running through the entire test suite with `config.i18n.raise_on_missing_translations` enabled should highlight a few.
=> Fix missing translations

app/controllers/api/v3/applications_controller.rb, app/services/applications/query.rb, app/services/courses/query.rb, app/services/schools/query.rb, spec/services/applications/query_spec.rb
This allows us to query for values that are null as well as skipping adding the condition entirely.
Updated query objects:
* applications
* schools
* courses
=> Switch remaining query objects to format with :ignore

app/views/npq_separation/admin/applications/index.html.erb, app/views/npq_separation/admin/applications/show.html.erb, app/views/npq_separation/admin/courses/show.html.erb, spec/features/npq_separation/admin/applications_spec.rb, spec/features/npq_separation/admin/courses_spec.rb, spec/features/npq_separation/admin/finance/statements_spec.rb, spec/features/npq_separation/admin/lead_providers_spec.rb, spec/features/npq_separation/admin/schools_spec.rb, spec/features/npq_separation/admin/users_spec.rb, spec/models/application_spec.rb, spec/support/matchers/summary_list_matcher.rb
[Jira-3043](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3043)
Our feature specs for the admin dashboard have mixed coverage (some have full tests, others partial, others none); we want to make them all consistently tested.
- Add missing test coverage for admin dashboard
Make the feature specs consistent across the admin dashboard. 
We may want to rethink this a bit in the future and move some of the views into view components that are tested instead, but this at least makes it all consistent for now.
=> Add missing test coverage for admin dashboard

app/serializers/api/statement_serializer.rb, spec/serializers/api/statement_serializer_spec.rb
[Jira-3007](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3007)
We should be returning `true` here if the `state` is `paid`, otherwise `false`.
=> Fix StatementSerializer paid attribute

public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/swagger_schemas/models/application.rb
Failure on main after adding Senco course
Add new Senco course to swagger docs
failures:
=> Add Senco to API docs

app/models/application.rb, app/models/course.rb, app/services/applications/query.rb, public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/factories/applications.rb, spec/factories/courses.rb, spec/factories/migration/ecf/finance/schedules.rb, spec/factories/migration/ecf/npq_courses.rb, spec/lib/questionnaires/check_answers_spec.rb, spec/lib/questionnaires/choose_school_spec.rb, spec/lib/questionnaires/possible_funding_spec.rb, spec/lib/services/ecf/npq_profile_creator_spec.rb, spec/lib/services/ecf/npq_profile_updater_spec.rb, spec/lib/services/eligibility/targeted_delivery_funding_spec.rb, spec/lib/services/funding_eligibility_spec.rb, spec/models/application_spec.rb, spec/models/course_spec.rb, spec/models/lead_provider_spec.rb, spec/models/registration_wizard_spec.rb, spec/rails_helper.rb, spec/requests/npq_separation/admin/courses_controller_spec.rb, spec/serializers/api/application_serializer_spec.rb, spec/services/applications/query_spec.rb, spec/services/courses/query_spec.rb, spec/services/migration/migrators/course_spec.rb, spec/support/database_seeds.rb, spec/swagger_schemas/models/application.rb
Ticket: [CPDLP-3015](https://dfedigital.atlassian.net/browse/CPDLP-3015)
In the current ECF implementation of `ineligible_for_funding_reason` to surface the value `previously_funded?` we had to optimise in the API applications endpoint [here in ECF](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/services/api/v3/npq_applications_query.rb#L34).
Fix `previously_funded?` N+1 query then improving the application endpoint performance.
[CPDLP-3015]: https://dfedigital.atlassian.net/browse/CPDLP-3015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3015] Improve application endpoint performance (`previously_funded?` N+1)

app/controllers/api/base_controller.rb, app/controllers/api/v1/applications_controller.rb, app/controllers/api/v2/applications_controller.rb, app/controllers/api/v3/applications_controller.rb, app/services/api/errors/response.rb, app/services/applications/reject.rb, config/locales/en.yml, config/routes.rb, db/seeds.rb, spec/requests/api/v1/applications_spec.rb, spec/requests/api/v2/applications_spec.rb, spec/requests/api/v3/applications_spec.rb, spec/services/applications/reject_spec.rb, spec/support/shared_examples/api_reject_application_endpoint_support.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3047
* `Applications::Reject` service class added
* Endpoints added:
* `/api/v1/npq-applications/:ecf_id/reject`
* `/api/v2/npq-applications/:ecf_id/reject`
* `/api/v3/npq-applications/:ecf_id/reject`
=> [CPDLP-3047] TS4 Add reject applications endpoint

config/initializers/courses.rb
The NPQ Senco course identifier has been changed from NPQS to NPQSENCO. This needs to be changed in the course name.
=> [CPDNPQ-1834] Updated senco course name

app/models/course.rb, db/migrate/20240517110612_ensure_course_identifiers_are_unique.rb, db/schema.rb, spec/factories/migration/ecf/npq_courses.rb, spec/models/course_spec.rb
I think the application would misbehave quite significantly if we had repeated course identifiers. In the longer term we need to have a think about how to decouple the data from the business logic, but for now let's just ensure they only exist once.
=> Ensure course identifiers are present and unique

Gemfile
Ticket: N/A
We are using FactoryBot to generate good test data in separation environment so we need to install/require it on Gemfile.
Require/Install `FactoryBot` gem in the separation environment.
=> Require FactoryBot gem in separation environment

.github/CODEOWNERS
This includes js updates and gem updates. We might get the occasional ruby version update on the actions but it should be less noisy
Ignore dependabot js and gem updates
failures:
=> Ignore dependabot prs when requesting reviews from team

lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb
Ticket: Same as https://github.com/DFE-Digital/npq-registration/pull/1421.
Re-opening a new PR as the other one had a broken build. Not sure why.
Rails 7 deprecated ActiveSupport::Deprecation singleton usage.
The gem `rails_semantic_logger`[ is still using it](https://github.com/reidmorrison/rails_semantic_logger/blob/93fed9edd0ba21490044e5fc7474c7b83eb2676c/lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb#L10). So a warning is displayed when running tests locally.
```Rails -- DEPRECATION WARNING: Calling silence on ActiveSupport::Deprecation is deprecated and will be removed from Rails (use Rails.application.deprecators.silence instead)```
Create a patch to fix the issue using `Rails.application.deprecators.silence` instead.
=> Fix deprecation warning with Rails7 usage of ActiveSupport::Deprecation singleton

app/controllers/api/v1/participants_controller.rb, app/controllers/api/v2/participants_controller.rb, app/controllers/api/v3/participants_controller.rb, app/serializers/api/participant_serializer.rb, app/services/participants/query.rb, app/services/valid_test_data_generators/applications_populater.rb, config/application.rb, spec/factories/applications.rb, spec/factories/schools.rb, spec/factories/users.rb, spec/requests/api/v1/participants_spec.rb, spec/requests/api/v2/participants_spec.rb, spec/requests/api/v3/participants_spec.rb, spec/serializers/api/participant_serializer_spec.rb, spec/services/participants/query_spec.rb, spec/support/shared_examples/api_index_endpoint_support.rb
Ticket: [CPDLP-3080](https://dfedigital.atlassian.net/browse/CPDLP-3080)
We would like to add the NPQ participant profiles endpoint to NPQ separation
- Add new API endpoint for all API versions: `GET api/v{1/2/3}/participants/npq​`.
[CPDLP-3080]: https://dfedigital.atlassian.net/browse/CPDLP-3080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3080] Add NPQ participant profiles endpoint

app/controllers/api/v1/participants_controller.rb, app/controllers/api/v2/participants_controller.rb, app/controllers/api/v3/participants_controller.rb, app/services/participants/resume.rb, config/locales/en.yml, spec/requests/api/v1/participants_spec.rb, spec/requests/api/v2/participants_spec.rb, spec/requests/api/v3/participants_spec.rb, spec/services/participants/resume_spec.rb, spec/support/shared_examples/api_resume_participant_endpoint_support.rb
[Jira-3088](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3088)
We want to add the participant resume endpoint from ECF, bringing across anything relevant to NPQ.
- Add Participant::Resume service
Add the service to move a participant back to the `active` state. This is lifted from ECF; instead of looking for the matching profile we find the matching application.
- Add /participants/npq/:id/resume endpoint
Adds the endpoint to enable providers to resume the training status of a participant.
=> Add `Participant::Resume` service and endpoints

app/models/declaration.rb, app/models/statement_item.rb, db/migrate/20240613151304_create_declarations.rb, db/migrate/20240614091519_add_declaration_to_statement_items.rb, db/schema.rb, spec/factories/declarations.rb, spec/factories/statement_items.rb, spec/models/declaration_spec.rb, spec/models/statement_item_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3085
* `Declaration` model added
* `cohort` and `lead_provider` has been included in declaration as this can change on the `application`
* `state_reason` is now on `Declaration` as its used when state is marked `ineligible`, therefore we do not need the `declaration_states` table. (reason is used for serializer)
=> [CPDLP-3085] TS6 - Add declarations table

app/controllers/api/v1/participants_controller.rb, app/controllers/api/v2/participants_controller.rb, app/controllers/api/v3/participants_controller.rb, app/models/application.rb, app/services/participants/defer.rb, config/locales/en.yml, spec/factories/applications.rb, spec/models/application_spec.rb, spec/requests/api/v1/participants_spec.rb, spec/requests/api/v2/participants_spec.rb, spec/requests/api/v3/participants_spec.rb, spec/services/participants/defer_spec.rb, spec/support/shared_examples/api_defer_participant_endpoint_support.rb
[Jira-3090](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3090)
We want to add the participant defer endpoint from ECF, bringing across anything relevant to NPQ.
- Add Participant::Defer service
Add the service to move a participant to a deferred state. This is lifted from ECF; instead of looking for the matching profile we find the matching application.
- Add /participants/npq/:id/defer endpoint
Adds the endpoint to enable providers to defer the training status of a participant.
I DRY up some of the duplication here between resume/defer in the final withdraw PR.
=> Add `Participant::Defer` service and endpoints

app/models/application.rb, app/serializers/api/application_serializer.rb, app/services/applications/query.rb, spec/models/application_spec.rb, spec/serializers/api/application_serializer_spec.rb, spec/services/applications/query_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3150
Add support for `eligible_for_dfe_funding?` in applications, so we take into consideration
the `funded_place` attribute for capping.
Related to this PR (https://github.com/DFE-Digital/early-careers-framework/pull/4871).
=> Add funded place logic to previously funded and eligibility

app/models/declaration.rb, app/services/applications/change_funded_place.rb, config/locales/en.yml, spec/models/declaration_spec.rb, spec/services/applications/change_funded_place_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3086
Add logic to check for `applicable_declarations` declarations before removing the `funded_place` in an application.
The API endpoint, as the validation returns `false`, will trigger a 422 with the error message from the validator.
=> Prevent funded place change with applicable declarations

app/services/valid_test_data_generators/applications_populater.rb, lib/tasks/valid_test_data_generators/separation_data.rake
Ticket: [CPDLP-3084](https://dfedigital.atlassian.net/browse/CPDLP-3084)
We have a service to create seed data for providers in separation which we need to keep up to date.
Add seed data for separation environment for participant profiles.
[CPDLP-3084]: https://dfedigital.atlassian.net/browse/CPDLP-3084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3084] Add seed data for separation environment for participant profiles

app/controllers/api/v1/declarations_controller.rb, app/controllers/api/v2/declarations_controller.rb, app/controllers/api/v3/declarations_controller.rb, app/models/declaration.rb, app/services/declarations/query.rb, config/routes.rb, spec/models/declaration_spec.rb, spec/requests/api/v1/declarations_spec.rb, spec/requests/api/v2/declarations_spec.rb, spec/requests/api/v3/declarations_spec.rb, spec/services/declarations/query_spec.rb
[Jira-3093](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3093)
We want to add the GET `/api/:version/declarations/:id` endpoint from ECF, which will return a single declaration by ID for the current lead provider.
- Add GET /api/:version/declarations/:id endpoint
Branches off #1445
=> Add declaration endpoint

config/initializers/constants.rb
The `https://mcas-proxyweb.mcas.ms/certificate-checker` prefix is added by DfE's O365 setup when people copy links and paste them into their browser. It looks like here it was accidentally pasted into the constant and the proxy ID eventually timed out.
=> Fix feedback link, remove weird proxyweb stuff

public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/swagger_helper.rb
To avoid confusing providers and until we make this dynamic, hardcode the url to separation instead of sandbox so providers don't try to test on sandbox.
Change base url in testing to separation rather than sandbox
failures:
=> Amend doc URL to separation rather than sandbox

app/models/declaration.rb, app/models/participant_outcome.rb, config/locales/en.yml, db/migrate/20240628073505_rename_outcome_to_participant_outcome.rb, db/schema.rb, spec/factories/participant_outcomes.rb, spec/models/declaration_spec.rb, spec/models/participant_outcome_spec.rb
Using `Outcome` here feels a bit confusing as the controller terminology is 'participant outcome'. Renaming to better align with what you would expect from looking at the controller.
=> Rename `Outcome` to `ParticipantOutcome`

app/services/ecf/npq_profile_creator.rb, app/services/report_service.rb, app/views/admin/applications/_application_details.html.erb, spec/views/admin/applications/show.html.erb_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1956
There is an issue with URNs not being passed over to ECF for private nurserys. This is because we are still passing over `DEPRECATED_private_childcare_provider_urn`.
This PR changes use of `DEPRECATED_private_childcare_provider_urn` to `private_childcare_provider&.provider_urn`
=> [CPDNPQ-1904] remove deprecated private_childcare_urn

app/services/report_service.rb
The `ReportService` runs on a cron every hour. It fetches all applications and puts them into a CSV to be saved in the `reports` table for the analytics dashboard. It is currently running this large query with an n+1 issue due to it not preloading `private_childcare_provider`. This is causing issues with the CPU load on our worker instances.
=> Preload private_childcare_provider in ReportService

app/controllers/api/v1/participants/outcomes_controller.rb, app/controllers/api/v2/participants/outcomes_controller.rb, app/controllers/api/v3/participants/outcomes_controller.rb, app/services/participant_outcomes/query.rb, spec/factories/declarations.rb, spec/requests/api/v1/participants/outcomes_spec.rb, spec/requests/api/v2/participants/outcomes_spec.rb, spec/requests/api/v3/participants/outcomes_spec.rb, spec/services/participant_outcomes/query_spec.rb, spec/support/shared_examples/api_index_endpoint_support.rb
[Jira-3098](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3098)
We want to bring across the participant outcomes endpoints from ECF into NPQ reg.
- Support filtering outcomes by participant ids
Update the `ParticipantOutcomes::Query` service to support filtering outcomes by one or more participant ids.
Add transient `user` to declaration to more easily create an outcome with a certain user (via declaration -> application -> user).
-  Add GET /app/:version/participants/npq/:id/outcomes endpoints
Adds the endpoints to retrieve outcomes for a given participant.
Add shared context for testing `index` actions on a given resource, for example GET `/parent/:id/resources`. Open to suggestions on better naming for this!
=> Add GET /app/:version/participants/npq/:id/outcomes endpoints

app/services/applications/accept.rb, app/services/applications/change_funded_place.rb, config/locales/en.yml, spec/services/applications/accept_spec.rb, spec/services/applications/change_funded_place_spec.rb
We currently validate against the funded place attribute regardless of type. So if a string is passed in we compute it as true.
This confused providers as they were passing values such as `"false"` and `"null"` and this was computed as `true`
- Ticket: [CPDLP-3239](https://dfedigital.atlassian.net/browse/CPDLP-3239)
Amend the validations in both services to only accept boolean values otherwise returns a validation error, even if it's a string.
Maybe we should allow strings and compute those values, but felt better to lock it down to just booleans
[CPDLP-3239]: https://dfedigital.atlassian.net/browse/CPDLP-3239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3239] Amend accept and change funding service to only accept funded place booleans only

app/services/ehco/targeted_delivery_funding_eligibility_updater.rb, spec/lib/services/ehco/targeted_delivery_funding_eligibility_updater_spec.rb
Ticket: N/A
When running tests, logger is outputting texts in screen.
`rspec spec/lib/services/ehco/targeted_delivery_funding_eligibility_updater_spec.rb`
Make the logger injectable so we can inject a fake logger in tests so it doesn't spit out text when running the tests.
=> Make logger injectable so we can disable logging in tests (targeted_delivery_funding_eligibility_updater_spec)

app/views/layouts/application.html.erb
Ticket: N/A
The GOV.UK Frontend is complaining about the missing `govuk-frontend-supported` css class in the `<body>` element.
- Add the css class
=> Fix the GOV.UK Frontend initialisation error

app/models/participant_outcome.rb, app/serializers/api/declaration_serializer.rb, spec/models/participant_outcome_spec.rb, spec/serializers/api/declaration_serializer_spec.rb, spec/serializers/api/declarations_csv_serializer_spec.rb
[Jira-3236](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3236)
We want to bring the `has_passed?` logic from ECF into `ParticipantOutcome` and expose in the `DeclarationSerializer`. The `has_passed` will be `nil` if the outcome does not exist or is `voided`, otherwise `true`/`false` for `passed` and `failed`.
- Add has_passed to DeclarationSerializer
=> Add `has_passed` to `DeclarationSerializer`

public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/requests/api/docs/v1/applications_spec.rb, spec/requests/api/docs/v1/declarations_spec.rb, spec/requests/api/docs/v2/applications_spec.rb, spec/requests/api/docs/v2/declarations_spec.rb, spec/requests/api/docs/v3/applications_spec.rb, spec/requests/api/docs/v3/declarations_spec.rb, spec/support/shared_examples/api_create_on_existing_resource_endpoint_documentation_support.rb, spec/support/shared_examples/api_update_endpoint_documentation_support.rb, spec/swagger_helper.rb, spec/swagger_schemas/filters/list_participant_declarations.rb, spec/swagger_schemas/models/participant_declaration.rb, spec/swagger_schemas/requests/participant_declaration_completed_request.rb, spec/swagger_schemas/requests/participant_declaration_request.rb, spec/swagger_schemas/requests/participant_declaration_retained_request.rb, spec/swagger_schemas/requests/participant_declaration_started_request.rb, spec/swagger_schemas/responses/participant_declaration.rb, spec/swagger_schemas/responses/participant_declarations.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3103
Add API docs for all the declaration endpoints in  NPQ in v1/v2/v3 for the GET/POST participant-declarations in all versions including any errors as in [About the API - Manage training for early career teachers](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fmanage-training-for-early-career-teachers.education.gov.uk.mcas.ms%2Fapi-reference%2F%3FMcasTsid%3D20596&McasCSRF=de29da0c68213eceedbb0dd96443cca1bf449ad8f7917e10b651b1814db41725) . Add the PUT void declarations in all versions.
=> Update swagger docs with declaration endpoints

config/initializers/courses.rb, spec/factories/courses.rb
Senco is a leadership course, and should belong to the leadership course group.
Change seed data for Senco point to leadership rather than specialist
failures:
=> Change Senco from specialist to leadership course

terraform/application/config/production.tfvars.json, terraform/application/database.tf, terraform/application/variables.tf
ECF postgres database don’t have a maintenance window set, so they are upgraded alongside nonprod at a random time
Ticket: https://trello.com/c/4NPqv8MF/1903-add-prod-postgres-maintenance-window
Add maintenance window to terraform
=> Add prod postgres maintenance window

app/services/valid_test_data_generators/applications_populater.rb, spec/services/valid_test_data_generators/applications_populater_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3102
We have a service to create seed data for providers in separation which we need to keep up to date.
Add outcomes to some accepted applications with completed declarations in the seed data.
=> [CPDLP-3102] Add outcomes seed data to separation

app/models/course_group.rb, app/services/declarations/create.rb, config/locales/en.yml, spec/factories/declarations.rb, spec/models/course_group_spec.rb, spec/models/declaration_spec.rb, spec/models/user_spec.rb, spec/services/declarations/create_spec.rb, spec/services/participant_outcomes/create_spec.rb, spec/services/statements/query_spec.rb
Ticket: [CPDLP-3198](https://dfedigital.atlassian.net/browse/CPDLP-3198)
When a provider submits a completed declaration we need to capture if they passed in an outcome.
Similar to ECF if a valid completed declaration has been created, create the outcome for that participant.
[CPDLP-3198]: https://dfedigital.atlassian.net/browse/CPDLP-3198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3198] Add outcomes logic to create declaration endpoint

app/services/declarations/void.rb, app/services/participant_outcomes/void.rb, spec/services/declarations/void_spec.rb, spec/services/participant_outcomes/void_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3199
* Created `ParticipantOutcomes::Void` service
* Updated `Declarations::Void` to run `ParticipantOutcomes::Void`
=> [CPDLP-3199] TS8 - Add outcomes logic to void declaration endpoint

Dockerfile, Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/test.rb
We want to use `bullet` to identify and alert on N+1 queries, so that we don't have to manually check for them.
- Add `bullet` gem
Add `bullet` to identify and report N+1 queries. Enabled in `development` and will raise an error in `test` if an N+1 is detected.
- Precompile assets using prod environment
We bundle the production assets and run the precompile using the test env, which doesn't make sense. It causes an issue now that we have `bullet` referenced in the `test.rb` as it installed installed with the production gems.
Switch to compiling assets using the prod environment. We need to specify a `SECRET_KEY_BASE` for this to complete, but it doesn't matter what it is.
Awkwardly due to the way we are mocking out the underlying services in our request specs and the way our queries are …
=> Add `bullet` gem

app/models/application.rb, config/locales/en.yml, spec/models/application_spec.rb
[Jira-3284](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3284)
When an application is accepted we attach a schedule. The application has a cohort as does the schedule, so we want to validate that an application can only have a schedule with the same cohort.
The `Accept` service ensures the schedule is picked using the application cohort, so this will always be the case when accepting an application; its more to protect against manual data changes.
- Add validation to ensure application cohort matches schedule cohort
=> Add missing application/schedule cohort validation

app/services/valid_test_data_generators/applications_populater.rb, lib/tasks/valid_test_data_generators/separation_data.rake, spec/services/valid_test_data_generators/applications_populater_spec.rb
Ticket: [CPDLP-3269](https://dfedigital.atlassian.net/browse/CPDLP-3269)
We need to revisit the rake task to setup seed data to cover all the set up specs below.
New data needs to be set up to support NPQ testing, some of which has already been set up in the rake task, but we’d like to beef up the scripts as per in the ticket description.
[CPDLP-3269]: https://dfedigital.atlassian.net/browse/CPDLP-3269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3269] Add data required to support NPQ MVP testing

config/application.rb, lib/middleware/time_traveler.rb, spec/lib/middleware/time_traveler_spec.rb
In ECF we allow the server-time to be changed per-request by specifying an `X-With-Server-Header` header.
We want to replicate this functionality in NPQ for all environments apart from production.
- Add X-With-Server-Date header support
In ECF we allow the server-time to be changed per-request by specifying an `X-With-Server-Header` header.
We want to replicate this functionality in NPQ for all environments apart from production.
Add `time_traveler` middleware from ECF and update it to use `ActiveSupport::Testing::TimeHelpers` instead of `TimeCop`. Load middleware into all environments, but disable in production.
I opted to load the middleware in all environments by default to avoid having to manually include it into new environments individually. The middleware itself will only run if …
=> Add X-With-Server-Date header support

app/services/valid_test_data_generators/applications_populater.rb
ASO is an old course which we shouldn't create data for anymore
Ignore ASO courses when creating seed data as they are old courses which we don't create applications for anymore
failures:
=> Ignore ASO courses instead of EHCO

app/serializers/api/declaration_serializer.rb, app/services/declarations/query.rb, spec/serializers/api/declaration_serializer_spec.rb
[Jira-3336](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3336)
The `DeclarationSerializer` was performing a second query for each declaration in order to find the latest outcome. Instead, we can preload the outomes in the query and perform an in-memory `sort_by` (instead of `order` which triggers another query) to find the latest outcome.
- Fix N+1 in DeclarationSerializer
=> Fix N+1 in DeclarationSerializer

app/models/application.rb, app/services/applications/accept.rb, app/services/applications/change_funded_place.rb, app/services/applications/reject.rb, app/services/declarations/statement_attacher.rb, app/services/declarations/void.rb, config/locales/en.yml, spec/models/application_spec.rb, spec/requests/api/docs/v3/applications_spec.rb, spec/services/applications/accept_spec.rb, spec/services/applications/change_funded_place_spec.rb, spec/services/applications/reject_spec.rb, spec/services/declarations/create_spec.rb, spec/services/declarations/statement_attacher_spec.rb, spec/services/declarations/void_spec.rb, spec/services/participants/change_schedule_spec.rb, spec/services/participants/defer_spec.rb, spec/services/participants/resume_spec.rb, spec/services/participants/withdraw_spec.rb, spec/support/shared_examples/participant_action_support.rb
[Jira-3244](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3244)
Update the API service class specs to use the `have_error` matcher.
Clean up the translations file to make it consistent.
- Clean up service error tests and translations
=> Clean up service error tests and translations

app/controllers/api/v1/applications_controller.rb, app/controllers/api/v1/declarations_controller.rb, app/controllers/api/v1/participant_outcomes_controller.rb, app/controllers/api/v1/participants/outcomes_controller.rb, app/controllers/api/v1/participants_controller.rb, app/controllers/api/v2/applications_controller.rb, app/controllers/api/v2/declarations_controller.rb, app/controllers/api/v2/enrolments_controller.rb, app/controllers/api/v2/participant_outcomes_controller.rb, app/controllers/api/v2/participants/outcomes_controller.rb, app/controllers/api/v2/participants_controller.rb, app/controllers/api/v3/applications_controller.rb, app/controllers/api/v3/declarations_controller.rb, app/controllers/api/v3/participant_outcomes_controller.rb, app/controllers/api/v3/participants/outcomes_controller.rb, app/controllers/api/v3/participants_controller.rb
We were using the same `Query` instance for both the `index` and `show` actions; this meant the filtering was being applied to the `show` endpoints when it shouldn't be (although this would only happen if a filter parameter was passed in).
- Fix query scopes for show actions
Extract the query `conditions` so that we only surface them in the `index` actions.
=> Fix query scopes for `show` actions

Gemfile, Gemfile.lock, config/initializers/rack_attack.rb, spec/rails_helper.rb, spec/requests/csp_reports_controller_spec.rb, spec/requests/rate_limiting_spec.rb, spec/support/shared_examples/rate_limiting_support.rb
[Jira-3337](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3337)
We want to mirror the rate limiting for API requests from ECF.
- Add rate limiting for `/api` requests that matches the ECF configuration.
Clean up and improve the testing around rate limiting.
Remove redundant protected routes (they no longer appear to exist).
=> Setup Rack::Attack for API requests

app/controllers/api/v3/applications_controller.rb, app/controllers/api/v3/participants_controller.rb, app/services/participant_outcomes/query.rb, spec/requests/api/v3/applications_spec.rb, spec/requests/api/v3/participants_spec.rb, spec/support/shared_examples/api_index_endpoint_support.rb
[Jira-3339](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3339)
The API sorting was not working correctly due to the `sort` parameter not being passed into the underlying query objects.
- Fix API sorting
Update `index` actions for applications/participants so that the `sort` parameter tranfers to the underlying query.
Add test coverage to avoid regressions in the future.
Remove unused `sort` attribute from outcomes query.
=> Fix API sorting

app/services/api/concerns/filter_ignorable.rb, app/services/applications/query.rb, app/services/declarations/query.rb, app/services/participant_outcomes/query.rb, app/services/participants/query.rb, app/services/statements/query.rb, spec/services/api/concerns/filter_ignorable_spec.rb, spec/services/applications/query_spec.rb, spec/services/declarations/query_spec.rb, spec/services/participant_outcomes/query_spec.rb, spec/services/participants/query_spec.rb, spec/services/statements/query_spec.rb
[Jira-3341](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3341)
Currently, if we add a blank filter to a query, for example `?filter[cohort_start_years]=` it will return no results. Instead, we want to treat the filter as if it wasn't specified, which is how ECF functions.
- Treat blank filters as if they are not specified
Add `FilterIgnorable` concern to centralise the logic around filtering. Treat empty values as ignored as well as the `:ignore` symbol. Retain `nil` as a valid/filterable value.
=> Ignore empty filters in queries

app/controllers/api/v1/participants/outcomes_controller.rb, app/controllers/api/v1/participants_controller.rb, app/controllers/api/v2/participants/outcomes_controller.rb, app/controllers/api/v2/participants_controller.rb, app/controllers/api/v3/participants/outcomes_controller.rb, app/controllers/api/v3/participants_controller.rb, app/services/declarations/create.rb, app/services/participant_outcomes/create.rb, app/services/participants/action.rb, app/services/participants/change_schedule.rb, app/services/participants/defer.rb, app/services/participants/resume.rb, app/services/participants/withdraw.rb, app/services/valid_test_data_generators/applications_populater.rb, config/locales/en.yml, spec/requests/api/v1/participants/outcomes_spec.rb, spec/requests/api/v1/participants_spec.rb, spec/requests/api/v2/participants/outcomes_spec.rb, spec/requests/api/v2/participants_spec.rb, spec/requests/api/v3/participants/outcomes_spec.rb, spec/requests/api/v3/participants_spec.rb, spec/services/participant_outcomes/create_spec.rb, spec/services/participants/change_schedule_spec.rb, spec/services/participants/defer_spec.rb, spec/services/participants/resume_spec.rb, spec/services/participants/withdraw_spec.rb, spec/support/shared_examples/api_create_endpoint_support.rb, spec/support/shared_examples/api_update_endpoint_support.rb, spec/support/shared_examples/participant_action_support.rb
[Jira-3347](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3347)
There are discrepencies between the ECF error messages and those in NPQ reg - namely:
- NPQ reg has multiple invalid schedule error messages whereas ECF only has one.
- NPQ reg returns `participant_id` errors on the `participant` attribute instead of `participant_id`.
- Remove invalid_schedule error
We only want one `invalid_schedule` error for `ChangeSchedule`, which is the same one we use for `blank`.
-  Change participant errors to participant_id
On various services we accept a `participant` instead of `participant_id`; this results in the error messages being on the `participant` attribute instead of the …
=> Fix error inconsistencies with ECF

app/controllers/api/base_controller.rb, app/services/api/errors/filter_validation_error.rb, app/services/participants/query.rb, config/locales/en.yml, spec/services/participants/query_spec.rb, spec/support/shared_examples/api_index_endpoint_support.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3344
* We can now raise `API::Errors::FilterValidationError` from query service classes.
* Base controller rescues `API::Errors::FilterValidationError` with a 422 response.
* Added filter validation on `Participants::Query` for `training_status`
=> [CPDLP-3344] MVP NPQ Prep - Add training status error

app/services/declarations/create.rb, app/services/declarations/void.rb, spec/services/declarations/create_spec.rb, spec/services/declarations/void_spec.rb, spec/support/matchers/error_matcher.rb
[Jira-3348](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3348)
In a number of scenarios we return multiple error messages whereas in ECF we would only return a single error at a time.
We want to update NPQ reg to be more consistent with ECF; only returning single errors on occasion.
- Only return one declaration error at a time when voiding
Currently we can return multiple declaration errors when voiding a declaration.
Only return a single declaration error at a time.
- Limit multiple errors on participant actions
Currently, if there is an error on the `participant_id` attribute and the `course_identifier` attribute we would return both errors. Instead, we only want to return the …
=> Limit response to single errors on certain actions

app/services/importers/manual_validation.rb, spec/lib/services/importers/manual_validation_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-2004
Excel strips leading zeros from TRNs. This PR adds them back if they are missing.
TRNs must be 7 digits. If the importer receives a validated TRN that is less then it will assume excel has stripped them. This PR therefore add 0's until the TRN is 7 digits.
=> [CPDNPQ-2004] TRN import with missing leading zeros

app/webpacker/styles/api_guidance.scss, app/webpacker/styles/code.scss
[Jira-3394](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3394)
The code blocks are not rendering correctly at the moment, we want to tweak the display to fix a few issues.
Reduce font size of inline `code` blocks to match the surrounding text.
Add line-height to the separate `code` blocks to ensure the underscores render visibly.
| <img width="1370" alt="Screenshot 2024-08-12 at 15 38 31" src="https://github.com/user-attachments/assets/d6750c41-2cc9-408d-adc0-235856ecf7a0">  | <img width="1370" alt="Screenshot 2024-08-12 at 15 38 02" src="https://github.com/user-attachments/assets/1eedb40f-6934-4db9-90ee-08fce8d2fd3b">   |
=> Minor style fixes for code blocks

app/models/application.rb, app/serializers/api/declaration_serializer.rb, app/serializers/api/participant_serializer.rb, app/services/applications/query.rb, app/services/declarations/query.rb, app/services/participants/query.rb, spec/models/application_spec.rb, spec/serializers/api/declaration_serializer_spec.rb, spec/serializers/api/participant_serializer_spec.rb, spec/services/applications/query_spec.rb, spec/services/declarations/query_spec.rb, spec/services/participants/query_spec.rb, spec/support/shared_examples/api_index_csv_endpoint_support.rb, spec/support/shared_examples/api_index_endpoint_support.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3363
* `Application` will touch `User` when updated
* `DeclarationSerializer` `updated_at` includes `participant_outcomes` and `statement_items`
* `ParticipantSerializer` `updated_at` includes `participant_id_changes` and `applications`
* Query services have been updated to include all the related tables `updated_at`
=> [CPDLP-3363] MVP NPQ Prep - Touch model improvements on endpoints

app/serializers/api/participant_serializer.rb, spec/serializers/api/participant_serializer_spec.rb
Ticket: [CPDLP-3391](https://dfedigital.atlassian.net/browse/CPDLP-3391)
On the participant serialiser in npq enrolments we should only surface accepted applications rather than all applications
Amend the participant serialiser to show a list of only accepted applications for that provider.
[CPDLP-3391]: https://dfedigital.atlassian.net/browse/CPDLP-3391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3391] Only surface accepted applications in enrolments

db/migrate/20240812095216_change_declaration_date_to_datetime_in_declarations.rb, db/schema.rb, public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/swagger_schemas/models/declaration_csv.rb, spec/swagger_schemas/models/participant_declaration.rb, spec/swagger_schemas/requests/participant_declaration_completed_request.rb, spec/swagger_schemas/requests/participant_declaration_retained_request.rb, spec/swagger_schemas/requests/participant_declaration_started_request.rb
[Jira-3390](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3390)
The `Declaration#declaration_date` is a `Date` in NPQ reg and a `DateTime` in ECF. The side-effect of having it as a `Date` in NPQ reg is that the `rfc3889` format uses an explicit timezone offset of `+00:00` instead of the shorthand `Z` that is used for `DateTime`. We're concerned this might break provider integrations, so to keep it consistently using the `Z` shorthand we are changing the field to a `DateTime` in NPQ reg.
- Change Declaration#declaration_date to DateTime
The issue in NPQ reg is the explicit `+00:00` in the formatted date:
```
(byebug) …
```
=> Change Declaration#declaration_date to DateTime

db/migrate/20240814093003_create_kind_of_nurseries_enum.rb, db/migrate/20240814095351_change_applications_kind_of_nursery_to_enum.rb, db/schema.rb, spec/models/application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3257
We currently set an enum for `kind_of_nursery` in the application model but don’t have it in the db
Set `kind_of_nursery` as an enum in the db.
=> [CPDLP-3257] Add in DB `kind_of_nursery` enum in application

app/models/get_an_identity/webhook_message.rb, app/services/get_an_identity_service/webhooks/user_updated_processor.rb, spec/models/get_an_identity/webhook_message_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3252
There's a regression created after https://github.com/DFE-Digital/npq-registration/pull/1593/files#diff-af07b0740b12a08358fb8e2d95eaddb480d815b03088b29ffbc6a308abb3e67dL27
Name the method properly so it fixes the regression.
=> Rename WebhookMessage processed method

.github/workflows/deploy.yml
We want to disable this temporarily to make testing easier (manually deploy instead for now).
=> Disable deploy to migration

spec/support/helpers/admin_login.rb, spec/support/rack_attack.rb
Ticket: [CPDLP-3434](https://dfedigital.atlassian.net/browse/CPDLP-3434)
Intermittently we get 429 failures in one of the parallel builds in Rspec in NPQ reg see https://github.com/DFE-Digital/npq-registration/actions/runs/10453888479/job/28945276236. After it’s rebuilt it passes ok
- Fix this issue to avoid flakiness and delays in the build
- Rack attack was being turned on in a test and depending upon whether it runs before the `spec/requests` specs, we then were getting rack attack blocking requests specs afterwards.
- Add missing `spec/support/rack_attack.rb` to turn rack attack off by default in tests and cause we still wanna optionally turn it on in [spec/support/shared_examples/rate_limiting_support.rb](https://github.com/DFE-Digital/npq-registration/blob/main/spec/support/shared_ex …
=> [CPDLP-3434] Fix flakey tests linked to rack attack

app/models/declaration.rb, app/services/declarations/create.rb, app/services/declarations/void.rb, docs/state_machines.md, spec/models/declaration_spec.rb
We want to add a state machine to the `Declaration` model to be consistent with `Statement` and `StatementItem`.
- Add state machine to `Declaration` model
Add state machine, defining transitions.
- Use state machine where possible
We can clean up/remove some of our methods to use the convenience methods provided by the state machine library.
I opted not to add a state machine to the `ParticipantOutcome#state` as we don't appear to transition between states with outcomes, instead creating a new outcome of a different state.
I'm not sure how much value this is actually adding; I think we need to go more 'all in' on the state machine and look to consolidate some of the constants/state logic spread throughout the various service classes.
=> Add state machine to `Declaration` model

.github/workflows/rspec.yml, sonar-project.properties
These change on each run and are specified in the action when we call the sonar-scanner CLI. The path to the combined coverage report was also wrong as I didn't realise simplecov puts it in the default `coverage` directory instead of the directory where the `collate` is ran.
=> Remove hard-coded coverage paths from sonar-project.properties

.gitignore, terraform/application/.terraform.lock.hcl, terraform/application/database.tf, terraform/application/terraform.tf, terraform/domains/environment_domains/.terraform.lock.hcl, terraform/domains/environment_domains/terraform.tf, terraform/domains/infrastructure/.terraform.lock.hcl, terraform/domains/infrastructure/terraform.tf
Keep providers up-to-date
This is now possible after https://github.com/DFE-Digital/terraform-modules/releases/tag/v0.38.0 was released
Ticket: https://trello.com/c/moH45K2M
Upgrade in application, domains/infrastructure and domains/environment_domains
make production terraform-plan
make domains-infra-plan
make production domains-plan
=> Upgrade terraform azurerm providers to 3.116.0

app/models/participant_outcome.rb, app/models/participant_outcome_api_request.rb, db/migrate/20240820153944_create_participant_outcome_api_requests.rb, db/schema.rb, spec/factories/participant_outcome_api_requests.rb, spec/models/participant_outcome_api_request_spec.rb, spec/models/participant_outcome_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3442
Following [CPDLP-3396](https://dfedigital.atlassian.net/browse/CPDLP-3396) we came up with a plan to implement sending outcomes to TRA in NPQ reg app.
- Add new table and model for participant outcomes api request;
- Check indexes/FK we need to also create (per ECF app);
[CPDLP-3396]: https://dfedigital.atlassian.net/browse/CPDLP-3396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3442] Add new table and model for outcomes api request

app/controllers/npq_separation/migration/migrations_controller.rb
[Jira-3441](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3441)
This removes the need to manually check for super_admin users in a `before_action`.
- Update MigrationsController to inherit from SuperAdminController
=> Update MigrationsController to inherit from SuperAdminController

.github/workflows/rspec.yml
Sonar cloud is failing on dependabot prs
https://github.com/DFE-Digital/npq-registration/actions/runs/10531124012/job/29182659403
We don't need to run sonar cloud on dependabot. Also this is causing failures in azure login due to not deploying anything in dependabot prs and we are missing azure login setup
failures:
=> Do not run sonar cloud on dependabot prs

terraform/application/config/separation.tfvars.json
> ⚠️ As the DB is not high availability there will be downtime when this rolls out, so we may want to merge it at a quiet time (infra team say GitHub is fine to deploy it).
[Jira-3447](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3447)
We noticed that the separation env was quite slow; we want to scale it up to be similar to production as providers are actively using this environment now.
- Scale up the separation environment
I've manually checked this with `terraform-plan` and it looks good:
```
DOCKER_IMAGE=ghcr.io/dfe-digital/npq-registration:824c2224f04129ed50d2d7302c7be480a036ed79 make ci separation terraform-plan
```
=> Scale up the separation environment

app/models/migration/ecf/participant_id_change.rb, app/models/migration/ecf/user.rb, app/models/participant_id_change.rb, app/services/migration/migrators/participant_id_change.rb, spec/factories/migration/ecf/participant_id_changes.rb, spec/models/migration/ecf/participant_id_change_spec.rb, spec/models/migration/ecf/user_spec.rb, spec/models/participant_id_change_spec.rb, spec/services/migration/migrators/participant_id_change_spec.rb
[Jira-3437](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3437)
We want to migrate participant ID changes from ECF to NPQ reg. We have to do this in a separate migrator (to the users migrator) as we need to migrate the users first (the `ParticipantIdChange` model does not store the `ecf_id`, instead using the NPQ reg ids).
- Add ParticipantIdChange migrator
=> Migrate `ParticipantIdChange` records from ECF

app/jobs/crons/batch_send_latest_outcomes_job.rb, app/jobs/send_to_qualified_teachers_api_job.rb, app/models/participant_outcome.rb, app/services/qualified_teachers_api_sender.rb, config/initializers/delayed_job.rb, spec/factories/participant_outcomes.rb, spec/jobs/crons/batch_send_latest_outcomes_job_spec.rb, spec/jobs/send_to_qualified_teachers_api_job_spec.rb, spec/models/participant_outcome_spec.rb
Ticket: [CPDLP-3444](https://dfedigital.atlassian.net/browse/CPDLP-3444)
We want to implement sending outcomes to TRA in NPQ reg app.
- Add BatchSendLatestOutcomesJob (per ECF)
- Add SendToQualifiedTeachersApiJob (per ECF)
- Include logic to retry jobs when TooManyRequests is raised (per ECF)
- Add to_send_to_qualified_teachers_api and related scopes
[CPDLP-3444]: https://dfedigital.atlassian.net/browse/CPDLP-3444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3444] Add BatchSendLatestOutcomesJob and SendToQualifiedTeachersApiJob

app/models/migration/ecf/finance/milestone.rb, app/models/migration/ecf/finance/schedule.rb, app/models/migration/ecf/finance/schedule/npq.rb, app/models/migration/ecf/finance/schedule/npq_ehco.rb, app/models/migration/ecf/finance/schedule/npq_leadership.rb, app/models/migration/ecf/finance/schedule/npq_specialist.rb, app/models/migration/ecf/finance/schedule/npq_support.rb, app/models/migration/ecf/finance/schedule_milestone.rb, app/services/migration/migrators/course.rb, app/services/migration/migrators/schedule.rb, spec/factories/migration/ecf/finance/milestones.rb, spec/factories/migration/ecf/finance/schedules.rb, spec/models/migration/ecf/finance/milestone_spec.rb, spec/models/migration/ecf/finance/schedule_spec.rb, spec/services/migration/migrators/course_spec.rb, spec/services/migration/migrators/schedule_spec.rb, spec/support/shared_examples/migrator_support.rb
We want to migrate NPQ schedules from ECF into NPQ reg.
- Add `Schedule` migrator
Add the `Schedule` migrator to bring across all NPQ schedules from ECF. As part of this change we also now create `CourseGroup` during the `Course` migration (we can't do this in its own migrator as it doesn't fir the pattern of bringing across records from ECF).
A `Schedule` must match on cohort, name, identifier and course group (derived from the ECF schedule type). We set the applies from/to based on the milestone dates. All milestone dates for ECF schedules must be the same or a failure is recorded.
=> Migrate `Schedules` from ECF

app/services/valid_test_data_generators/pending_applications_populater.rb, lib/tasks/valid_test_data_generators/separation_data.rake, spec/services/valid_test_data_generators/pending_applications_populater_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3410
* Created service `ValidTestDataGenerators::PendingApplicationsPopulater` to create pending applications only
=> [CPDLP-3410] Creates addtional pending applications for providers

spec/factories/cohorts.rb
On 1st September we rolled over to the next cohort (as the current) and this caused the `declaration_date` to be invalid. Pushing the rollover date to next month to unblock the pipeline while we fix properly.
=> Fix declaration_date mismatch with schedule

.github/workflows/rspec.yml
As of v4.4 of `actions/upload-artifact@v4` it no longer uploads hidden files; this means the `.resultset.json` coverage report is omitted. Add `include-hidden-files: true` to ensure hidden files are picked up.
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#hidden-files
=> Fix sonar cloud in CI

app/models/migration/ecf/finance/statement.rb, app/models/migration/ecf/finance/statement_line_item.rb, app/services/migration/migrators/statement.rb, app/services/migration/migrators/statement_item.rb, spec/factories/migration/ecf/finance/statement_line_item.rb, spec/models/migration/ecf/finance/statement_line_item_spec.rb, spec/models/migration/ecf/finance/statement_spec.rb, spec/services/migration/migrators/statement_item_spec.rb
[Jira-3440](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3440)
As part of the `Statement` migrator we also want to bring across `StatementLineItem` records from ECF. We can match these on the `declaration_id` and `state` for each statement.
- Migrate statement line items from ECF
=> Add `StatementLineItem` to `Statement` migrator

app/models/migration/data_migration.rb, app/services/migration/failure_manager.rb, app/services/migration/migrators/base.rb, spec/features/migration_spec.rb, spec/helpers/migration_helper_spec.rb, spec/models/migration/data_migration_spec.rb, spec/services/migration/failure_manager_spec.rb, spec/support/shared_examples/migrator_support.rb
[Jira-3485](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3485)
We are finding that failures are duplicated in the reports, so the same ID for an object that has failed will appear multiple times.
- Clear migration failures prior to running
As we store failures in Redis, when we clear the NPQ reg database and re-run a migration after a failed migration the failure manager will add the failures to those from the last run (as the `DataMigration` models/ids get reset so are the same as the previous run).
To avoid this, we can purge the failures from Redis for a `DataMigration` as part of the migration preparation.
- Fix rounding issues with data migrations
We are rounding down in the …
=> Clear migration failures prior to running

app/models/migration/ecf/participant_profile_state.rb, app/services/migration/migrators/application_state.rb, db/migrate/20240904072033_add_ecf_id_to_application_states.rb, db/schema.rb, spec/factories/migration/ecf/participant_profile_states.rb, spec/models/migration/ecf/participant_profile_state_spec.rb, spec/services/migration/migrators/application_state_spec.rb
[Jira-3489](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3489)
We want to bring across the `ParticipantProfileState` records from ECF to NPQ reg, as `ApplicationState` records. The `participant_profile_id` will match up to the `ecf_id` on the `Application` in NPQ reg.
- Add `ApplicationState` migrator
=> Add `ApplicationState` migrator

app/models/migration/ecf/participant_outcome_api_request.rb, app/services/migration/migrators/participant_outcome_api_request.rb, spec/factories/migration/ecf/participant_outcome_api_requests.rb, spec/services/migration/migrators/participant_outcome_api_request_spec.rb
Ticket: [CPDLP-3508](https://dfedigital.atlassian.net/browse/CPDLP-3508)
We need to pull in participant outcome api request data to NPQ.
Add Participant Outcome API migrator.
[CPDLP-3508]: https://dfedigital.atlassian.net/browse/CPDLP-3508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3508] Add Participant Outcome API migrator

spec/services/valid_test_data_generators/separation_shared_data_spec.rb
Ticket: N/A
A test is flakey.
Fixes `rspec ./spec/services/valid_test_data_generators/separation_shared_data_spec.rb:101`
=> Fix flakey test in separation_shared_data_spec file

Makefile
This allows sshing into the worker pod when we need to run commands and the web app is not deployed
Add `aks-worker-ssh` command to make file 
failures:
=> Add worker ssh command to make file

app/services/migration/migrators/user.rb, spec/services/migration/migrators/user_spec.rb
[Jira-3487](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3487)
We only want to flag an issue if an ECF user is found with multiple, verified TRNs that are different on their NPQ applications.
- Only check verified TRNs in User migrator
=> Only check verified TRNs in User migrator

app/views/registration_wizard/ineligible_for_funding/_not_eligible_for_scholarship_funding.html.erb, spec/features/journeys/happy_paths/basic_registration_journey_spec.rb, spec/features/journeys/happy_paths/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb, spec/features/journeys/happy_paths/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb, spec/features/journeys/happy_paths/changing_from_outside_of_catchment_area_to_inside_spec.rb, spec/features/journeys/happy_paths/via_using_old_name_and_not_headship_spec.rb, spec/features/journeys/happy_paths/via_using_same_name_spec.rb, spec/features/journeys/happy_paths/when_get_an_identity_returns_no_trn_spec.rb, spec/features/journeys/happy_paths/when_working_in_other_spec.rb, spec/features/journeys/happy_paths/while_working_at_public_nursery_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2073
Throughout the NPQ application, all text which currently says “state funded” should say “state-funded”
=> [CPDNPQ-2073] Standardise hyphenation of "state-funded"

app/serializers/api/participant_serializer.rb, spec/requests/api/docs/v1/participants_spec.rb, spec/requests/api/docs/v2/participants_spec.rb, spec/requests/api/docs/v3/participants_spec.rb, spec/serializers/api/participant_serializer_spec.rb, spec/services/valid_test_data_generators/separation_shared_data_spec.rb
Ticket: [CPDLP-3488](https://dfedigital.atlassian.net/browse/CPDLP-3488)
In ECF we surface the TRN in the NPQ participant serialiser from the teacher profile. The teacher profile is only updated if the TRN is validated.
In NPQ update the trn to only read from the teacher_reference_number if it is validated on the application.
[CPDLP-3488]: https://dfedigital.atlassian.net/browse/CPDLP-3488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3488] Update NPQ participant serialiser to show validated trn

app/services/migration/migrators/application_state.rb, app/services/migration/migrators/base.rb, app/services/migration/migrators/contract.rb, spec/services/migration/migrators/application_state_spec.rb, spec/services/migration/migrators/contract_spec.rb
[Jira-3563](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3563)
The `Contract` migrator has a number of failures caused by a bug in the migration code; we are not correctly copying attributes from the ECF model to the NPQ reg model.
- Optimise lookups in Contract migrator
To be consistent with other migrators and to hopefully speed things up we preload the lookups (course/statement).
- Fix attribute slicing in migrators
In the `Contract` and `ApplicationState` migrators we slice attributes using an array; this results in an empty hash and the tests were passing as we made the same slicing error. We need to use the splat operator here to correctly slice the attributes. In the …
=> Fix bugs in Contract migrator

app/services/migration/migrators/statement_item.rb, spec/factories/migration/ecf/participant_declarations.rb, spec/services/migration/migrators/statement_item_spec.rb
[Jira-3499](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3499)
We get a number of failures due to migrating ECF statement items (as we don't migrate ECF statements they fail to match up to a statement in NPQ reg).
- Exclude ECF statement items from `StatementItem` migrator.
=> Exclude ECF statement line items from migration

app/services/migration/migrators/application.rb, app/services/migration/migrators/base.rb, app/services/migration/migrators/schedule.rb, spec/factories/migration/ecf/npq_applications.rb, spec/services/migration/migrators/application_spec.rb
[Jira-3497](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3497)
We want to bring across the data associated with NPQ applications in ECF to NPQ reg. Previously we were performing an integrity check on the attributes, but after investigation we determined all attributes should be updated from ECF to NPQ reg for applications.
The school, course, lead provider and user should not be different and we have added an integrity check to ensure this.
- Migrate ECF applications to NPQ reg
The attributes that are identical in each:
```
created_at
updated_at
headteacher_status
eligible_for_funding
funding_choice
works_in_school
employer_name
employment_role
targeted_support_funding_eligibility …
```
=> Migrate ECF applications to NPQ reg

app/controllers/accounts/user_registrations_controller.rb, spec/features/account_spec.rb
The user registrations page doesn't really show any personal data but should be behind a login regardless. No data can be changed from it without signing in.
=> Ensure the user registrations page isn't public

app/components/npq_separation/navigation_structures/guidance_navigation_structure.rb, app/views/api/guidance/index.html.erb
Moved 'How-to guides' link to right of primary navigation
add new how to section to nav, also add anchor as it's on the same page
failures:
=> Added 'How-to guides' anchor link to primary navigation on API guidance pages

app/services/migration/migrators/user.rb, spec/services/migration/migrators/user_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3484
- Added new `find_or_initialize_user(ecf_user)` method:
- use `ecf_user.id` and `ecf_user.get_an_identity_id` to find users on NPQ
- if users don't exist, initialize new user and return
- if user exists with only `ecf_user.id`, return user
- if both id's return users they are the same, return user
- if both id's return users, but they are different, raise error
- if only `ecf_user.get_an_identity_id` return a user, look into ECF with the `ecf_id`
- if not found, update NPQ user's `ecf_id`
- if ECF user exists, check if its an orphaned user (transferred etc)
- if yes, update NPQ user's `ecf_id`
- if no, raise an error
=> [CPDLP-3484] User migrator find or initialise logic to deal with orphaned ecf user, but return error for all the other scenarios

db/seeds/base/add_schedules.rb, spec/factories/cohorts.rb, spec/factories/schedules.rb, spec/support/with_default_schedules.rb
Declaration model validations rely on:
- `declaration_date` being in the future
- `declaration_date` being on/after the `applies_from` date in the schedule attached to the accepted application
Our factory set up data for schedules/cohorts is close to production data, where the schedule `applies_from` date can start from October for a new cohort. 
For the previous cohort since October was in the past all tests were passing. However after September the 1st we moved into a new cohort due to our cohort factory set up. That rendered the new schedules and `applies_from` dates in the future. This meant most of our test suite failed where declarations were being created.
After multiple iterations found in: https://github.com/DFE-Digital/npq-registration/pull/1684 to …
=> Workaround for declaration validation failures in specs

.devcontainer/boot.sh, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
Codespaces has stopped working recently; its failing to boot rails on some occasions and on older PRs the asset pipeline appears to be broken.
- Fix Codespaces not booting
Codespaces fails to run since we changed the asset pipeline; we need to run `yarn build` and `yarn build:css` to compile the JS/CSS assets. Instead of doing this once on boot I've opted to run Foreman in the Codespace, which gives us the `--watch` behaviour to recompile CSS/JS as and when it changes.
The codespace was also failing to boot due to `bundle install` failing to compile native gems (`bigdecimal`). I went on a bit of a wild goose chase with this error; initially I thought it was because the `docker-compose.yml` recently changed, but Codespaces uses a different one. I then thought it was due to native libraries …
=> Fix Codespaces

app/services/migration/migrators/application.rb, spec/services/migration/migrators/application_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3572
* Updated `Migration::Migrators::Application` to save school, lead_provider and course from ECF NPQ Application
=> [CPDLP-3572] Data cleanup - Favour ECF in application migrator

public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/swagger_schemas/models/application.rb, spec/swagger_schemas/models/application_csv.rb, spec/swagger_schemas/models/participant.rb
The `teacher_reference_number` returned in Application and Participant responses can be `nil`; we should indicate this in the API docs.
- Make TRN nullable in API docs
=> Make TRN nullable in API docs

app/services/migration/migrators/application.rb, app/services/migration/migrators/base.rb, app/services/migration/migrators/cohort.rb, app/services/migration/migrators/contract.rb, app/services/migration/migrators/course.rb, app/services/migration/migrators/declaration.rb, app/services/migration/migrators/participant_id_change.rb, app/services/migration/migrators/schedule.rb, app/services/migration/migrators/statement.rb, app/services/migration/migrators/statement_item.rb, db/migrate/20240916124923_add_ecf_id_to_remaining_tables.rb, db/schema.rb, spec/factories/migration/ecf/cohorts.rb, spec/features/migration_spec.rb, spec/services/migration/migrators/application_spec.rb, spec/services/migration/migrators/cohort_spec.rb, spec/services/migration/migrators/contract_spec.rb, spec/services/migration/migrators/declaration_spec.rb, spec/services/migration/migrators/participant_id_change_spec.rb, spec/services/migration/migrators/schedule_spec.rb, spec/services/migration/migrators/statement_item_spec.rb, spec/services/migration/migrators/statement_spec.rb, spec/services/valid_test_data_generators/separation_shared_data_spec.rb
[Jira-3569](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3569)
We want to add the `ecf_id` to all the tables (apart from schools) where we're bringing across data from ECF. This will enable us to simplify the migration logic and speed up some of the lookups.
- Add ecf_id to remaining migration tables
Add the `ecf_id` to the remaining migration tables, apart from `schools` as these already exist in NPQ reg and are only verified/not actually migrated as part of the migration process.
The `ecf_id` fields are nullable since we don't expose them to lead providers and will not need to generate them going forward.
-  Use ecf_id in all migrators
We now have `ecf_id` on cohorts, contracts, participant_id_changes, schedules and statement_items, …
=> Add `ecf_id` to remaning migration tables

app/views/layouts/api_guidance.html.erb, spec/features/guidance_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3Aacb48219-565b-41a9-a019-3a72ebc165b0&selectedIssue=CPDLP-3474
Gotta go back innit
- Add backlink to guidance pages except for the index page.
- Move grid row div only into index section
failures:
=> Add back link to guidance pages

db/schema.rb
Add missing schema migrations for contract templates, this was removed accidentally
thanks @leandroalemao for spotting
=> Add missing schema migrations for contract templates

app/models/participant_id_change.rb, app/serializers/api/participant_serializer.rb, app/services/migration/migrators/participant_id_change.rb, app/services/participants/query.rb, app/services/valid_test_data_generators/applications_populater.rb, db/migrate/20240917142926_remove_foreign_keys_from_participant_id_changes.rb, db/migrate/20240918145749_change_from_and_to_participant_ids_to_uuid_in_participant_id_changes.rb, db/schema.rb, spec/factories/applications.rb, spec/factories/participant_id_changes.rb, spec/models/participant_id_change_spec.rb, spec/serializers/api/participant_serializer_spec.rb, spec/services/migration/migrators/participant_id_change_spec.rb, spec/services/participants/query_spec.rb, spec/support/shared_examples/api_index_endpoint_support.rb
Ticket: [CPDLP-3575](https://dfedigital.atlassian.net/browse/CPDLP-3575)
After reviewing errors in migrators, we found out there're some missing users in NPQ as they are orphans. We’ve agreed to change the table to UUIDs and only populate those values without bringing across the users.
Update user from/to in NPQ for Participant id changes table.
[CPDLP-3575]: https://dfedigital.atlassian.net/browse/CPDLP-3575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3575] Update user from/to participant id changes table

app/services/migration/migrators/application.rb, app/services/migration/migrators/base.rb, app/services/migration/migrators/itt_provider.rb, app/services/migration/migrators/private_childcare_provider.rb, spec/serializers/api/application_serializer_spec.rb, spec/services/migration/migrators/application_spec.rb, spec/services/migration/migrators/itt_provider_spec.rb, spec/services/migration/migrators/private_childcare_provider_spec.rb
[Jira-3574](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3574)
We want to bring across any IttProvider or PrivateChildcareProvider records that exist in ECF (as part of an NPQApplication) but are not present in NPQ reg. When we bring them across we want to flag them as disabled so that they don't appear in other areas of the NPQ reg application.
- Migrate IttProvider and PrivateChildcareProvider
Providers are matched case insensitively. We can also fallback on the `operating_name` of the `IttProvider` if set.
| Main | This branch |
| -- | -- |
| <img width="1025" alt="Screenshot 2024-09-17 at 13 20 10" src="https://github.com/user-attachments/assets/d1d81b00-753b-4925-bb23-b24750732c39"> |  <img width="1005" alt="Screenshot 2024-09-17 …
=> Create IttProvider and PrivateChildcareProvider on migration

app/services/migration/migrators/user.rb, spec/services/migration/migrators/user_spec.rb
[Jira-3594](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3594)
We only want to raise an error for multiple verified `NPQApplication` TRNs if there is not a `teacher_profile.trn` on the ECF user. We will favour the profile TRN over the `NPQApplication` TRNs and fallback on the NPQ user TRN in case there is not a verified TRN in ECF (and the NPQ user already has one).
- Only raise on multiple application TRNs if no teacher profile TRN
=> Only raise on multiple application TRNs if no teacher profile TRN

app/views/registration_wizard/choose_your_provider.html.erb, app/views/registration_wizard/shared/_questions_page.html.erb, config/locales/en.yml, spec/features/journeys/happy_paths/basic_registration_journey_spec.rb
Add warning text to provider page as specified in the **prototype**:
How it's rendering **locally on the app**:
We discussed improving on the design, e.g. hint text outlining the exact dates, or removing the radios when that provider is no longer open, but [Nabi would like to get something out sooner rather than later](https://ukgovernmentdfe.slack.com/archives/C05A3H3ENRG/p1726664111768049).
=> Add warning message to the provider page

spec/factories/migration/ecf/participant_declarations.rb, spec/models/declaration_spec.rb, spec/models/participant_outcome_spec.rb, spec/services/declarations/create_spec.rb
A number of tests setup the `declaration_date` to be `1.day.ago`; this is usually fine as the `applies_from` of the schedule is the start of the month; but when we're on the first day of the next month it causes the date to be too early/before the `applies_from`.
As a workaround we can go back `1.hour` instead of `1.day`, so the date is on the 1st of the month and not the previous month.
This gets the tests passing; we may want to find a better solution as they would still fail when ran between 12-1am on the 1st of a month.
=> Fix failing specs due to declaration date

app/services/migration/migrators/application.rb, app/services/migration/migrators/application_state.rb, app/services/migration/migrators/base.rb, app/services/migration/migrators/declaration.rb, app/services/migration/migrators/participant_id_change.rb, app/services/migration/migrators/statement_item.rb, app/services/migration/migrators/user.rb, spec/features/migration_spec.rb, spec/services/migration/migrators/application_spec.rb, spec/services/migration/migrators/application_state_spec.rb, spec/services/migration/migrators/declaration_spec.rb, spec/services/migration/migrators/statement_item_spec.rb, spec/services/migration/migrators/user_spec.rb, spec/support/shared_examples/migrator_support.rb, terraform/application/config/migration.tfvars.json
[Jira-3511](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3511)
We want to utilise all available workers where possible by ensuring the records_per_worker split evenly across a multiple of the number of workers.
- Optimise records_per_worker
Also increases to 30 workers for better throughput.
Main:
```
[["application", "29 minutes and 25.89283599999999 seconds"],
["declaration", "4 minutes and 8.569072000000006 seconds"],
["statement_item", "2 minutes and 49.38589099999999 seconds"],
["user", "2 minutes and 21.038196 seconds"],
["contract", "1 minute and 59.136003 seconds"],
["application_state", "1 minute and 59.082032 seconds"],
["participant_outcome_api_request", "1 minute and …
```
=> Optimise records_per_worker

app/services/migration/migrators/application.rb
[Jira-3511](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3511)
Preload the matching applications in NPQ reg instead of finding on each iteration.
Main:
```
[["application", "29 minutes and 25.89283599999999 seconds"],
["declaration", "4 minutes and 8.569072000000006 seconds"],
["statement_item", "2 minutes and 49.38589099999999 seconds"],
["user", "2 minutes and 21.038196 seconds"],
["contract", "1 minute and 59.136003 seconds"],
["application_state", "1 minute and 59.082032 seconds"],
["participant_outcome_api_request", "1 minute and 9.245193999999998 seconds"],
["participant_outcome", "1 minute and 0.7751540000000006 seconds"],
["participant_id_change", "35.009366 seconds"], …
```
=> Optimise application lookup

spec/services/migration/migrators/schedule_spec.rb
The NPQ/ECF schedules factory dates happen to align today so that the test that checks the applies_from/to changes on migrating schedules is failing. Udpate to use relative dates so they will always be different/get updated during the test migration.
=> Fix failing schedule migrator test

.github/actions/refresh-migration-database/action.yml, .github/workflows/report-migration-results.yml, Makefile, app/jobs/crons/migration_job.rb, app/models/migration/data_migration.rb, config/environments/review.rb, config/environments/staging.rb, spec/jobs/crons/migration_job_spec.rb, spec/models/migration/data_migration_spec.rb
[Jira-3512](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3512)
We want to refresh the migration DB every night so that we can run the migration on a schedule.
- Refresh migration DB nightly
Refresh migration DB at midnight.
- Run migration nightly
We want to run the data migration on a nightly basis to monitor how it
performs/the results.
Run migration at 12:30am every morning; this is 30 minutes after the migration DBs are refreshed.
=> Run migration on a nightly schedule

.github/workflows/report-migration-results.yml
Enable manual testing of the action; needs to be in `main` before we can run it manually.
=> Add workflow_dispatch to migration report action

app/javascript/application.js, app/views/api/guidance/test.md, package.json, yarn.lock
The Mermaid diagrams are quite small and hard to read due to them being shrunk to fit the width of the page. We would like to be able to pan and zoom in the diagrams to make them easier to view.
- Add pan/zoom functionality to the Mermaid diagrams
Use the `svg-pan-zoom` node module to add pan/zoom controls to the Mermaid diagrams. We are using the default controls for now, but we could customise them if we wanted to in the future.
There is a [test page](https://npq-registration-review-1762-web.test.teacherservices.cloud/api/guidance/test) in the review app; I'll remove it prior to merging.
| Default | Zoomed in |
| -- | -- |
| <img width="752" alt="Screenshot 2024-10-02 at 11 00 25" src="https://github.com/user-attachments/assets/0849eecf-9e93-4a6f-88c7-86d821e99fed"> | <img width="791" …
=> Add pan/zoom functionality to Mermaid diagrams

app/services/migration/migrators/application.rb, spec/services/migration/migrators/application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3516
In the data migrators we currently raise an error if the NPQ user on application is different than the ECF user on application in the application migrator. However we have cases where transfers happened that have not been reflected in NPQ.
- amend the application migrator to set the user id to match the one in ecf
- remove the failure on application if the users are different between ecf and npq
=> [CPDLP-3516] Amend applications migrator to set the user id to match the one in ecf

app/serializers/api/participant_serializer.rb
The current accepted scope adds an n+1 to the API response for every participant as it generates a query. Instead add the check in the select body to avoid n+1s
Change accepted scope to a check in the select body
failures:
=> Change accepted scope to a check in the select body

app/models/user.rb, spec/models/user_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2128
Our code is currently overriding the user's data with their TRA record. When a user's TRN doesn't match a TRA record, we allow them to submit their application with the TRN they provided. However, this leads to the TRN being overwritten with a blank value.
We need to ensure the TRN is retained in such cases.
Modify the User methods `find_or_create_from_tra_data_on_unclaimed_email` and `find_or_create_from_tra_data_on_uid` to update the TRN only when a TRN is returned by TRA.
=> [CPDNPQ-2128] Keep the user TRN unchanged when TRA returns an empty TRN

app/services/declarations/query.rb, app/services/participant_outcomes/query.rb, app/services/participants/query.rb, app/services/statements/query.rb, spec/services/declarations/query_spec.rb, spec/services/participant_outcomes/query_spec.rb, spec/services/participants/query_spec.rb, spec/services/statements/query_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3608
* `Participants::Query` now by default sorts by `created_at`
* Adding `applications.accepted_at` to sorting forces query to return multiple `User` records as it has to join `Application`
* Added `distinct` to the query
* Added test to replicate the bug
=> [CPDLP-3608] Fix bug with duplicate records in NPQ

app/models/application.rb, app/models/user.rb, config/locales/en.yml, db/migrate/20230720141121_update_approved_itt_provider.rb, db/migrate/20241001144636_remove_default_from_ecf_id_in_contract_templates.rb, db/migrate/20241001200634_add_index_to_applications.rb, db/schema.rb, spec/lib/services/handle_submission_for_store_spec.rb, spec/models/application_spec.rb, spec/models/user_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3509
We would like to ensure that after separation, any new records created for the API in the db have a UUID which will be surfaced correctly.
- Ensure ecf id is populated for new applications and users after separation
- Ensure ecf id is required for applications and users after separation
- Fix migrations (db recreation was failing due a default scope added to IttProvider
- Remove default from contract templates db table
- Add missing index to application
=> [CPDLP-3509] Ensure ECF ID generation on all new records in NPQ

app/views/pages/closed_registration_exception.html.erb, app/views/registration_wizard/start.html.erb
The URL to request a trn contains a parameter which results in an infinite loop. Removing this parameter fixes the link
=> Removed parameter from trn service link

app/services/valid_test_data_generators/applications_populater.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3609
We were getting duplicates in pagination due to data having very similar created_at across all test data. This makes the test data more random
Add a random time to the schedule time selected
failures:
=> Amend test data generators to random created at

app/services/migration/migrators/application.rb, spec/services/migration/migrators/application_spec.rb
Ticket: [CPDLP-3496](https://dfedigital.atlassian.net/browse/CPDLP-3496)
We currently surface the `accepted_at` in the participant serialiser. We need to make sure this value is populated from old records as well with participant profiles.
When the application migrator runs, ensure that the `accepted_at` field is populated via the participant profile created at if the application is accepted.
[CPDLP-3496]: https://dfedigital.atlassian.net/browse/CPDLP-3496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3496] Populate `accepted_at` via application migrator

app/models/application.rb, app/views/accounts/_active_application_table.html.erb, app/views/accounts/_course_details.html.erb, spec/models/application_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3607
NPQ currently through an internal API to ECF gets outcomes for users to surface on the accounts pages. We would like to retain the same logic when internal APIs are turned off
- Currently `participant_outcome_state` is being updated via a scheduled job which will be disabled after separation.
- We have two services that creates outcomes, so do an application `participant_outcome_state` needs to be updated:
- When a new declaration is created and then an outcome is created.
- When a declaration is voided.
=> [CPDLP-3607] Add logic to recalculate `participant_outcome_state` after separation

app/views/pages/cookies.html.erb
Update cookie policy to:
- remove the hide-cookie-banner cookie as no longer in use
- remove the lines relating to the DfE Identity cookie policy and link there instead
- update the expiry date of the GA cookies
=> Update cookie policy

app/views/npq_separation/admin/applications/show.html.erb, spec/features/npq_separation/admin/applications_spec.rb
Ticket: [CPDNPQ-2147](https://dfedigital.atlassian.net/browse/CPDNPQ-2147)
We need to provide the same information in the post separation Admin console as is currently available in the ECF dashboard
* Extend the Application details screen with the additional fields currently only available on the ECF dashboard
* Extend the existing feature spec to cover the newly shown fields
[CPDNPQ-2147]: https://dfedigital.atlassian.net/browse/CPDNPQ-2147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2147] Add ECF fields to separated Admin/Applications#show

app/services/declarations/create.rb, app/services/participants/change_schedule.rb, app/validators/contract_for_cohort_and_course_validator.rb, config/locales/en.yml, spec/requests/api/docs/v1/declarations_spec.rb, spec/requests/api/docs/v1/participants_spec.rb, spec/requests/api/docs/v2/declarations_spec.rb, spec/requests/api/docs/v2/participants_spec.rb, spec/requests/api/docs/v3/declarations_spec.rb, spec/requests/api/docs/v3/participants_spec.rb, spec/services/declarations/create_spec.rb, spec/services/participants/change_schedule_spec.rb, spec/validators/contract_for_cohort_and_course_validator_spec.rb
Ticket: [CPDLP-3519](https://dfedigital.atlassian.net/browse/CPDLP-3519)
We want to add current contract logic in record declaration and change schedules.
Add contract for course validation to change schedule and declarations create services.
[CPDLP-3519]: https://dfedigital.atlassian.net/browse/CPDLP-3519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3519] Add contract for course validation to change schedule and declarations create services

.github/workflows/run_nightly_migration.yml
We don't do this in the MigratorJob as its ran on the button click from the UI.
=> Prepare migration before running

app/models/migration/ecf/api_token.rb, app/models/migration/ecf/lead_provider_api_token.rb, app/services/migration/parity_check/token_provider.rb, config/environments/development.rb, config/environments/migration.rb, config/environments/production.rb, config/environments/review.rb, config/environments/sandbox.rb, config/environments/separation.rb, config/environments/staging.rb, config/environments/test.rb, lib/abstract_interface.rb, spec/models/migration/ecf/lead_provider_api_token_spec.rb, spec/services/migration/parity_check/token_provider_spec.rb
[Jira-3614](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=unassigned%2C712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3614)
We are creating a service to check parity between the API responses of ECF and NPQ reg, once the data has been migrated. As part of this we will need to call the endpoints as lead providers, so we will need to be able to generate tokens for each lead provider in both ECF and NPQ reg.
- Add ECF models for ApiToken generation
Bring across the models from ECF that we need to be able to generate API tokens for ECF in NPQ registration.
I haven't improved the test coverage here, just a quick lift and shift from ECF.
- Add token generation service for ECF/NPQ
As part of the parity check we will need to generate …
=> Add token generation service for parity check

app/models/user.rb, spec/lib/services/get_an_identity_service/webhooks/user_updated_processor_spec.rb, spec/models/user_spec.rb
Email uniqueness validations were removed in https://github.com/DFE-Digital/npq-registration/pull/989
This was a quick fix to resolve errors from users trying to login with their Get an Identity accounts.
We now need to clean up the duplicate user records that have crept in since then and then re-add the validation. This will enable a smooth migration of data from ECF to NPQ. Work is currently underway to cleanup the data dn we can then add the validation when ready.
=> Readded email uniqueness validation

spec/services/statements/query_spec.rb
Ticket: N/A
This [spec](https://github.com/DFE-Digital/npq-registration/blob/main/spec/services/statements/query_spec.rb#L35) is failing due the same course potentially being selected for [L31](https://github.com/DFE-Digital/npq-registration/blob/main/spec/services/statements/query_spec.rb#L31) and [L32](https://github.com/DFE-Digital/npq-registration/blob/main/spec/services/statements/query_spec.rb#L32) resulting in a validation error being raised.
```
ActiveRecord::RecordInvalid:
Validation failed: Course Can only have one contract for statement and course
```
Make the course not dynamic in the lines mentioned above, so it fixes the flakey spec.
=> Fix `spec/services/statements/query_spec.rb` flakey test

db/seeds.rb
* `Flipper` feature flags need to be created before we run the seed stuff
=> Create all the Flipper flags before seed

app/models/declaration.rb, app/services/migration/migrators/declaration.rb, spec/models/declaration_spec.rb, spec/services/migration/migrators/declaration_spec.rb
Ticket: [CPDLP-3520](https://dfedigital.atlassian.net/browse/CPDLP-3520)
We have found old declarations that have invalid declaration dates in relation to the schedule start date. Those are legacy declarations in cohort 2021/2022 and will need to be taken away with contract managers, but we need to unblock migration so we should bring those across.
- Change the declaration migrator/model validation to allow pulling in declarations that have invalid schedules only. 
- Only allowed on data migration only and nowhere else.
[CPDLP-3520]: https://dfedigital.atlassian.net/browse/CPDLP-3520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3520] Disable declaration validation on schedule in migration only

app/services/migration/parity_check/token_provider.rb, spec/services/migration/parity_check/token_provider_spec.rb, spec/services/migration/parity_check_spec.rb
Fix typo in key name; its hyphens in the keyvault but they convert to underscores in the app.
=> Fix typo in key name for parity check tokens

app/components/npq_separation/admin/outcomes_table_component.rb, app/controllers/npq_separation/admin/participant_outcomes_controller.rb, app/models/participant_outcome.rb, config/locales/en.yml, config/routes.rb, spec/components/npq_separation/admin/outcomes_table_component_spec.rb, spec/factories/participant_outcomes.rb, spec/features/npq_separation/admin/applications_spec.rb, spec/models/participant_outcome_spec.rb, spec/requests/npq_separation/admin/participant_outcomes_controller_spec.rb
Ticket: [CPDNPQ-2152](https://dfedigital.atlassian.net/browse/CPDNPQ-2152)
We want to allow admin users to reschedule delivery of outcomes to the qualified teachers API
* Added logic for whether to allow rescheduling to the ParticipantOutcome model
* Added a method to `nil` out the relevant ParticipantOutcome attributes, which will trigger rescheduling
* Extended the ParticipantOutcomes component table to add a resend link
* Shortened some of the other columns in ParticipantOutcomes table to make space for the `Resend` link
* Added feature specs covering the above
* Refactored the existing method to determine whether an Outcome is the most recent to work with relationships instead of doing a query directly, this allows it to benefit from eager loaded data. The number of outcomes per …
=> [CPDNQT-2152] Resend outcome to api

app/services/migration/migrators/application.rb, spec/services/migration/migrators/application_spec.rb
Ticket: [CPDLP-3632](https://dfedigital.atlassian.net/browse/CPDLP-3632)
We are not checking if the school urn and school ukprn come from the same school in the migration.
Ensure that any value we pull in from ECF for school urn and school ukprn match the same school and should be aligned, otherwise raise a failure.
[CPDLP-3632]: https://dfedigital.atlassian.net/browse/CPDLP-3632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3632] Ensure school ukprn matches school urn in application migrator

app/controllers/npq_separation/migration/parity_checks_controller.rb, app/helpers/migration_helper.rb, app/models/migration/parity_check/response_comparison.rb, app/services/migration/parity_check.rb, app/services/migration/parity_check/client.rb, app/views/npq_separation/migration/parity_checks/_completed_parity_check.html.erb, app/views/npq_separation/migration/parity_checks/_multiple_comparisons_summary.html.erb, app/views/npq_separation/migration/parity_checks/_response_body_diff.html.erb, app/views/npq_separation/migration/parity_checks/_single_comparison_summary.html.erb, app/views/npq_separation/migration/parity_checks/response_comparison.html.erb, config/parity_check_endpoints.yml, db/migrate/20241021085312_add_page_to_response_comparisons.rb, db/schema.rb, spec/features/parity_check_spec.rb, spec/fixtures/files/parity_check/get_endpoints.yml, spec/helpers/migration_helper_spec.rb, spec/models/migration/parity_check/response_comparison_spec.rb, spec/requests/npq_separation/migration/parity_checks_controller_spec.rb, spec/services/migration/parity_check/client_spec.rb, spec/services/migration/parity_check_spec.rb
[Jira-3618](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3618)
We want to support pagination and filtering in the parity check service, so that we can compare the responses across multiple pages and with different query parameters.
- Add page attribute to ResponseComparison
We want to support pagination when calling certain endpoints as party of the parity check. To make it more managable, we're going to store the results of each page as a separate `ResponseComparison` instance.
Add `page` attribute to `ResponseComparison` model.
- Extract Client from ParityCheck service
To avoid overcomplicating the `ParityCheck` service, the request/response logic has been extracted …
=> Support pagination and filtering in parity check service

app/models/application.rb, app/models/user.rb, app/services/migration/migrators/application.rb, app/services/migration/migrators/cohort.rb, app/services/migration/migrators/participant_id_change.rb, app/services/migration/migrators/schedule.rb, app/services/migration/migrators/statement.rb, app/services/migration/migrators/user.rb, db/migrate/20241023112339_change_object_type_to_json_for_versions.rb, db/migrate/20241023113236_add_note_to_versions.rb, db/schema.rb, spec/models/application_spec.rb, spec/models/user_spec.rb, spec/services/migration/migrators/application_spec.rb, spec/services/migration/migrators/cohort_spec.rb, spec/services/migration/migrators/participant_id_change_spec.rb, spec/services/migration/migrators/schedule_spec.rb, spec/services/migration/migrators/statement_spec.rb, spec/services/migration/migrators/user_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3631
* `Cohort`, `Schedule`, `ParticipantIdChange` and `Statement` migrations will use timestamps from ECF
* Updated `paper_trail`
* `object` field type is now `json`
* `object_changes` added
* added `note` field
* `Application` & `User`
* Can now include `version_note` which adds `versions.note` entry into `versions`
* Migration will use ECF timestamps and include a `version_note`
* If there has been any changes from ECF attrs, we set `updated_at` to `Time.zone.now`
=> [CPDLP-3631] Ensure we migrate all relevant timestamps from ECF

.github/workflows/deploy.yml
When we branch off another branch the CI doesn't run; it would be better if it did so we get failures flagged before we rebase with `main`.
=> Run CI on all branches

Makefile
We are pointing to cpd ecf when we should npq registration in konduit make command
Amend make command to point to npq registration web app instead.
copy paste innit, thanks @jebw for the good spot!
=> Update konduit make commands to point to correct web app

.github/workflows/deploy.yml
Ticket: BAU
Currently CI is running on all branch pushes, including running for the push to `gh-read-only/*` branches used by the merge queue
Merge Queues are also re-running the same pipelines
I don't think we need to run for all branches, only for all pull requests - this would still give us the ability to stack PRs
1) Revert to only running branch pushes to main
2) Run pull request merges irrespective of the branch they are merging into
failures:
=> Run CI on all PRs but not all branch pushes

app/controllers/npq_separation/migration/parity_checks_controller.rb, app/helpers/migration_helper.rb, app/models/migration/parity_check/response_comparison.rb, app/views/npq_separation/migration/parity_checks/_multiple_comparisons_summary.html.erb, app/views/npq_separation/migration/parity_checks/response_comparison.html.erb, db/migrate/20241024142323_add_ecf_npq_ids_to_response_comparison.rb, db/schema.rb, spec/features/parity_check_spec.rb, spec/helpers/migration_helper_spec.rb, spec/models/migration/parity_check/response_comparison_spec.rb
[Jira-3525](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3525)
- Add ecf/npq response body ids to ResponseComparison
We want to perform additional checks on the response IDs regardless of if the comparison was successful or not. We want to check for duplicate/mismatched ids across all requests for a comparison.
Add `ecf_response_body_ids` and `npq_response_body_ids` to `ResponseComparison`.
- Add duplicate/matching ID checks to overview page
When we return multiple results we want to check that the IDs in the results are consistent between ECF and NPQ reg and that there are no duplicate IDs returned.
Fix pluralisation bug in overview page title.
Always use multiple …
=> Surface duplicates in parity check

app/services/migration/migrators/application.rb, app/services/migration/migrators/user.rb, spec/services/migration/migrators/application_spec.rb, spec/services/migration/migrators/user_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3638
* `Application`
* Backfill for `ecf_id`
* Backfill for `cohort_id`
* Backfill for `lead_provider_approval_status `
* `User`
* Backfill for `ecf_id`
=> [CPDLP-3638] Add backfill for ecf_ids and data in migration

app/services/migration/migrators/statement_item.rb, spec/services/migration/migrators/course_spec.rb, spec/services/migration/migrators/declaration_spec.rb, spec/services/migration/migrators/statement_item_spec.rb, spec/services/migration/migrators/statement_spec.rb, spec/services/migration/migrators/user_spec.rb
Ticket: [CPDLP-3674](https://dfedigital.atlassian.net/browse/CPDLP-3674)
The declarations `updated_at` timestamps is being changed in migrations when it shouldn’t be.
The `attributes` method returns a hash which keys are string, not symbol.. so it was not setting `statement_items` timestamps correctly in the statement item migrator, causing the [declarations serializer updated_at](https://github.com/DFE-Digital/npq-registration/blob/main/app/serializers/api/declaration_serializer.rb#L41) to return the wrong value.
```
User.last.attributes.slice(:id) => {}
User.last.attributes.slice("id") => {"id"=>216}
```
[CPDLP-3674]: https://dfedigital.atlassian.net/browse/CPDLP-3674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3674] Fix attributes slice syntax

app/controllers/npq_separation/migration/parity_checks_controller.rb, app/helpers/migration_helper.rb, app/models/migration/parity_check/response_comparison.rb, app/services/migration/parity_check/client.rb, app/views/npq_separation/migration/parity_checks/_completed_parity_check.html.erb, app/views/npq_separation/migration/parity_checks/response_comparison.html.erb, config/parity_check_endpoints.yml, spec/factories/migration/parity_check/response_comparisons.rb, spec/features/parity_check_spec.rb, spec/fixtures/files/parity_check/post_endpoints.yml, spec/fixtures/files/parity_check/put_endpoints.yml, spec/helpers/migration_helper_spec.rb, spec/models/migration/parity_check/response_comparison_spec.rb, spec/services/migration/parity_check/client_spec.rb, spec/services/migration/parity_check_spec.rb
We want to add POST and PUT endpoints to the parity check tool to ensure the responses and behaviour of the API is consistent between ECF and NPQ reg.
- Add POST endpoints to parity check
Support `post` requests in the parity check tool. In order to do this we expand the `Client` to support POST requests and allow specifying a `payload` in the YAML for a path. This can either be a hash, which will be sent as the request body or it can be a method name that can construct a dynamic payload.
- Add PUT endpoints to parity check
Support `put` requests in the parity check tool. In order to do this we expand the `Client` to support PUT requests and add specific use cases to the YAML file/client.
- Memoize request body
To avoid issues with dynamic payloads and ensure both the NPQ and ECF requests …
=> Add POST/PUT endpoint support to parity check

app/components/banners/maintenance_component.html.erb, app/components/banners/maintenance_component.rb, app/controllers/maintenance_banners_controller.rb, app/helpers/banner_helper.rb, app/services/feature.rb, app/views/layouts/api_docs.html.erb, app/views/layouts/api_guidance.html.erb, app/views/layouts/application.html.erb, app/views/layouts/shared/_maintenance_banner.html.erb, config/routes.rb, spec/components/banners/maintenance_component_spec.rb, spec/features/maintenance_banner_spec.rb, spec/helpers/banner_helper_spec.rb, spec/requests/maintenance_banner_spec.rb, spec/services/feature_spec.rb
When we migrate the lead provider API to NPQ reg we will have downtime; we want to be able to inform our users of this ahead of time.
- Add maintenance banner
Add a maintenance banner that we can use to alert users of upcoming downtime.
This is ported from ECF.
| Application layout | Guidance layout | API docs layout |
| -- | -- | -- |
| <img width="1485" alt="Screenshot 2024-10-30 at 10 07 08" src="https://github.com/user-attachments/assets/a0f66ee2-9b0e-4698-adf2-1e167afbc346"> | <img width="1485" alt="Screenshot 2024-10-30 at 10 08 59" src="https://github.com/user-attachments/assets/553c37c2-8f8c-41ad-a432-51fdecea1e18"> | <img width="1485" alt="Screenshot 2024-10-30 at 10 09 58" src="https://github.com/user-attachments/assets/89969a5c-bb67-4fa9-88d8-8c4755a87372"> |
=> Add maintenance banner

spec/requests/maintenance_banner_spec.rb
Sometimes this test takes longer than 1s to run; making it 5s should give it enough wiggle room.
=> Fix flakey banner dismiss spec

app/jobs/migration_job.rb, app/jobs/migrator_job.rb, app/jobs/parity_check_job.rb, config/initializers/delayed_job.rb, spec/jobs/migration_job_spec.rb, spec/jobs/migrator_job_spec.rb, spec/jobs/parity_check_job_spec.rb, terraform/application/application.tf, terraform/application/config/migration.tfvars.json, terraform/application/config/production.tfvars.json, terraform/application/variables.tf
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3518
* Migration jobs will use `migration` queue
* Existing worker runs the following queues: `default,low_priority,participant_outcomes`
* New migration worker runs `migration` queue only
=> [CPDLP-3518] Add migration queue only worker to NPQ

app/models/user.rb, app/services/migration/users/creator.rb, spec/features/migration_spec.rb, spec/models/user_spec.rb, spec/services/migration/migrators/user_spec.rb, spec/services/migration/users/creator_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3675
- Adds a unique validation to the ecf_id field in the user model. This field should be unique. 
- Remove validation for ecf id in user migrator as it is no longer needed
The user data is being cleaned up in advance of this PR. A unique constraint at the DB level will be added in a subsequent PR.
failures:
=> [CPDLP-3675] Added rails validation to ecf_id in user model

app/models/statement_item.rb, app/serializers/api/declaration_serializer.rb, app/services/declarations/query.rb, spec/models/statement_item_spec.rb, spec/serializers/api/declaration_serializer_spec.rb, spec/services/declarations/query_spec.rb
Ticket: [CPDLP-3695](https://dfedigital.atlassian.net/browse/CPDLP-3695)
We currently use statement line items in the updated at on declaration serialiser to surface changes to statements linked to declarations. However after running the parity check we see the updated at all pulling in from when a statement item was marked as payable then paid. We only want to see a change if declarations were moved from one statement to another.
- If statements are updated (not on creation) on a statement line item, touch the declaration it’s attached to
- Remove statement items from the serialiser and query in updated since for declarations
[CPDLP-3695]: https://dfedigital.atlassian.net/browse/CPDLP-3695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3695] Touch declaration if statement is changed on a statement item

terraform/application/config/migration.tfvars.json
Ticket: [CPDLP-3606](https://dfedigital.atlassian.net/browse/CPDLP-3606)
Currently, the NPQ migration DB tier is not the same as in ECF. 
Align migration DB tier with ECF.
Note: Manually to be deployed to migration before merging this PR down.
[CPDLP-3606]: https://dfedigital.atlassian.net/browse/CPDLP-3606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3606] Upgrade postgres db tier in migration env

app/serializers/api/declaration_serializer.rb, app/services/declarations/query.rb, app/services/participant_outcomes/create.rb, spec/serializers/api/declaration_serializer_spec.rb, spec/services/declarations/query_spec.rb, spec/services/participant_outcomes/create_spec.rb
Ticket: [CPDLP-3711](https://dfedigital.atlassian.net/browse/CPDLP-3711)
We currently use outcomes in the updated at on the declaration serialiser to surface changes to has passed calculated from outcomes. However, after running the parity check we see the updated at changed on all declarations with an outcome which we are trying to minimise for providers
- Touch the declaration if an outcome is created via the POST outcomes endpoint;
- Remove outcomes from the serialiser and query in updated since for declarations;
[CPDLP-3711]: https://dfedigital.atlassian.net/browse/CPDLP-3711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3711] Touch declaration if new outcome added

app/services/migration/migrators/declaration_superseded_by.rb, spec/services/migration/migrators/declaration_superseded_by_spec.rb
Ticket: [CPDLP-3712](https://dfedigital.atlassian.net/browse/CPDLP-3712)
The declaration superseded by migrator is updating the updated at timestamp on the declaration when setting the superseded declaration id.
- Do not touch the declaration timestamp on `DeclarationSupersededBy` migrator.
[CPDLP-3712]: https://dfedigital.atlassian.net/browse/CPDLP-3712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3712] Do not touch the declaration timestamp on DeclarationSupersededBy migrator

.github/actions/deploy-environment-to-aks/action.yml, .github/actions/smoke-test/action.yml, bin/smoke
Ticket: [CPDNPQ-2170](https://dfedigital.atlassian.net/browse/CPDNPQ-2170)
Current the application does not run smoke tests during deployment - the healthchecks are tested as part of the AKS deployment module but only that they respond with success. This does additional checks such as ensuring the migrations have completed correctly
1. Added a `bin/smoke` program to smoke test the new application
2. Added a github action to run the `bin/smoke` program to perform the smoke tests
3. Integrated the github action in (2) with the deploy_to_aks action so that smoke tests occur during deployment into all environments
failures:
[CPDNPQ-2170]: …
=> [CPDNPQ-2170] Run smoke test during deployment

app/models/application.rb, app/services/migration/migrators/application.rb, spec/models/application_spec.rb, spec/services/migration/migrators/application_spec.rb
The parity check tool is flagging that some user `updated_at` values are unexpected/changed. We want to find out why and make them consistent with ECF.
- Skip user touch during migration when application changes
When an application changes and the `lead_provider_approval_status` is updated we are touching the user `updated_at`. We don't want to do this during the migration as it is causing user timestamps to change and differences in the parity check.
Add `skip_touch_user_if_changed` attribute to `Application` and set it to `true` for the migration `update!` call.
Tested on migration environment:
Before:
```
Migration::Ecf::NpqApplication.find("92464289-adc1-4d6c-a012-96da00a1d779").user.updated_at
=> Mon, 13 Feb 2023 16:06:38.148051000 UTC +00:00
Application.find_by(ecf_id: …
```
=> Fix user timestamps not always updating

app/models/application.rb, app/serializers/api/application_serializer.rb, app/serializers/api/applications_csv_serializer.rb, app/services/migration/migrators/application.rb, spec/models/application_spec.rb, spec/serializers/api/application_serializer_spec.rb, spec/serializers/api/applications_csv_serializer_spec.rb, spec/services/migration/migrators/application_spec.rb
[Jira-3713](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3713)
We are finding that some ITT providers and private childcare providers are coming back as `nil` in the API response where they should be populated (as they are in ECF).
We also want to ensure that the `updated_at` of the application in NPQ reg is set to the current date if there is a provider in NPQ reg but not in ECF, so that the change in data will be surfaced to lead providers.
- Ensure disabled providers are included in serializers
We have a default scope on the providers that omits disabled providers by default. This is causing the providers to be `nil` in the serializers, but the tests are passing as the scope is bypassed due to the providers being preloaded in the …
=> Fix bug with providers not populating in serializers

app/services/migration/migrators/application.rb, app/services/migration/migrators/base.rb, app/services/migration/migrators/user.rb, spec/services/migration/migrators/application_spec.rb, spec/services/migration/migrators/user_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3716
* Application migrator
* Set `updated_at` if `trn` has changed
* User migrator
* Set `updated_at` if email changed from `npq_application.participant_identity.email` and `npq_application.profile.participant_identity.email`
* Set `updated_at` if `trn_verified` changed.
=> [CPDLP-3716] Parity check - Change updated at setting in User migrator

bin/smoke
Ticket: [2170](https://dfedigital.atlassian.net/browse/CPDNPQ-2170)
Our deployments are not rolling rather than blue/green, this means there is a window when we may get a response from the old application. Ideally terraform wouldn't complete before the old apps had drained but that appears not to be the case so the check against the deployed version occasionally receives a response from the old app.
1. Re-add the check against the deployed version
2. Add a `sleep` to delay checking the healthcheck endpoint to allow time for old apps to drain
failures:
=> [CPDNPQ-2170] Re-add the git sha check and include a sleep

app/services/applications/query.rb
Ticket: n/a
When changing associations in application serialiser we forgot to add the new ones to the query
Amend includes to include the disabled private childcare provider and itt provider
failures:
=> Remove n+1 in application query by including correct associations

config/environments/review.rb, config/environments/sandbox.rb, config/environments/separation.rb, config/environments/staging.rb
Ticket: N/A
Some Non prod env inherits `cache_store` from production. We need to set it back as `null_store`.
Fix `cache_store` back to `null_store` for non prod envs.
=> Fix cache_store for non prod envs

terraform/application/config/review.tfvars.json
Ticket: [2209](https://dfedigital.atlassian.net/browse/CPDNPQ-2209)
Reduce boot time in review apps
Only load the rails environment once to configure the db, load the schema and load the seeds.
Since the application is slow to boot due to bigquery gems - this should reduce doing the same reloading from 4 times to 2 times
failures:
=> [CPDNPQ-2209] Avoid repeatedly reloading rails app during boot

app/components/npq_separation/admin/statement_details_component.rb, app/controllers/npq_separation/admin/finance/statements_controller.rb, app/models/statement.rb, app/views/npq_separation/admin/finance/statements/show.html.erb, config/locales/en.yml, spec/components/npq_separation/admin/statement_details_component_spec.rb, spec/factories/statements.rb, spec/features/npq_separation/admin/finance/statements_spec.rb, spec/models/statement_spec.rb
Ticket: [CPDNPQ-2142](https://dfedigital.atlassian.net/browse/CPDNPQ-2142)
The payment authorisation functionality is already present in the code base but is relying on a stubbed out calculator and is not connected to the statements screen.
1. Show a button linking to the payment authorisations form from the statement summary screen
2. Use the new `Statements::SummaryCalculator` for the Payment Authorisations Form
3. Show a persistent flash message to say payment authorisation is in progress when a statement has a paid date set but is not yet transitioned to a paid state
4. Show an inline tag message to show when a payment happened once a statement has transitioned to a paid state
failures: …
=> [CPDNPQ-2142] Integration with CPDNPQ-2141

bin/smoke
This is failing on prs even with the sleep added, removing until properly fixed to unblock team
Ticket: n/a
Remove sha check from smoke test
failures:
=> Remove sha check until it's fixed

app/services/migration/migrators/application.rb, spec/services/migration/migrators/application_spec.rb
Ticket: [CPDLP-3758](https://dfedigital.atlassian.net/browse/CPDLP-3758)
Currently when checking that the school urn changed in the migrator for applications we aren’t checking if the profile exists, this means we might always trigger updates for unaccepted applications
Change the school urn updated at logic to check that a profile exists before comparing equality.
[CPDLP-3758]: https://dfedigital.atlassian.net/browse/CPDLP-3758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3758] Check that a profile exists before touching `updated_at`on Application migrator

app/services/dqt/v1/teacher.rb, spec/services/dqt/v1/teacher_spec.rb
Add logging so that we can monitor that these requests are happening and completing successfully when we switch them on in production.
=> Add logging for DQT API requests

app/services/migration/migrators/application.rb, app/services/migration/migrators/base.rb, app/services/migration/migrators/user.rb, spec/services/migration/migrators/application_spec.rb
[Jira-3759](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3759)
We have noticed some application cohorts are being overwritten to the default/fallback cohort. This is due to the timing/ordering of the `run_once` code in the application migrator.
- Fix race condition with run_once
There is a potential race condition in `run_once` migrator logic whereby if the `run_once` depends on data modified as part of the migration it might happen too early.
To avoid this, we can change the behaviour so the single-run code goes at the end and is ran by the last worker to complete. This way it ensures the migration for the model has fully completed before executing.
After running the migration:
```
Migration::Ecf::NpqApplication.find("fe026f85-1e68-453c-a191-e419a0b47982").cohort.start_year
=> …
```
=> Fix race condition with `run_once`

db/seeds.rb, lib/tasks/courses.rake, terraform/application/config/review.tfvars.json
[Jira-3767](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3767)
The review apps have become increasingly flakey, often failing to deploy for either timeouts or seed failures. We want to fix this to make them more reliable.
- Prevent double-seeding the review apps
We currently run `db:seed` when the container boots and then immediately run a `db:seed:replant` in the following github action step. This can cause the healthcheck to fail as the courses are purged until the replant re-adds them. It results in the review app deploy being flakey.
Use existing rake task to seed courses on container boot (which will be fast and allow the healthcheck to pass) and then run a …
=> Prevent double-seeding the review apps

app/services/migration/migrators/user.rb, spec/factories/users.rb, spec/lib/services/get_an_identity_service/webhooks/user_updated_processor_spec.rb, spec/models/registration_wizard_spec.rb, spec/services/migration/migrators/user_spec.rb
[Jira-3763](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3763)
We have a number of placeholder TRNs in the ECF dataset; we want to ensure when we migrate these that they are always in an unverified state.
- Ensure placeholder TRNs are unverified
Checked on migration:
```
User.where(trn: %w[0000000 1234567], trn_verified: true).exists?
=> false
```
=> Ensure placeholder TRNs are unverified

bin/smoke
We reverted #1905 due to seeing failures in the review app deployments (see #1973). We think these failures were caused by other flakiness/issues with the pipeline, so we want to re-instate the SHA check.
- Re-instate SHA check on deploy
Re-instate the SHA check on deploy that was removed in case it was causing flakiness; we were seeing failures on the SHA check, but they appear to be related to other issues with the pipeline.
Check the correct SHA is deployed, once per second for a maximum of 10 seconds (to give time for the old pods to drain and new pods to spin up).
=> Re-instate SHA check on deploy

app/models/declaration.rb, app/models/statement.rb, config/locales/en.yml, spec/models/declaration_spec.rb, spec/models/statement_spec.rb, spec/services/statements/mark_as_paid_spec.rb, spec/services/statements/mark_as_payable_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3766
* Removed max statement items validation from Statement
* Added max statement items validation to Declaration
* Added multiple declarations to mark as payable/paid service specs.
=> [CPDLP-3766] Fix validation on statements not be limit to 2 statement items

app/models/release_notes.rb, app/views/api/guidance/index.html.erb, spec/models/release_notes_spec.rb
[Jira-3745](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3745)
We want to update the latest release note formatting so that it's more user friendly.
- Update latest release note formatting
Split date into new paragraph above release note text and link directly to the full release note. Only display the first paragraph of the release note under "What's new".
[Link to latest release note](https://npq-registration-review-1985-web.test.teacherservices.cloud/api/guidance)
=> Update latest release note formatting

app/models/lead_provider.rb, db/migrate/20241112131533_update_ucl_provider_name.rb, db/schema.rb, db/seeds/base/add_api_tokens.rb, db/seeds/separation_shared_data.yml, spec/lib/questionnaires/choose_your_provider_spec.rb, spec/models/lead_provider_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2197
The UCL provider name is different between ECF and NPQ - it needs to be the same
Changing `University College London (UCL) Institute of Education` to `UCL Institute of Education` everywhere in the code,
and migrating the Lead Provider names too
=> [CPDNPQ-2197] update UCL provider name

app/models/application.rb, config/analytics.yml, config/analytics_blocklist.yml, config/initializers/dfe_analytics.rb, spec/models/application_spec.rb, spec/requests/dfe_analytics_spec.rb
Adds `senco_in_role`, `senco_in_role_status`, `senco_start_date`, `trn` to analytics from `raw_application_data`.
=> Add some fields from raw application data to analytics

.github/workflows/refresh_migration_database.yml, .github/workflows/run_nightly_migration.yml
We are kicking off a parity check and want to see the results in the morning.
Disable nightly migration to avoid wiping the results.
=> Disable nightly migration

Gemfile, Gemfile.lock, app/services/migration/coordinator.rb, app/services/migration/migrators/base.rb, spec/features/migration_spec.rb, spec/services/migration/coordinator_spec.rb
[Jira-3785](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=unassigned%2C712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3785)
We occasionally find that the migration run stalls part way through; there are no job failures but also no active/in-progress jobs, which suggests there is a race condition around the logic for queueing the next set of workers. This seems to have become more prominent since we added the `run_once_post_migration` functionality.
- Fix migration race condition
I believe the race condition occurs around how we check for the last worker and then updated the `completed_at` for the current worker; if the last two workers perform the check at the same time it could result in both of them believing they are not the …
=> Fix migration race condition

app/models/user.rb, app/serializers/api/application_serializer.rb, app/serializers/api/participant_serializer.rb, app/services/applications/query.rb, app/services/migration/migrators/user.rb, app/services/participants/query.rb, config/analytics.yml, db/migrate/20241119074851_add_significantly_updated_at_to_users.rb, db/migrate/20241122155145_backfill_significantly_updated_at.rb, db/schema.rb, spec/factories/users.rb, spec/lib/services/handle_submission_for_store_spec.rb, spec/models/user_spec.rb, spec/serializers/api/application_serializer_spec.rb, spec/serializers/api/participant_serializer_spec.rb, spec/services/applications/query_spec.rb, spec/services/migration/migrators/user_spec.rb, spec/services/participants/query_spec.rb, spec/support/helpers/journey_helper.rb
[Jira-3747](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=unassigned%2C712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3747)
At the moment, we use the `User#updated_at` to surface changes to lead providers via the API. The issue with this is that actions/changes that lead providers don't care about result in the user being marked as 'updated'. Instead, we want to have an additional `updated_at` attribute that we can use to surface the changes lead providers care about to the underlying `User` model.
- Add significantly_udpated_at attribute to User 
We have an `updated_at` on the `User` model, however this is updated frequently and for actions that lead providers don't need to care about (such as when a user signs in).
We want to …
=> Add `significantly_updated_at` attribute to `User`

app/services/participants/query.rb, spec/services/participants/query_spec.rb
[Jira-3803](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3803)
When filtering participants on `training_status` we were still returning all `applications` in the resulting relationship of each `User`. To be consistent with ECF we want to only return the applications that match the `training_status` we are filtering to.
- Fix `Participants::Query` filtering on `training_status`
Fix filtering by `training_status` to only return matching applications in the resulting participants.
Add test to verify that filtering by `from_participant_id` behaves in the same way; we only want participant id changes that match the filter to be in the results.
=> Fix `Participants::Query` filtering on `training_status`

app/services/participants/query.rb, spec/services/participants/query_spec.rb
[Jira-3798](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3798)
When we filter on `includes` with ActiveRecord the included table is filtered down to the records that match the conditional. For the `Participants::Query` this means when filtering by `updated_since` the related applications/id
changes are filtered as well as the base users. Instead, we want the users to be filtered but retain all the applications and id changes in the preloaded association.
- Fix bug in filtering in `Participants::Query`
To achieve this we can instead use a subquery to find the applications/id changes updated within the timeframe and filter on the selected `user_id` of those.
This will …
=> Fix bug in filtering in `Participants::Query`

app/services/handle_submission_for_store.rb, spec/features/journeys/happy_paths/when_get_an_identity_returns_no_trn_spec.rb, spec/lib/services/handle_submission_for_store_spec.rb
Adds
* `senco_in_role`
* `senco_start_date`
* `on_submission_trn`
to the application when its saved.
=> Add extra fields to db when saving an application

app/views/npq_separation/admin/finance/statements/show.html.erb, spec/features/npq_separation/admin/finance/statements_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2289
Currently the ECF ID for a statement is not shown in the Statement details page within the NPQ admin screen but needs to be since this is the 'external' ID lead providers will be aware of
1. Added the ECF ID to the details summer list
failures:
=> [CPDNPQ-2289] Show ECF ID on statement details admin page

app/models/statement.rb, spec/models/lead_provider_spec.rb, spec/models/statement_spec.rb
We shouldn't be attaching declarations to payable/paid statements even if they match other criteria
Ticket: n/a
Change scope to only look for "open" statements as the next output fee statements
failures:
=> Only attach declarations to open statements

app/models/release_notes.rb, app/views/api/guidance/index.html.erb, app/views/api/guidance/release-notes.md, spec/models/release_notes_spec.rb
⚠️ This is blocked until we perform separation in production ECF/NPQ
Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3530
Add release note for NPQ separation. 
This will be merged on the 27th of November after separation is complete and successful in ECF/NPQ
=> [CPDLP-3530] Add NPQ separation release note

config/initializers/rack_attack.rb, spec/requests/rate_limiting_spec.rb
[Jira-3806](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3806)
We had a catch-all/generic rate limit that was set to 300 requests/5 minutes. This is lower than all of our other throttles in RackAttack and was causing API requests to be throttled incorrectly.
Instead, we want to add an additional throttle for non-API requests at 300 requests/minute and a catch all/backstop throttle that will ensure no request to the service will exceed 1500 requests/5 minutes.
=> Fix rate limiting

app/services/one_off/bulk_change_applications_to_pending.rb, lib/tasks/bulk_change_applications_to_pending.rake, spec/lib/tasks/one_off/bulk_change_applications_to_pending_spec.rb, spec/services/one_off/bulk_change_applications_to_pending_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2270
bulk script for revert to pending - rake file and service ported from ECF - updated to work with the NPQ `Applications::RevertToPending` service.
=> [CPDNPQ-2270] port rake file and service from ECF (bulk script for revert to pending)

Dockerfile, app/models/application_record.rb, config/database.yml
As we only have a single database connection again we can drop the `primary` clarification from the rake tasks and the database configuration.
=> Remove references to `primary` database

Dockerfile, Gemfile, Gemfile.lock
Ticket: N/A
There was only one job being scheduled via `whenever` gem, which got removed as it was linked to ECF.
The other jobs use `delayed_cron_job` instead.
Remove whenever gem.
=> Remove whenever gem

.github/workflows/deploy.yml
Ahead of removing the environment to prevent other deploys causing issues while we tear down the environment.
=> Disable deployment to separation

README.md, app/models/course.rb, docs/funding.md, spec/models/course_spec.rb
We want to document the behaviour around funding/capping as since we introduced `funded_place` there is a fair amount going on when dealing with applications, declarations and eligibility.
- Document funding/capping behaviour
Add documenbtation for funding to detail how application funding, eligibility and capping behaviour works both pre and post 2024 when the `funded_place` attribute was added.
- Clean up rebranded_alternative_courses
I found the switch statement confusing and it makes the behaviour seem more complicated than it actually is.
If the course is a 'rebranded alternative' course return all possible courses otherwise just return the current course.
=> Document funnding/capping behaviour

app/controllers/npq_separation/admin/users/change_trn_controller.rb, app/forms/questionnaires/qualified_teacher_check.rb, app/services/participants/change_trn.rb, app/services/teacher_reference_number.rb, app/validators/valid_trn_validator.rb, app/views/npq_separation/admin/users/change_trn/show.html.erb, app/views/npq_separation/admin/users/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/npq_separation/admin/users_spec.rb, spec/lib/questionnaires/qualified_teacher_check_spec.rb, spec/services/dqt/record_check_spec.rb, spec/services/participants/change_trn_spec.rb, spec/services/teacher_reference_number_spec.rb, spec/validators/valid_trn_validator_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2178
Allow admin users to change a participant's TRN
- add ability to change TRN from separation admin participant page, including new `Participants::ChangeTrn` service
- add specs to cover existing TRN validation fully
- move common validation for TRN into new validator
- remove unused code from `TeacherReferenceNumber` service, to make it clear the validation there was never used
- change length validation from separate min and max to a single length check (this changes the error messages too)
- update `trn_verified` to true when the TRN is updated
change link:
error case:
=> [CPDNPQ-2178] admin change TRN

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Ticket: [CPDNPQ-2357](https://dfedigital.atlassian.net/browse/CPDNPQ-2357)
We want the user to need to go via the email to login
1. Prevent showing the OTP code on staging
[CPDNPQ-2357]: https://dfedigital.atlassian.net/browse/CPDNPQ-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2357] Make staging auth operate like production

spec/components/npq_separation/admin/course_payment_overview_component_spec.rb, spec/features/npq_separation/admin/finance/statement_spec.rb, spec/models/lead_provider_spec.rb, spec/requests/api/docs/v1/applications_spec.rb, spec/requests/api/docs/v2/applications_spec.rb, spec/requests/api/docs/v3/applications_spec.rb, spec/services/valid_test_data_generators/statements_populater_spec.rb
After the 25th of December we have failing specs due to schedules
After certain dates the schedules change for courses. Create both courses to avoid failures at certain times in the year.
I avoided the `with_default_schedules` setup as it does not amend dates to stop declaration failures which is needed in those specs.
For the valid test data, there is a date in the service itself we have to travel to, travel to it in the specs.
failures:
=> Fix schedule spec failures due to date changes

Makefile, terraform/domains/environment_domains/config/production.tfvars.json, terraform/domains/environment_domains/config/production_Terrafile, terraform/domains/environment_domains/config/sandbox.tfvars.json, terraform/domains/environment_domains/config/staging.tfvars.json, terraform/domains/environment_domains/main.tf, terraform/domains/infrastructure/config/zones_Terrafile
Ticket: https://trello.com/c/5jCq2a3p
Add front door environments for pen testers and external users
Depends on https://github.com/DFE-Digital/terraform-modules/pull/139
- Configure staging and sandbox environment
- Delete references to terrafile
- Delete old records
Domains are ready:
- https://x.register-national-professional-qualifications.education.gov.uk/
- https://t.register-national-professional-qualifications.education.gov.uk/
- Wait for https://github.com/DFE-Digital/terraform-modules/pull/139 to be relase to stable (check with infra)
- Remove TEMP commit
=> [2158] Staging and sandbox front door domains

spec/services/participants/change_schedule_spec.rb
spec failing because it's now 2025
change cohort in spec to `Date.current.year + 1` because it still uses the fallback_cohort.
=> fix failing spec

config/initializers/sentry.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2335
enable sentry on staging and review environments.
we already have the environment variable `SENTRY_DSN` set for staging and review apps.
This PR needs to be merged before I can create the alert in sentry for staging (sentry needs at least one error from that environment for it to appear in the alert settings dropdown).
=> [CPDNPQ-2335] enable sentry on staging and review environments

docs/connecting-to-azure.md
doc describing how to connect to azure - idea and format stolen from my last team (claim).
=> connecting to azure doc

Makefile, docs/connecting-to-azure.md
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2442
Currently the default `Makefile` commands will run consoles on the web nodes which can impact a running web request if the console usage triggers an out of memory scenario.
A secondary concern is the console command by default provides read-write and in production this will often only need to be read-only for investigation purposes
1. Run all commands from worker nodes instead
2. Provide an alternative to ssh into a web node
3. Changed the default `aks-console` to use rails' `--sandbox` parameter
4. Added a new `aks-rw-console` command to run without the `--sandbox` parameter
=> [CPDNPQ-2442] Default to running rails console from workers

app/controllers/concerns/api/pagination.rb, config/initializers/pagy.rb, db/migrate/20250103111630_add_indexes.rb, db/schema.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2395
requests to `/api/v3/participants/npq?page_size=3000&updated_since=2020-01-01` are too slow (~800ms)
* switch to [pagy_countless](https://ddnexus.github.io/pagy/docs/extras/countless/) (saves 200-300ms)
* add index to applications lead_provider_approval_status (saves ~100ms)
* add index to users created_at (saves ~200ms)
Tested using a production data dump, using lead provider _Ambition Institute_, which has ~46,000 users.
before optimisation: page load ~800ms
after optimisation: page load ~150ms
=> [CPDNPQ-2395] improve participants API load times

lib/tasks/one_off/move_declarations_for_2023_cohort.rake
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2418
new rake task.
Originally I had a call to `OneOff::MigrateDeclarationsBetweenStatements` to move June 2025 to Feb 2025, but it turns out there are no declarations for the June 2025 statements,
so now I just have the Jan 2025 to Feb 2025 move.
=> [CPDNPQ-2418] rake task for moving declarations for 2023 cohort

app/services/users/merge_and_archive.rb, lib/tasks/merge_user_into_another.rake, spec/lib/tasks/merge_user_into_another_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2314
The `merge_user_into_another` rake task isn't outputting what it is doing, which makes the dry run not very useful.
Add logging
=> [CPDNPQ-2314] log what Users::MergeAndArchive is doing

app/services/course_groups/leadership.rb, app/services/course_groups/specialist.rb, spec/services/course_groups/leadership_spec.rb, spec/services/course_groups/specialist_spec.rb
Ticket: [CPDNPQ-2461](https://dfedigital.atlassian.net/browse/CPDNPQ-2461)
Currently lead providers are unable to accept applications because our schedule calculation does not return any schedule for today for Leadership and Specialist courses
1. The `CourseGroup::Leadership` calculator is updated to special case the extended autumn 2024 schedule
2. The `CourseGroup::Specialist` calculator is updated to special case the extended autumn 2024 schedule
[CPDNPQ-2461]: https://dfedigital.atlassian.net/browse/CPDNPQ-2461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CPDNPQ-2461 fix schedule calculations

db/seeds.rb
When running `db:migrate db:seed`, we need to reload column information.
=> Fix seeds when run together with migration

app/controllers/npq_separation/admin/applications_controller.rb, app/views/npq_separation/admin/applications/show.html.erb, spec/features/npq_separation/admin/applications_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2455
show links to the statements linked to each declaration in the application show page
e.g.
=> [CPDNPQ-2455] show links to statements

.github/workflows/backup_production_database.yml, .github/workflows/deploy.yml, .github/workflows/destroy_review_app.yml, .github/workflows/lead_provider_openapi_check.yml, .github/workflows/maintenance.yml, .github/workflows/restore_azure_database.yml, .github/workflows/rspec.yml
Ticket: [CPDNPQ-2397](https://dfedigital.atlassian.net/browse/CPDNPQ-2397)
We are getting warnings in GitHub actions because we use `ubuntu-latest` for our runners and this is going to change the image it corresponds to to 24.04 soon
1. Explicitly use `ubuntu-24.04` to verify that our pipelines work with 24.04 and optionally merge to silence warnings
[CPDNPQ-2397]: https://dfedigital.atlassian.net/browse/CPDNPQ-2397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2397] Switched to using ubuntu-24.04 in CI

app/models/declaration.rb, spec/models/declaration_spec.rb
`declaration_date` does not need to be validated when is not being changed.
https://dfedigital.atlassian.net/browse/CPDNPQ-2432
=> Validate declaration_date only when its changed

app/jobs/crons/batch_send_latest_outcomes_job.rb, app/jobs/crons/generate_dashboard_report_job.rb, app/jobs/crons/sweep_stale_sessions_job.rb, app/jobs/crons/update_schools_job.rb, app/jobs/dashboard_report_job.rb, app/jobs/sweep_stale_sessions_job.rb, config/initializers/delayed_job.rb, spec/jobs/crons/batch_send_latest_outcomes_job_spec.rb, spec/jobs/crons/generate_dashboard_report_job_spec.rb, spec/jobs/crons/sweep_stale_sessions_job_spec.rb, spec/jobs/crons/update_schools_job_spec.rb
Ticket: [CPDNPQ-2421](https://dfedigital.atlassian.net/browse/CPDNPQ-2421)
It has been observed when cron jobs fail, eg API flakiness or bugs, the Jobs run away with themselves. Our sandbox environment is currently attempting to synchronise with GIAS every few minutes rather than once per day as scheduled.
This is caused by a combination of factors
1. Cron Jobs _should_ simply rescedule for the next point they are meant to run
2. Default retry behaviour is to allow for a job to run for 4 hours and retry 25 times - a theoretical max compute cost of 104 hours for every scheduled job!
3. Retry backoff is quite slow, this leads to failing jobs being processed sooner but at a cost of higher job retries if we want an adequate time window to address failing jobs
4. We are scheduling regular jobs …
=> [CPDNPQ-2421] Prevent run-away cron jobs

app/services/applications/revert_to_pending.rb, config/locales/en.yml, spec/services/applications/revert_to_pending_spec.rb, spec/services/bulk_operation/bulk_change_applications_to_pending_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2317
When there are voided statement items and a voided declaration, it is currently not possible to revert an application to pending.
It raises an error in the admin console:
```
ActiveRecord::InvalidForeignKey in NpqSeparation::Admin::Applications::RevertToPendingController#create`
PG::ForeignKeyViolation: ERROR: update or delete on table "declarations" violates foreign key constraint "fk_rails_19a5cbebb5" on table "statement_items"
DETAIL: Key (id)=(1278) is still referenced from table "statement_items".
```
* Change the validation, so that only applications with declaration in revertable states(`voided`, `ineligible`, `awaiting_clawback`, `clawed_back`) can be reverted to pending
* Do not delete any declarations
* If there are …
=> [CPDNPQ-2317] change validation and do not destroy declarations

spec/features/npq_separation/admin/creating_statements_spec.rb
Ticket: BAU
Specs are consistently failing on `main`, they were not earlier today - I think this is because we're only allowing 0.1 seconds to download the file and CI is more heavily loaded later in the day.
1. I cannot see an obvious way of blocking on the download, so instead I'm just checking in a loop for up to 5 seconds for the file to download
=> Allow for slow file downloads in CI

app/controllers/application_controller.rb, spec/requests/npq_separation/admin_controller_spec.rb
Ticket: [CPDNPQ-2508](https://dfedigital.atlassian.net/browse/CPDNPQ-2508)
To ensure users do not get logged out in the middle of the day we are changing the logout time to always be midnight
1. Change from logging out after 12 hours to logging out at midnight
[CPDNPQ-2508]: https://dfedigital.atlassian.net/browse/CPDNPQ-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2508] Change to always log users out at midnight

app/views/accounts/user_registrations/show.html.erb, spec/support/helpers/journey_assertion_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2490
Added _Application ID_ on the registration success page:
=> [CPDNPQ-2490] show Application ID on registration success page

spec/factories/statements.rb
Ticket: BAU
We are getting regular failures from flaky specs when trying to deploy out to production
The origin of this is we no longer allow duplicate statements, and due to randomness in the statement period combined with a pool of only 48 possible periods, occasionally a spec which generates 2 statements will generate 2 for the same period.
1. Iterate the periods instead within the pool of 48
=> BAU - Fix flaky statements factory

app/jobs/send_application_submission_email_job.rb, app/mailers/application_submission_mailer.rb, spec/jobs/send_application_submission_email_job_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2511
`ecf_id` is referenced in the gov.uk notify template, but is not set in the mailer.
add `ecf_id` to `ApplicationSubmissionMailer#application_submitted_mail`
=> [CPDNPQ-2511] add ecf_id to application_submitted_mail

app/services/import_gias_schools.rb, spec/factories/schools.rb, spec/fixtures/files/invalid_csv_header.csv, spec/services/import_gias_schools_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2433
If the `ImportGiasSchools` is run on a local development environment, it will fail because 766 out of 1766 of the seeded schools have null `last_changed_date`.
This change to the factory that is used by the seeds fixes that, so it is more like production.
For sandbox and staging, there are a number of seeded schools with null `last_changed_date` - for this the `ImportGiasSchools` will now cope with that.
Set the `last_changed_date` to 1/1/2010 for all schools created using a factory.
Cope with a null `last_changed_date` in `ImportGiasSchools`
⚠️ do not merge until CPDNPQ-2421 is merged ⚠️
=> [CPDNPQ-2433] fix ImportGiasSchools

app/models/financial_change_log.rb, app/services/one_off/create_or_update_statements.rb, spec/services/one_off/create_or_update_statements_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2520
deadline date and payment date need to be updated on a couple of statements
Update the `OneOff::CreateOrUpdateStatements` used by the `one_off:create_or_update_statements` rake task so that it updates the deadline date and payment date.
=> [CPDNPQ-2520] allow deadline_date and payment_date to be updated

db/seeds/base/add_applications.rb, spec/factories/application_states.rb, spec/factories/applications.rb, spec/factories/cohorts.rb, spec/factories/courses.rb, spec/factories/participant_outcomes.rb, spec/factories/schools.rb, spec/factories/statements.rb, spec/factories/users.rb, spec/features/npq_separation/admin/users_spec.rb, spec/models/lead_provider_spec.rb, spec/requests/api/v3/statements_spec.rb, spec/services/assurance_reports/query_spec.rb, spec/services/statements/query_spec.rb, spec/services/statements/summary_calculator_spec.rb
Ticket: [CPDNPQ-2466](https://dfedigital.atlassian.net/browse/CPDNPQ-2466)
We are making these change because our deploys are frequently failing and its holding up the team
1. Use of non-deterministic values in factories has been removed
2. Removed a factory trait which was causing flaky specs because the traits behaviour is now matched by the default behaviour
[CPDNPQ-2466]: https://dfedigital.atlassian.net/browse/CPDNPQ-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2466] Replace use of non-deterministic data in factories

config/initializers/rack_attack.rb
Ticket: BAU
Currently with a limit of 5 attempts in 1 minute its not possible to mistype an OTP code and then login on the second attempt.
1. Change form 5 page loads under `/session` in 1 minute to 10 page loads in 2 minutes
This should allow for a real user to retry with rate limiting still taking effect at the same point
=> [BAU] - allow for failed login attempts

app/models/statement_item.rb, app/services/declarations/void.rb, docs/state_machines.md, spec/models/statement_item_spec.rb, spec/services/declarations/void_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2517
void ineligible statement_items when voiding a declaration - previously only eligible and payable statement_items were voided.
=> [CPDNPQ-2517] void ineligible statement_items when voiding a declaration

lib/tasks/api_token.rake, lib/tasks/merge_user_into_another.rake, lib/tasks/one_off/create_contract.rake, lib/tasks/one_off/load_legacy_participant_outcomes.rake, lib/tasks/one_off/move_declarations_for_2023_cohort.rake, lib/tasks/one_off/move_declarations_from_dec24_to_jan25.rake, lib/tasks/update_application.rake, lib/tasks/update_declaration.rake, spec/lib/tasks/merge_user_into_another_spec.rb
Ticket: BAU
Various rake tasks are logging to stdout in specs - this isn't strictly necessary and complicates the spec output
1. Use the regular rails logger when the tasks are running in the Rails test environment
=> [BAU] Silence logger noise in specs

app/controllers/session_wizard_controller.rb, app/models/session_wizard.rb, config/initializers/exceptions.rb, config/initializers/sentry.rb, spec/controllers/session_wizard_controller_spec.rb
Ticket: [2361](https://dfedigital.atlassian.net/browse/CPDNPQ-2361)
Visits to invalid URLs under `/session` path trigger an error instead of a 404. Whilst harmless this is creating noise for us in the errors channel and risks distracting from 'real' errors. The fix is a trivial change
1. Rescue the invalid step and treat it as a page not found
=> CPDNPQ-2361 Handle invalid session steps

Gemfile, app/controllers/npq_separation/admin/lead_providers_controller.rb, config/environments/review.rb, config/environments/test.rb
Ticket: BAU
We want to know when our pages are not optimised automated testing (ie the `test` environment) and manual testing during production review (ie `review` environment) are our best options
1. Remove 'ignores' from bullet in test environment
2. Enable bullet and make it hard fail in review environment
3. Fix an N+1 which was discovered as part of this
=> Enable bullet in test+review and fix N+1

app/views/registration_wizard/dont_have_teacher_reference_number.html.erb, app/views/registration_wizard/dqt_mismatch.html.erb, app/views/registration_wizard/start.html.erb, app/views/registration_wizard/teacher_reference_number.html.erb
Ticket: [CPDNPQ-2590](https://dfedigital.atlassian.net/browse/CPDNPQ-2590)
The link now requires an access token to be accessed
1. The link used in various screens
[CPDNPQ-2590]: https://dfedigital.atlassian.net/browse/CPDNPQ-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2590] Update request a TRN link

docs/acquiring_new_private_childcare_provider_data.md, docs/importing_data.md
In the `Acquiring new Private Childcare Provider CSV data for import` doc:
the link in the table of contents was wrong
also, the links to the importer classes didn't work.
=> fix childcare provider import doc

app/views/registration_wizard/shared/_additional_info.html.erb, spec/requests/rate_limiting_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2602
we show a link to a `change-dqt` step, which does not exist
Change link to point to Dfe Identity - where they can change their name.
Also, remove the last paragraph, which has a link to a non-existent `not-sure-updated-name` step.
=> [CPDNPQ-2602] remove link to non-existent step

app/models/lead_provider.rb, app/services/lead_providers/updater.rb, db/migrate/20221130142333_add_hint_to_lead_providers.rb, db/seeds/base/add_api_tokens.rb, lib/tasks/lead_providers.rake, spec/features/journeys/happy_paths/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb, spec/forms/questionnaires/choose_your_provider_spec.rb, spec/models/lead_provider_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2625
TDT have stopped offering NPQs
remove Teacher Development Trust from all the provider course lists.
=> [CPDNPQ-2625] remove lead provider Teacher Development Trust from all courses

app/models/declaration.rb, app/services/declarations/create.rb, config/locales/en.yml, spec/models/declaration_spec.rb, spec/services/declarations/create_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2369
Creating a declaration via the API with an invalid `declaration_type` causes a 500 error
The issue is that a query that uses an invalid `declaration_type` will raise the error:
`ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input value for enum declaration_types`.
This is happening in `Declarations::Create#existing_declaration` which is used in the `output_fee_statement_available` validation.
Rather than catching the `ActiveRecord::StatementInvalid` error, I think it's cleaner to just add an inclusion validation on the `Declarations::Create` service.
The validation added to the Declaration model won't be used in this scenario, but I've added it for thoroughness.
=> [CPDNPQ-2369] validate declaration_type at both model and service layer

app/controllers/npq_separation/admin/applications/change_lead_provider_controller.rb, app/models/course.rb, app/services/applications/change_lead_provider.rb, app/views/npq_separation/admin/applications/change_lead_provider/show.html.erb, app/views/npq_separation/admin/applications/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/npq_separation/admin/applications_spec.rb, spec/services/applications/change_lead_provider_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2480
* a new link next to the Lead Provider name: 'Transfer'
* a page showing all Lead Providers
* validation to ensure a LP is selected
I've used a `show` page instead of a `new` page - our admin pages seem to mostly use `new`.
Advantages of using 'show' instead of 'new'
* the URL is better I think: `/admin/applications/:id/change_lead_provider`
* the controller doesn't need an empty `def new; end` method
* if using 'new', and there's an error on the page, then user ends up on the show page anyway, which if they reload, causes an error. Using 'show' avoids this.
example page:
=> [CPDNPQ-2480] Admin console - change lead provider

app/models/user.rb, spec/factories/users.rb, spec/models/user_spec.rb
Ticket: [CPDNPQ-2645](https://dfedigital.atlassian.net/browse/CPDNPQ-2645)
There was a prior change to avoid updating a users TRN on login if their TRN was blank in DfE Identity (#1782). Unfortunately it is still resetting the users trn_verified status back to unverified.
1. Refactored specs to allow extension
2. Changed User to only set `trn`+`trn_verified`+`trn_lookup_status` if the user is has TRN information in DfE Identity
[CPDNPQ-2645]: https://dfedigital.atlassian.net/browse/CPDNPQ-2645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2645] Stop unverifying users

lib/tasks/one_off/backfill_trn_verified_status.rake, spec/lib/tasks/one_off/backfill_trn_verified_status_spec.rb
Ticket: [CPDNPQ-2645](https://dfedigital.atlassian.net/browse/CPDNPQ-2645)
We have a subset of users who have incorrectly have their TRN flagged as unverified. This happened because when the user logs in via DfE Identity, their `trn_verified` field and `trn_lookup_status` are always updated according to whether DfE Identity holds a TRN for the user.
Their TRN is _not_ updated if DfE Identity does not hold a TRN for the user.
This leads to a situation where users who have gone down the DQT path are left with their TRN set, but having had that marked as verified, any subsequent login will mark it back as unverified.
This provides a script to identify these users and correct their `trn_verified` status
1. It finds users who have `trn_auto_verified` set to `true` (so they went down the DQT …
=> [CPDNPQ-2645] Rake task to correct unverified users

app/services/declarations/create.rb, config/locales/en.yml, spec/services/declarations/create_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2632
There was already a `validate_schedule_exists` validation, but it wasn't being run, because the cohort validation was raising an error first.
Just reordering the validations fixes this.
Also, it wasn't actually checking if the schedule exists, but rather if the declaration type was allowed - so I've split the validation into two separate validations.
=> [CPDNPQ-2632] ensure validate_schedule_exists is run before the cohort validation

app/forms/session_wizard_steps/base.rb, app/forms/session_wizard_steps/sign_in.rb, app/forms/session_wizard_steps/sign_in_code.rb, app/models/session_wizard.rb, config/locales/en.yml, spec/forms/session_wizard_steps/sign_in_code_spec.rb, spec/forms/session_wizard_steps/sign_in_spec.rb
Ticket: [CPDNPQ-2546](https://dfedigital.atlassian.net/browse/CPDNPQ-2546)
This is a separate wizard, UI components are separate and having them grouped together is confusing
1. Separate out the SessionWizard steps
[CPDNPQ-2546]: https://dfedigital.atlassian.net/browse/CPDNPQ-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2546] Separate out the wizard session steps

Gemfile, Gemfile.lock, config/initializers/strong_migrations.rb, db/seeds/base/add_applications.rb, terraform/application/config/review.tfvars.json
Ticket: [CPDNPQ-2366](https://dfedigital.atlassian.net/browse/CPDNPQ-2366)
Migrations are one of the few ways to make a change to a site which cannot just be resolved by a revert, potentially resulting in down time. Improving our resilience to mistakes in migration files helps avoid unintended problems.
1. Strong migrations gem has been added to protect against dangerous migrations
2. Review apps are changed to run through the migrations instead of just loading `db/schema` whilst this is slow it is more likely to catch problems and on an empty database only adds a few seconds to the deploy time so seems like a good trade-off.
[CPDNPQ-2366]: https://dfedigital.atlassian.net/browse/CPDNPQ-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CPDNPQ-2366 Improve migration robustness

app/services/declarations/query.rb, app/services/queries/condition_formats.rb, docs/swagger.md, package.json, public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/requests/api/docs/v3/statements_spec.rb, spec/services/applications/query_spec.rb, spec/services/declarations/query_spec.rb, spec/services/queries/condition_formats_spec.rb, spec/support/shared_examples/api_index_endpoint_documentation_support.rb, spec/support/shared_examples/api_index_endpoint_support.rb, spec/swagger_schemas/concerns/sorting.rb, spec/swagger_schemas/filters/pagination.rb, yarn.lock
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2368
Using an invalid UUID in the filter param for declarations, raises an error.
The other APIs cope with an invalid UUID fine (no error raised).
I've added a `uuids` option to the `extract_conditions` method - which if true will remove invalid UUIDs from the conditions.
I don't think we need additional validation - especially because you can pass (for example) multiple participant_ids - so if only one is invalid, it is better to just return values for the IDs that _are_ valid, rather than raising an error for the one that is not valid.
Whilst investigating this, I noticed our 'try it out' feature on the swagger docs was not working, because the filter, page and sort parameters were not quite described correctly - I've fixed that in …
=> [CPDNPQ-2368] stop invalid UUID reaching query object

app/models/user.rb, app/services/users/archiver.rb, spec/features/journeys/sad_paths/dfe_sign_in_spec.rb, spec/services/users/archiver_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2647
When logging in, users that have been archived are being found and used (because they have a UID that matches the one of the user logging in)
* do not use an archived user
* before saving the new user using the DfE Identity data, blank the UID of the clashing archived user - there is a uniqueness constraint on UID that will fail otherwise.
=> [CPDNPQ-2647] do not use archived users when logging in

Makefile
Using konduit (e.g. `make konduit-snapshot`) puts the database URL with the wrong indentation in our `config/database.yml`.
This is because the primary database was removed in https://github.com/DFE-Digital/npq-registration/pull/2055, the indentation changed, but the Makefile was not updated.
Fix the indentation, so the URL is put in the right place.
=> fix konduit

app/forms/questionnaires/course_start_date.rb, app/forms/questionnaires/dqt_mismatch.rb, app/forms/questionnaires/qualified_teacher_check.rb, spec/features/journeys/sad_paths/session_expires_before_qualified_teacher_check_spec.rb, spec/forms/questionnaires/qualified_teacher_check_spec.rb, spec/support/api_responses.rb, spec/support/helpers/journey_helper.rb, spec/support/shared_examples/forms_questionnaires_support.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2638
If the user's session expires, or does not exist, and the page they have in their browser is the qualfied_teacher_check page - then submitting this form causes an error.
The `after_save` on this step, and also the `next_step` on the next step (course_start_date) rely on having a current_user.
In the expired/non-existent session scenario, that user is a `NullUser`.
The fix is:
* cope with NullUser in the qualfied_teacher_check step
* check if the user is is not a NullUser before the `dqt_mismatch` and `course_start_date` steps (either of which could follow the qualfied_teacher_check step) , and redirect them to the start of the journey if it is a NullUser
=> [CPDNPQ-2638] cope with expired/non-existent session on qualified_teacher_check step

app/controllers/npq_separation/admin/applications/reviews_controller.rb, app/services/admin_service/applications_search.rb, db/seeds/base/add_applications.rb, spec/features/npq_separation/admin/applications_in_review_spec.rb
Addresses task 3 on this ticket:
https://dfedigital.atlassian.net/browse/CPDNPQ-2618
In this PR:
- Reverse the sort order of applications on the 'Registrations in review' page in the admin console, so that the most recent application displays first.
- Edit the test data with unique timestamps, and add a new test scenario, so that the new order can be tested. 
New order displays most recent application first:
=> Reverse sort direction - registrations in review - admin console

app/controllers/omniauth_controller.rb, app/models/user.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2688
There are a couple of errors appearing in sentry - for one of them, I can't be sure how we're getting to that point.
errors we're seeing:
- Email address must be unique - last seen: Mar 9, 2025 1:56:55 PM
- uid has already been taken - last seen: Feb 14, 2025 4:43:59 PM - this was resolved by CPDNPQ-2647
I've tried a few scenarios, but cannot get to a point where we hit the errors we're seeing.
Adding extra info to the sentry error
=> [CPDNPQ-2688] add extra info to sentry error

spec/rails_helper.rb
we recently moved to cuprite - here are a couple of tweaks to the config
- Remove a leftover reference to selenium. I've checked, and screenshots and HTML are saved when there's a feature test error
- Increase default max wait time - I've seen a couple of flaky tests - this may help
=> feature test tweaks

app/controllers/errors_controller.rb, spec/features/content_security_policy_spec.rb, spec/requests/api/errors_spec.rb, spec/support/shared_contexts/render_errors.rb, spec/support/shared_examples/api_index_endpoint_support.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2463
The Not Found page always returned HTML
We don't actually return formats based on the Content-Type header,
we always return JSON from API endpoints.
So now, the errors controller will check the request URL, and if it is API, it will return JSON.
Only the Not Found page was actually incorrectly returning HTML - the other responses were already correct (401, 422, 500).
=> [CPDNPQ-2463] ensure errors are JSON for API requests

app/controllers/omniauth_controller.rb
The last change to add additional info to the sentry error causes this error:
https://dfe-teacher-services.sentry.io/issues/6413570401/?project=5817541&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20omniauth_controller&referrer=issue-stream&sort=date&stream_index=0
Change the additional information to be a hash
=> sentry context needs to be a hash

app/services/course_groups/leadership.rb, app/services/course_groups/specialist.rb, spec/services/course_groups/leadership_spec.rb, spec/services/course_groups/specialist_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2692
we need the autumn 2024 schedule to be until 6/6/25 to allow providers to accept late registration Autumn 2024 applications.
autumn 2024 schedule now ends 6/6/25
=> [CPDNPQ-2692] extend autumn 2024 schedule to 6/6/25

app/models/declaration.rb, app/models/delivery_partner.rb, app/models/delivery_partnership.rb, app/models/lead_provider.rb, app/services/feature.rb, config/analytics.yml, config/locales/en.yml, db/migrate/20250210145412_create_delivery_partners.rb, db/schema.rb, spec/factories/delivery_partners.rb, spec/factories/delivery_partnerships.rb, spec/factories/lead_providers.rb, spec/models/declaration_spec.rb, spec/models/delivery_partner_spec.rb, spec/models/delivery_partnership_spec.rb, spec/models/lead_provider_spec.rb, spec/services/feature_spec.rb
Ticket: [CPDNPQ-2448])(https://dfedigital.atlassian.net/browse/CPDNPQ-2448)
Add a data model for managing delivery partners
1. Added DeliveryPartners model
2. Added DeliveryPartnership join model between LeadProviders, Cohorts, and DeliveryPartners
3. Added Primary and Secondary delivery partners to declarations
Not quite finished yet - needs the checking for delivery_partner_id on Declaration to take account of whether is post 2024 cohort but sufficient for initial review now
[CPDNPQ-2448]: https://dfedigital.atlassian.net/browse/CPDNPQ-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2448] Add delivery partners data model

app/controllers/api/v3/delivery_partners_controller.rb, app/models/cohort.rb, app/models/delivery_partner.rb, app/serializers/api/delivery_partner_serializer.rb, app/services/delivery_partners/query.rb, config/routes.rb, db/seeds.rb, db/seeds/base/add_delivery_partners.rb, spec/models/cohort_spec.rb, spec/models/delivery_partner_spec.rb, spec/requests/api/v3/delivery_partners_spec.rb, spec/serializers/api/delivery_partner_serializer_spec.rb, spec/services/applications/query_spec.rb, spec/services/delivery_partners/query_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2451
* controller
* delivery partners service
* query object
* serializer
* `DeliveryPartner#cohorts_for_lead_provider` method
* index API supports filtering by cohort and sorting
When querying for delivery partners, the query is joining two `has_many through:` tables.
Rails makes 2 SQL queries - one for the delivery partners, and one for the cohorts.
I couldn't figure out a way to make that a single query - so the serializer calls `DeliveryPartner#cohorts_for_lead_provider`
=> [CPDNPQ-2451] delivery partner API index and show

app/controllers/api/v3/declarations_controller.rb, app/models/declaration.rb, app/services/declarations/create.rb, config/locales/en.yml, spec/models/declaration_spec.rb, spec/requests/api/v3/declarations_spec.rb, spec/services/declarations/create_spec.rb, spec/support/matchers/error_matcher.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2453
Allow `delivery_partner_id` and `secondary_delivery_partner_id` to be specified when creating a declaration.
Call the validations for delivery partners from the `Declaration` model directly.
Update the validation error messages on the Declaration model, so they are public-facing API error messages.
Allow two new attributes: `delivery_partner_id`, `secondary_delivery_partner_id`.
=> [CPDNPQ-2453] set delivery partners on declarations

Gemfile, Gemfile.lock
Ticket: BAU
We are currently using bye-bug and pry but byebug is superceded by the ruby debugging library and IRB has improved sufficiently to reduce the value of PRY.
1. Replace the PRY and byebug dependencies with a dependency on ruby's built in debugging library. We're using the gem version to ensure we benefit from the latest release without being on the latest ruby release
=> [BAU] Drop byebug and pry

.github/workflows/build_flow_visualisation.yml, .github/workflows/restore_snapshot_database.yml
Ticket: BAU
Visualisation step has failed because of GH Actions ubuntu 20.04 brownout. We shouldn't be using version 20.04
1. Use Ubuntu 24.04
=> [BAU] Fix visualisation github action not to use ancient ubuntu release

app/models/declaration.rb, spec/factories/declarations.rb, spec/models/declaration_spec.rb
Ticket: [CPDNPQ-2730](https://dfedigital.atlassian.net/browse/CPDNPQ-2730)
Currently you cannot update the state on a declaration which was made without a delivery partner once the feature flag is enabled. 
1. Only check the presence of the delivery_partner field if creating a new record or the field has actually been changed
[CPDNPQ-2730]: https://dfedigital.atlassian.net/browse/CPDNPQ-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2730] Avoid checking dp_id for existing declarations

app/controllers/admin/features_controller.rb, app/models/user.rb, app/views/admin/features/index.html.erb, app/views/admin/features/show.html.erb, config/locales/en.yml, spec/models/user_spec.rb, spec/support/shared_contexts/with_activerecord_flipper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2747
In the new feature flags section, we are currently trying to show how many actors (i.e. users) are feature-flagged for different features:
However, this does not work in an intuitive way.
Every time a feature-flagged user signs in to the NPQ service, they’re recorded as another actor - making it seem like there are more actors than there are. 
What’s more, the actors section is only relevant for the Registration Open feature flag - so it’s confusing to have the actors section for all flags. 
We want to prevent confusion by removing the actors information from these pages.
Instead, we can link users to the ‘Closed registration users’ page, which is a better source of truth to understand who is feature flagged.
**User story**
As a …
=> 2747 - remove users sections from feature flags index and show pages

app/models/lead_provider.rb, spec/models/lead_provider_spec.rb
ActiveRecord's where clause is doing the join automatically, by adding a manual `join`, it ends up aliased and so unconstrained
It doesn't actually cause incorrect records to be included but does cause duplicate entries in the returned results
Ticket: [CPDNPQ-2789](https://dfedigital.atlassian.net/browse/CPDNPQ-2789)
The length of the `#available_delivery_partners` list on a declaration ends up as the product of the number of partnerships for that declarations lead provider and cohort, multiplied by the total number of partnerships.
These are all repeat entries so wont allow incorrect declarations but may slow down the application if its loading lots of records. (eg number of cohorts * number of lead providers * number delivery partners * partnerships for particular cohort)
1. Remove the …
=> [CPDNPQ-2789] Fix join triggering duplicate delivery partners in list

app/models/declaration.rb, config/locales/en.yml, spec/models/declaration_spec.rb
Ticket: [CPDNPQ-2731](https://dfedigital.atlassian.net/browse/CPDNPQ-2731)
Overseas applications will not have a delivery partner, so once a delivery partner is required then declarations would be prevented.
1. Allow declarations from overseas without delivery_partner_id
2. Actually prevent declarations from overseas with a delivery_partner_id as this would imply an incorrect declaration
[CPDNPQ-2731]: https://dfedigital.atlassian.net/browse/CPDNPQ-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2731] Allow overseas declarations

app/services/declarations/create.rb, config/locales/en.yml, spec/services/declarations/create_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2788
currently, if an ID is specified that refers to a non-existent delivery partner, no error is raised, the delivery partner is just set to nil.
Add validation to check there is a delivery partner for the specified ID
=> [CPDNPQ-2788] add validation to check the delivery partners exist

app/constraints/has_flipper_access.rb, app/models/admin.rb, app/models/null_user.rb, app/views/admin/_layout.html.erb, config/locales/en.yml, config/routes.rb, spec/features/admin_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2768
We have a new section of the admin console for turning feature flags on and off. This was intended to replace the Flipper panel provided by Flipper. 
Remove the Flipper panel and remove the link to it from the nav bar, as well as associated methods/code. 
See acceptance criteria on the ticket ⬆️
=> Remove the Flipper features panel

app/services/applications/accept.rb, app/services/course_groups/ehco.rb, app/services/course_groups/leadership.rb, app/services/course_groups/specialist.rb, config/locales/en.yml, spec/services/applications/accept_spec.rb, spec/support/shared_examples/course_group_schedule_support.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2800
lead providers accepting an application from the 2023 cohort will end up with a nil schedule
* added a TODO to remove schedule_date from these classes - it is never set to anything other than `Date.current`, which is confusing, as it implies it could be set to something else.
* for applications in the 2024 and 2025 cohorts, it will pick the one schedule we have for each of those cohorts
* for applications in 2023 and earlier cohorts, the default date ranges will be used to pick spring or autumn cohorts
* for applications after 6/6/25 - the same default date ranges will be used
* add validation on `Applications::Accept` so that if in the future, our code fails to determine a schedule, then the accept will fail.
* send a message to …
=> [CPDNPQ-2800] cope with late acceptance from 2023 and earlier cohorts

app/controllers/api/v3/declarations_controller.rb, app/services/declarations/change_delivery_partner.rb, config/locales/en.yml, config/routes.rb, spec/requests/api/v3/declarations_spec.rb, spec/services/declarations/change_delivery_partner_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2749
Allow delivery_partner_id and secondary_delivery_partner_id to changed using its own api endpoint: `/api/v3/participant-declarations/{id}/change-delivery-partner`
Call the validations for delivery partners from the Declaration model. When either `delivery_partner` or `secondary_delivery_partner` does not exist, use the `The entered '#/delivery_partner_id' is not from your list of confirmed Delivery Partners for the Cohort` error method for convinience - end user need to use designated delivery partner.
The api endpoint allows to remove `secondary_delivery_partner` from declaration.
=> Api endpoint to change declaration delivery partner.

lib/tasks/api_token.rake, spec/lib/tasks/api_token_spec.rb
Ticket: [CPDNPQ-2776](https://dfedigital.atlassian.net/browse/CPDNPQ-2776)
We want a simple CLI tool for generating API tokens for the lead providers which also reminds explains appropriate mechanisms for transferring api tokens.
1. Added a rake task for generating API tokens
[CPDNPQ-2776]: https://dfedigital.atlassian.net/browse/CPDNPQ-2776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2776] Added rake task to generate API Tokens

.editorconfig, terraform/application/application.tf
Ticket: [CPDNPQ-2460](https://dfedigital.atlassian.net/browse/CPDNPQ-2460)
Currently Delayed::Job will sleep for a 5 second delay in between polling for new jobs. If it receives a signal to exit, it will continue to sleep until the sleep duration has passed only then does it exit.
This leads to a scenario in review apps where the worker application continues sleeping whilst the postgres container gets destroyed. I'd initially tried marking the worker app as explicitly depending upon postgres _but_ k8s reports back to terraform as having removed an application before the container has actually exited so that doesn't solve the problem.
1. The worker container explicitly depends upon postgres, via a 'wait' resource
2. The wait resource, a 15 second delay, is introduced between worker removal …
=> [CPDNPQ-2460] Delay removal of postgres on review app teardown

app/views/pages/closed_registration_exception.html.erb, app/views/registration_closed/show.html.erb, spec/features/service_closed_spec.rb
Ticket: [CPDNPQ-2804](https://dfedigital.atlassian.net/browse/CPDNPQ-2804)
We want to improve clarity of content for our users
1. Content on 'start late registration' screen
2. Content on home page when registration is closed
[CPDNPQ-2804]: https://dfedigital.atlassian.net/browse/CPDNPQ-2804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2804] registration screen changes

app/helpers/application_helper.rb, app/views/layouts/shared/_head.html.erb, app/views/shared/analytics/_tracking_pixels.html.erb, config/application.rb, spec/helpers/application_helper_spec.rb
Ticket: [CPDNPQ-2753](https://dfedigital.atlassian.net/browse/CPDNPQ-2753)
We want to enable CSP in production
1. Replace use of inline styles for tracking pixels in `<head>`
2. Allow controlling whether to include tracking pixels via env var instead of hardcoding to production only, allows testing in earlier environments, including locally
[CPDNPQ-2753]: https://dfedigital.atlassian.net/browse/CPDNPQ-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2753] Avoid inline styles on tracking pixels

app/views/shared/analytics/_tracking_pixels.html.erb
Ticket: [CPDNPQ-2753](https://dfedigital.atlassian.net/browse/CPDNPQ-2753)
I used the wrong class name when changing how tracking pixels are hidden
1. use correct name
[CPDNPQ-2753]: https://dfedigital.atlassian.net/browse/CPDNPQ-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NPDNPQ-2753 fix wrong class causing pixels to show

public/api/docs/v1/swagger.yaml, public/api/docs/v2/swagger.yaml, public/api/docs/v3/swagger.yaml, spec/requests/api/docs/v3/declarations_spec.rb, spec/swagger_helper.rb, spec/swagger_schemas/models/participant_declaration.rb, spec/swagger_schemas/requests/v3/participant_declaration_change_delivery_partner_request.rb
Missing fields documentation - for `declaration` response and `change-delivery-partner` endpoint:
=> Add change-delivery-partner documentation - v3 only

config/environments/production.rb
We have hit the default flipper limit of 100 on the closed registration route:
https://dfe-teacher-services.sentry.io/issues/6593675525/?referrer=slack&notification_uuid=d42a8537-a82a-4f3b-877a-094ce3abc124&environment=production&alert_rule_id=14507801&alert_type=issue
Increase the limit to 1000
=> Increase Flipper limit actors

app/components/npq_separation/admin/adjustments_table_component.html.erb, app/components/npq_separation/admin/adjustments_table_component.rb, app/controllers/npq_separation/admin/finance/statements/adjustments_controller.rb, app/forms/admin/adjustments/destroy_adjustment_form.rb, app/forms/admin/adjustments/update_adjustment_form.rb, app/views/npq_separation/admin/finance/statements/adjustments/_adjustment_form.html.erb, app/views/npq_separation/admin/finance/statements/adjustments/delete.html.erb, app/views/npq_separation/admin/finance/statements/adjustments/edit.html.erb, app/views/npq_separation/admin/finance/statements/adjustments/index.html.erb, app/views/npq_separation/admin/finance/statements/adjustments/new.html.erb, app/views/npq_separation/admin/finance/statements/show.html.erb, config/locales/en.yml, config/routes.rb, spec/components/npq_separation/admin/adjustments_table_component_spec.rb, spec/features/npq_separation/admin/finance/adjustments_spec.rb, spec/forms/admin/adjustments/create_adjustment_form_spec.rb, spec/forms/admin/adjustments/destroy_adjustment_form_spec.rb, spec/forms/admin/adjustments/update_adjustment_form_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2767
Adding the ability to edit and delete adjustments.
There are 3 different flows to consider:
* editing and deleting adjustments whilst creating them - the adjustments index page only shows the adjustments created since leaving the statement page
* editing and deleting adjustments by clicking on the 'Change or remove' link on the statement page - the adjustments index page shows all adjustments
* creating adjustments by clicking the 'Change or remove` link on the statement page, and then choosing the 'Yes' radio button - this flow means all the adjustments are shown on the adjustments index page, and also the cancel links go to back to the adjustments index page
=> [CPDNPQ-2767] admin console - edit and delete adjustments

lib/tasks/delivery_partners.rake, spec/lib/tasks/delivery_partners_spec.rb
Ticket: [CPDNPQ-2832](https://dfedigital.atlassian.net/browse/CPDNPQ-2832)
We need to move delivery partner and delivery partnership data from Sandbox to Production so require a mechanism to both import and export those records
1. Add a rake task to export all Delivery Partners to a nominated CSV file
2. Add a rake task to export all Delivery Partnerships to a nominated CSV file
3. Add a rake task to import all Delivery Partners from a nominated CSV file
4. Add a rake task to import all Delivery Partnerships from a nominated CSV file
[CPDNPQ-2832]: https://dfedigital.atlassian.net/browse/CPDNPQ-2832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CPDNPQ-2832 Rake tasks for delivery partners

config/environments/review.rb, config/environments/sandbox.rb, config/environments/staging.rb, terraform/application/config/review.tfvars.json, terraform/application/config/sandbox.tfvars.json, terraform/application/config/staging.tfvars.json, terraform/application/variables.tf
We want to use redis instances for the cache in all environments so they more closely mimic production.
1. `staging` and `sandbox` environments are swapped to use 'real' azure redis instances
2. `review` apps are swapped to use a redis container instance in the 'test' AKS cluster (the same as we do with postgres at the moment)
An azure backed redis instance was created in earlier revisions of this PR to verify we can correctly create a real azure redis instance in the `staging` and `sandbox` environments
=> [CPDNPQ-2713] Use redis for review apps

config/environments/review.rb, config/environments/sandbox.rb, config/environments/staging.rb
When the new redis is created its not actually functional initially
1. Swap back to using memory store so the app continues to work even though redis isn't functional
=> [CPDNPQ-2713] Swap back to memory store for now for non-prod environments

config/environments/review.rb, config/environments/staging.rb
We want to use redis for the rails cache in staging and review environments
1. Removed the overrides to use the memory store
=> [CPDNPQ-2713] Use redis cache store for review and staging environments

config/locales/en.yml, spec/features/npq_separation/admin/feature_flags_spec.rb
Moving [this code](https://github.com/DFE-Digital/npq-registration/pull/2418) has resulted in a couple of broken links in the feature flags content. Changes in this PR:
- fix 2 links
- enhance the existing feature flags spec to alert us to the presence of links in feature flags descriptions, in case the links change again
=> Fix broken links in feature flags content

config/environments/sandbox.rb
We want to use redis for the rails cache in sandbox environment
1. Removed the overrides to use the memory store for `sandbox`
=> [CPDNPQ-2713] Use redis for cache in sandbox environment

config/application.rb
Ticket: BAU
We are using the Rails 7.1 framework and should use those defaults
1. Change from using the rails 7.0 defaults to the rails 7.1 defaults
failures:
=> [BAU] Use rails 7.1 defaults

terraform/application/config/production.tfvars.json
We are using a larger redis instance in production than required, downscaling will reduce costs
1. Downscaling from a P2 instance to a P1 instance
Rollout was tested by creating an equivalent 'real azure' redis in a review app then downscaling it and verifying there was no loss of connectivity
=> [CPDNPQ-2713] Downscale our production redis instance

app/components/npq_separation/navigation_structures/admin_navigation_structure.rb, app/controllers/npq_separation/admin/closed_registration_users_controller.rb, app/views/admin/_layout.html.erb, app/views/npq_separation/admin/closed_registration_users/destroy.html.erb, app/views/npq_separation/admin/closed_registration_users/index.html.erb, app/views/npq_separation/admin/closed_registration_users/new.html.erb, config/routes.rb, spec/features/service_closed_spec.rb
Ticket:
https://dfedigital.atlassian.net/browse/CPDNPQ-2769
We're gradually moving sections of the old admin console to the new admin console. This PR covers moving the 'Closed registration users' section. 
| Description              | Before | After |
| :---------------- | :------: | :----: |
| 'Closed registration users' is currently in the 'Legacy Admin' area - this PR moves it to the 'Separation Admin' area        |   ![Screenshot 2025-05-13 at 14 38 27](https://github.com/user-attachments/assets/ba4afb7f-a064-4fa4-b5a5-629affa60ac3)   | ![Screenshot 2025-05-13 at 14 35 41](https://github.com/user-attachments/assets/f105bd37-1d12-4955-b620-30e7bb023aff) |
=> Move 'Closed registration users' to new admin console

config/initializers/secure_headers.rb
Ticket: [CPDNPQ-2753](https://dfedigital.atlassian.net/browse/CPDNPQ-2753)
We want a working content security policy which we can turn into enforcement mode
1. Drop the old `insecure-inline` option from SecureHeaders output - this is for backwards compatibility but shouldn't be needed in 2025.
2. Add a hash for the default inline styling applied to plain text files in browsers. If robots.txt is crawled using a browser (likely chrome) then this will trigger an error whenever its called. Adding the hash solves that
[CPDNPQ-2753]: https://dfedigital.atlassian.net/browse/CPDNPQ-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CPDNPQ-2753 Disable nonce compat and allow plain text style

spec/features/admin/bulk_operations/update_and_verify_trns_spec.rb
Ticket: BAU
The update TRNs spec in bulk operations are sometimes failing
1. Ensure expected records are returned from database rather than relying on insert order which can be racy
=> [BAU] Fix flaky spec in bulk operations work

public/api/docs/v3/swagger.yaml, spec/swagger_schemas/requests/v3/participant_declaration_started_request.rb
Ticket: [CPDNPQ-2861](https://dfedigital.atlassian.net/browse/CPDNPQ-2861)
Most declarations going forward will require a `delivery_partner_id` so it makes sense to include it in the example
1. Include `delivery_partner_id` in the api docs example for creating a new declaration
[CPDNPQ-2861]: https://dfedigital.atlassian.net/browse/CPDNPQ-2861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2861] Include delivery_partner_id in the declarations example

app/views/layouts/api_docs.html.erb, app/views/layouts/api_guidance.html.erb, app/views/layouts/application.html.erb, app/views/layouts/shared/_head.html.erb, config/initializers/secure_headers.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2753
We are still getting reports through for the tracking pixels, this is a bit of an experiment to see if different ordering will help. I doubt it will but it shouldn't cause any issues either
1. Moved `data:` to end of `img_src` in content security policy
2. Added nonces to the swagger srcs
3. Moved tracking img's out of head - they aren't legimate in a HEAD tag anyway so shouldn't be there - maybe that might relate to the CSP errors?
=> [CPDNPQ-2753] More tweaks to content security policy

spec/support/matchers/component_matcher.rb
Ticket: BAU
We have a flaky spec which is failing on a call to the have_component matcher and its proving difficult to understand the source of the failure.
Improving the error message will help debug future occurrances of this flaky spec
1. Improved the error message for the `have_component` rspec matcher
failures:
=> [BAU] Improve error message from have_component matcher

terraform/domains/environment_domains/config/production.tfvars.json, terraform/domains/environment_domains/config/sandbox.tfvars.json, terraform/domains/environment_domains/main.tf, terraform/domains/environment_domains/variables.tf
Configure rate limiting for production & sandbox
Add global rate limit per IP for 5 minute intervals
Value for global rate set from checking ingress logs for the last 4 weeks plus and is not lower than the app rate limit
make production|sandbox domains-plan
https://trello.com/c/rmljcE5W/2345-add-rate-limiting-for-services
=> Add ingress rate limit

spec/factories/bulk_operation/reject_applications.rb, spec/factories/bulk_operation/revert_applications_to_pending.rb, spec/models/bulk_operation/reject_applications_spec.rb, spec/models/bulk_operation/revert_applications_to_pending_spec.rb, spec/models/bulk_operation_spec.rb
Sometimes, the bulk operations specs fail with an IOError
move tempfile creation into the spec, so it's still referenced whilst the spec is running, which should avoid it being garbage collected.
=> move tempfile creating into spec to stop it being garbage collected too early

lib/tasks/update_legacy_passed_participant_outcomes.rake, spec/lib/tasks/update_legacy_passed_participant_outcomes_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2803
This rake task will likely be used 2-4 times a year
Rake task to update legacy passed participant outcomes that have the specified TRN to a new TRN
=> [CPDNPQ-2803] rake task to update TRN on legacy passed participant outcomes

spec/support/matchers/component_matcher.rb
Ticket: BAU
We have a flaky spec on the statements page. This is caused by Lead Provider names (generated by Faker) sometimes having non ascii characters in them. This is resulting in escaped HTML for the rendered component we are expecting _but_ the browser is returning the unescaped version of the HTML.
1. Unescape the rendered HTML from the tests rendered copy of the component
=> [BAU] Fix flaky spec on statements page

app/components/npq_separation/navigation_structures/guidance_navigation_structure.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2791
Fixed the link to the roadmap page in the navigation.
Swapped an anchor link to page link.
failures:
=> Fix link to roadmap page in navigation

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Ticket: [CPDNPQ-2566](https://dfedigital.atlassian.net/browse/CPDNPQ-2566)
Discovered that the reviews page does not allow for blank lead provider approval statuses during testing of review_status feature on sandbox
1. Missing specs were added for the helper method
2. The helper method was corrected to handle being passed a nil status
[CPDNPQ-2566]: https://dfedigital.atlassian.net/browse/CPDNPQ-2566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-2566] Allow for nil #lead_provider_approval_status

app/components/npq_separation/navigation_structures/admin_navigation_structure.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2897
In some cases, 'Dashboard' is being underlined instead of the nav item that was selected.
For example, 'Bulk operations' is selected but 'Dashboard' is underlined:
Another example - 'Closed registration users' is selected but 'Dashboard' is underlined:
This PR fixes the 'prefix' sections in the nav component so that we're using the correct paths.
=> Ensure correct item is underlined in nav component

app/components/npq_separation/admin/statements_table_component.rb, app/components/npq_separation/application_tally_component.html.erb, app/components/npq_separation/application_tally_component.rb, app/components/npq_separation/navigation_structures/admin_navigation_structure.rb, app/services/applications/change_lead_provider.rb, app/views/npq_separation/admin/applications/change_lead_provider/show.html.erb, app/views/npq_separation/admin/applications/revert_to_pending/new.html.erb, app/views/npq_separation/admin/applications/reviews/show.html.erb, app/views/npq_separation/admin/applications/show.html.erb, app/views/npq_separation/admin/dashboards/summary/show.html.erb, app/views/npq_separation/admin/delivery_partners/index.html.erb, app/views/npq_separation/admin/delivery_partnerships/edit.html.erb, app/views/npq_separation/admin/finance/statements/adjustments/_adjustment_form.html.erb, app/views/npq_separation/admin/lead_providers/index.html.erb, app/views/npq_separation/admin/statements/create.html.erb, app/views/npq_separation/admin/statements/new.html.erb, config/locales/en.yml, spec/components/npq_separation/admin/statements_table_component_spec.rb, spec/components/npq_separation/application_tally_component_spec.rb, spec/components/npq_separation/navigation_structures/admin_navigation_structure_spec.rb, spec/features/npq_separation/admin/applications_in_review_spec.rb, spec/features/npq_separation/admin/applications_spec.rb, spec/features/npq_separation/admin/dashboards/summary_spec.rb, spec/features/npq_separation/admin/delivery_partnerships_spec.rb, spec/features/npq_separation/admin/lead_providers_spec.rb, spec/models/bulk_operation/revert_applications_to_pending_spec.rb, spec/services/applications/change_lead_provider_spec.rb, spec/services/one_off/migrate_declarations_between_statements_spec.rb, spec/views/npq_separation/admin/applications/show.html.erb_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2903
New side nav on the Course provider page.
All instances of the words "Lead provider" renamed to "Course provider" across the admin console.
API error messages and API guidance are left untouched.
=> [CPDNPQ-2903] course provider page and rename all instances of "Lead provider"

.github/workflows/deploy.yml
Ticket: BAU
If an update is pushed to a branch when terraform is deploying then the running terraform deploy is sent a kill signal. This leads to premature termination of the `terraform apply` and results in resources get created but not persisted in the tf state file.
Some of these resources we as team members cannot remove and require other teams such as infra to remove for us.
1. Prevent auto cancelling running workflows - _note: this will still cancel pending workflows so 3 pushes in quick succession will only result in a running workflow, plus a single pending one for the latest push_
failures:
=> [BAU] Prevent terraform apply from being cancelled prematurely

app/components/npq_separation/navigation_structures/admin_navigation_structure.rb, app/views/npq_separation/admin/finance/statements/show.html.erb, spec/features/npq_separation/admin/finance/statement_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2777
We're changing the way navigation works within the Finance section of the admin console. 
Removing Declarations and Contracts and adding Cohorts:
| ![Screenshot 2025-06-12 at 10 19 52](https://github.com/user-attachments/assets/fa09116e-2092-4645-b7bc-843b17c5302e)  | ![Screenshot 2025-06-12 at 10 20 34](https://github.com/user-attachments/assets/34276089-115c-4ed8-8b5c-0572242edbe1)    |
Adding extra side nav for show pages:
| ![Screenshot 2025-06-12 at 10 25 32](https://github.com/user-attachments/assets/509f82ae-4315-4dec-a921-ffd54fbd7410)  | ![Screenshot 2025-06-12 at 10 23 57](https://github.com/user-attachments/assets/ba0c3686-b6c3-485 …
=> WIP - edit finance side nav

app/models/api_token.rb, app/models/application.rb, app/models/application_state.rb, app/models/declaration.rb, app/models/ecf_sync_request_log.rb, app/models/get_an_identity/webhook_message.rb, app/models/participant_outcome.rb, app/models/user.rb, bin/rails, bin/rake, bin/setup, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/review.rb, config/environments/sandbox.rb, config/environments/staging.rb, config/environments/test.rb, config/initializers/assets.rb, config/initializers/filter_parameter_logging.rb, config/initializers/inflections.rb, config/initializers/permissions_policy.rb, spec/requests/api/documentation_controller_spec.rb
Ticket: [CPDNPQ-2905](https://dfedigital.atlassian.net/browse/CPDNPQ-2905)
We want to upgrade to Rails 7.2 in the near future, moving the application configs closer to the rails defaults will make upgrading them as part of the 7.2 upgrade more straight forward and reduce the change of running into odd behaviours because of legacy configs.
**Note:** this is the second attempt without enabling `force_ssl` - that will be enabled in a follow up PR
1. Swapped to using the new enum format for the application models
2. Use the new `:rescuable` option for errors in the test environment
3. Configure the activerecord session plugin across all environments for consistency
4. Standardised the environment configs on the Rails templates with the NPQ specific changes after
5. Dropped the environment …
=> Re-apply "[CPDNPQ-2905] config file updates"

.github/actions/deploy-environment-to-aks/action.yml, .github/actions/smoke-test/action.yml, .github/workflows/deploy.yml, .github/workflows/manual_deploy.yml, bin/smoke
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2931
We want to check the SHA being deployed is the expected one but currently we are checking it is the SHA of the branch being deployed. This causes problems with manual deploys - as part of testing it was discovered that manual deploys also continued on and deployed the subsequent environments.
The references to `current-commit-sha` are misleading in the manual deploy scenario where the current commit on the branch may not be the sha being deployed. This has also been renamed to avoid confusion.
1. The existing check was re-enabled
2. The manual_deploy step was moved to its own workflow - this resolves the manual deploy continuing on and deploying other later environments - whilst also avoiding waiting on spec runs and docker image …
=> [CPDNPQ-2931] Move manual_deploy to own workflow

app/assets/stylesheets/application.sass.scss
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2649
All links by default now will look gov links, even without `govuk-link` class.
=> Use gov-uk default style for p and a elements

app/controllers/registration_wizard_controller.rb, app/forms/questionnaires/ineligible_for_funding.rb, spec/features/journeys/happy_paths/basic_registration_journey_spec.rb, spec/features/journeys/happy_paths/when_referred_by_return_to_teaching_adviser_spec.rb, spec/features/journeys/happy_paths/when_working_in_other_spec.rb, spec/features/journeys/sad_paths/going_back_and_changing_referred_by_return_to_teaching_adviser_spec.rb, spec/support/helpers/journey_assertion_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2812
The main issue is that clicking 'Back' on our steps ends up going to the wrong page.
To reproduce the error in this ticket:
* go through journey answering 'No' at RTTA step: `course-start-date` -> `provider-check` -> `teacher-catchment` -> `work-setting` ('Other') -> `referred-by-return-to-teaching-adviser` ('No') -> `choose-your-npq` ('senior-leadership') -> `ineligible-for-funding` -> `funding-your-npq`
* click 'Back' until you get to the work-setting: `funding-your-npq` -> `ineligible-for-funding` -> `choose-your-npq` -> `work-setting`
* go forwards again, but answer 'Yes' at the RTTA step:` work-setting` -> `referred-by-return-to-teaching-adviser` (yes) -> `choose-your-npq `-> `possible-funding` -> `choose-your-provider`
* …
=> [CPDNPQ-2812] handle error scenario

app/services/declarations/create.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2808
Bullet::Notification::UnoptimizedQueryError seen in sentry on review apps
I did see the issue locally, once,
but when I tried to reproduce the issue again on a reseeded database, I could not reproduce the error.
Adding a reload fixed the problem when I did have it locally - I've no idea why.
=> [CPDNPQ-2808] fix n+1 query

spec/services/applications/query_spec.rb
occasional failure of spec: `spec/services/applications/query_spec.rb:362`
specify previous cohort, otherwise the cohort factory will attempt to update the existing current cohort, which causes the validation failure.
=> fix flaky spec - specify cohort, so that factory does not attempt to update current cohort

app/forms/admin/adjustments/concerns/adjustment_form.rb, app/forms/admin/adjustments/create_adjustment_form.rb, app/forms/admin/adjustments/destroy_adjustment_form.rb, app/forms/admin/adjustments/update_adjustment_form.rb, app/models/statement.rb, app/services/statements/summary_calculator.rb, app/views/npq_separation/admin/finance/statements/show.html.erb, config/locales/en.yml, db/seeds/base/process_statements.rb, spec/features/npq_separation/admin/finance/adjustments_spec.rb, spec/features/npq_separation/admin/finance/statement_payment_spec.rb, spec/forms/admin/adjustments/create_adjustment_form_spec.rb, spec/forms/admin/adjustments/destroy_adjustment_form_spec.rb, spec/forms/admin/adjustments/update_adjustment_form_spec.rb, spec/models/statement_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2991
Adjustments are allowed, all the way up until a statement is marked as paid.
You cannot make adjustments now if the statement is in state `paid`.
In production:
statements from 2021 to 2022 never have `marked_as_paid_at` set, because this change was introduced in 2023.
statements from 2023 have a mixture of `marked_as_paid_at`:`nil` and `marked_as_paid_at` set.
statements from 2024 onwards always have `marked_as_paid_at` set.
I've made the seeds always set `marked_as_paid_at` for statements 2023 onwards, so they better reflect what we have in production.
I've renamed the method `statement#marked_as_paid?`, to `statement#has_marked_as_paid_at_date?` - because it was confusing and wrong before - the method is only used to decide …
=> [CPDNPQ-2991] change when manual adjustments allowed

app/services/applications/accept.rb, config/locales/en.yml, db/seeds/base/add_schedules.rb, spec/services/applications/accept_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2811
currently, 3 scenarios are covered by the "Schedule cannot be determined" error:
1. A schedule identifier has been specified when accepting the application, but that schedule does not exist in the application's cohort - this is something under the user's control - they can specify a different identifier, or not specify one, and we'll determine the correct schedule.
2. No schedule identifier has been specified, and we have not been able to determine what schedule to use - this is a problem on our end.
3. When the selected schedule is not valid for the application's course, we currently show 2 errors: "The selected schedule is not valid for the course" and "Schedule cannot be determined" - we shouldn't be showing the second error …
=> [CPDNPQ-2811] application accept error messages

app/controllers/registration_wizard_controller.rb, app/models/registration_wizard.rb, spec/features/journeys/sad_paths/step_does_not_exist_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2771
certain steps were removed from the journey, but we still get requests to these steps
For the removed steps, redirect to the course-start-date step.
For other steps, continue to raise the `InvalidStep` error.
=> [CPDNPQ-2771] redirect to start when removed step

app/views/accounts/_course_details.html.erb
Ticket: BAU
These are debug only links and the pages they link through to have now been removed. This causes these pages to refuse to render on review apps
1. Removed debug code
failures:
=> [BAU] Fix remove review app only debug links

app/views/npq_separation/admin/applications/show.html.erb, spec/features/npq_separation/admin/applications_spec.rb, spec/views/npq_separation/admin/applications/show.html.erb_spec.rb
Add schedule identifier row to the funding eligibility section on the application show page.
Admins need this info when investigating queries and bugs.
ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3071
=> Add new row for schedule identifier to the application show page

app/views/npq_separation/admin/applications/_user.html.erb, spec/views/npq_separation/admin/applications/show.html.erb_spec.rb
Ticket: BAU
Currently if a user account is lacking a date of birth the show page for their application produces and error
1. Fall back to showing 'Not provided'
2. Added spec for scenario
failures:
=> [BAU] Handle users without date of birth present

app/components/npq_separation/admin/history_component.rb, spec/components/npq_separation/admin/history_component_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3034
application history doesn't work for some applications
cope with application.versions that don't have any object_changes
=> [CPDNPQ-3034] bugfix - cope with versions with no object_changes

app/components/npq_separation/admin/adjustments_table_component.html.erb, spec/components/npq_separation/admin/adjustments_table_component_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3097
We do not want minus numbers to wrap over two lines. Resolving this by using a non-breaking hyphen.
=> Prevent line break between minus sign and pound symbol in currency formatting

app/services/applications/change_training_status.rb, app/views/npq_separation/admin/applications/change_training_statuses/new.html.erb, app/views/npq_separation/admin/applications/show.html.erb, config/locales/en.yml, spec/services/applications/change_training_status_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3119
When the provider approvial status is in pending, i.e. it has not yet been set:
- do not show change link next to 'Training status' - people should not be able to change the training status in this scenario
- add a dash next to 'Training status' - we use a dash throughout the admin console when a status is not yet set
| <img width="878" height="91" alt="Screenshot 2025-08-05 at 17 05 58" src="https://github.com/user-attachments/assets/fb31e6db-c5b4-4e2f-9ec9-296bea42f6c4" />  | <img width="969" height="101" alt="Screenshot 2025-08-05 at 17 04 06" src="https://github.com/user-attachments/assets/f9d30a79-e3a9-4269-b656-94e1594df0b3" />    |
Account for the scenario where you could still …
=> Ensure that training status cannot be set when provider approval status is pending

spec/factories/schools.rb, spec/services/funding_eligibility_spec.rb
occasional failure in funding_eligibility_spec:
`rspec ./spec/services/funding_eligibility_spec.rb[1:15:38:2:5:1:2]` # FundingEligibility when institution is a School when school is LA nursery when not LA disadvantaged nursery when user has selected the early_years_leadership course behaves like funding eligibility returns funding_eligiblity_status_code not_entitled_ey_institution
The URN was previously just a number, and occasionally it would match a URN from LA_DISADVANTAGED_NURSERIES.
This PR changes the factory so URNs and UKPRNs start with 'TEST', so they will never match a URN from the PP50 lists.
=> fix flaky spec

app/controllers/application_controller.rb, app/models/null_user.rb, spec/controllers/controllers_spec.rb
Ticket: [CPDNPQ-3171](https://dfedigital.atlassian.net/browse/CPDNPQ-3171]
We have had a user in Staging unable to restore an old session because they have a NullUser persisted in the :registration_store key
1. Restore the `NullUser` to allow sessions to be successfully restored
2. Clear out the old bad session and redirect the user to the homepage
[CPDNPQ-3171]: https://dfedigital.atlassian.net/browse/CPDNPQ-3171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-3171] Session restore error

app/views/npq_separation/admin/users/_application.html.erb, app/views/npq_separation/admin/users/show.html.erb, spec/features/npq_separation/admin/users_spec.rb
Bug fix to stop the H2 'Applications' getting repeated above each summary card on the users show page.
=> H2 'Applications' is getting repeated with each summary card 

app/services/users/find_or_create_from_provider_data.rb, spec/models/user_spec.rb, spec/services/users/find_or_create_from_provider_data_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2984
In very rare cases, GAI user can have cased email that clashes with an existing user, eg GAI returns `FOO@example.com` and our database already have `foo@example.com`. This results in a validation error.
The proposed code fixes the issue. Please note that device gem is downcasing all our emails before saving them - hence regression spec in `user_spec.rb`.
=> Handle cased emails from GAI properly

app/controllers/api/v1/get_an_identity/webhook_messages_controller.rb, app/controllers/npq_separation/admin/webhook_messages/processing_jobs_controller.rb, app/decorators/get_an_identity/webhook_messages/user_updated_decorator.rb, app/helpers/webhook_messages_helper.rb, app/models/user.rb, app/services/get_an_identity_service/webhooks/user_updated_processor.rb, app/services/participants/change_trn.rb, app/services/users/find_or_create_from_provider_data.rb, app/views/npq_separation/admin/webhook_messages/index.html.erb, app/views/npq_separation/admin/webhook_messages/show.html.erb, config/locales/en.yml, spec/factories/get_an_identity_webhook_messages.rb, spec/features/npq_separation/admin/webhook_messages_spec.rb, spec/models/user_spec.rb, spec/services/get_an_identity_service/webhooks/user_updated_processor_spec.rb, spec/services/participants/change_trn_spec.rb, spec/services/users/find_or_create_from_provider_data_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3025
* the message format of the webhook message has changed
* we did not used to use the preferred name (we do when the user first logs in) - this has been fixed
* the admin console webhook messages pages had the wrong path names
* make GAI syncing and login code use same logic when updating TRN/trn_verified/trn_lookup_status - this logic is now in the `User` model
* add missing specs for webhook messages pages on admin console
=> [CPDNPQ-3025] enable GAI syncing - update message format and fix admin console

spec/factories/declarations.rb, spec/factories/schedules.rb, spec/features/npq_separation/admin/applications/applications_spec.rb, spec/lib/tasks/update_application_spec.rb, spec/services/declarations/create_spec.rb, spec/services/statements/summary_calculator_spec.rb
Ticket: [CPDNPQ-3193](https://dfedigital.atlassian.net/browse/CPDNPQ-3193)
Our specs are failing on `main`
1. Fixes to various specs which were relying on `create(:cohort, :current)` to always return the same value which isn't true if things like `travel_to` are used
2. Refactored some of the specs to improve readability and clarify why some specs were failing
3. Explicitly fail if the `void` service silently with invalid data
[CPDNPQ-3193]: https://dfedigital.atlassian.net/browse/CPDNPQ-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDNPQ-3193] fix failing specs

app/components/npq_separation/admin/statement_selector_component.html.erb, app/components/npq_separation/admin/statement_selector_component.rb, app/components/npq_separation/admin/statements_table_component.rb, app/controllers/npq_separation/admin/finance/statements_controller.rb, app/views/npq_separation/admin/finance/statements/show.html.erb, config/locales/en.yml, spec/components/npq_separation/admin/statement_selector_component_spec.rb, spec/requests/npq_separation/admin/finance/statements_controller_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3140
* show `output_fee` on the statements page, as "Payment run"
* add a filter for Payment run
* increased test coverage on `StatementSelectorComponent` to 100%
* show Payment run on the statement page
=> [CPDNPQ-3140] admin console statements page - add filter for output_fee

app/controllers/npq_separation/admin/cohorts_controller.rb, app/services/exporters/contracts.rb, app/services/one_off/update_contracts.rb, app/services/statements/bulk_creator/contract_row.rb, app/views/npq_separation/admin/cohorts/show.html.erb, config/routes.rb, spec/features/npq_separation/admin/cohorts_spec.rb, spec/features/npq_separation/admin/creating_statements_spec.rb, spec/requests/npq_separation/admin/cohorts_controller_spec.rb, spec/services/exporters/contracts_spec.rb, spec/services/one_off/update_contracts_spec.rb, spec/support/helpers/file_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2706
* allow contracts CSV to be download via the admin console - via the cohort screens
* update our `OneOff::UpdateContracts` which is used in rake tasks to support the same CSV headers as we use for creating contracts via the admin console.
=> [CPDNPQ-2706] download contracts CSV

app/controllers/npq_separation/admin/delivery_partners_controller.rb, app/forms/admin/delivery_partners/continue_form.rb, app/models/delivery_partner.rb, app/services/admin_service/delivery_partners_search.rb, app/views/npq_separation/admin/delivery_partners/similar.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20250910144739_install_fuzzy_str_match_extension.rb, db/schema.rb, spec/features/npq_separation/admin/delivery_partners_spec.rb, spec/forms/admin/delivery_partners/continue_form_spec.rb, spec/models/delivery_partner_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2722
* when creating a delivery partner, check for similar matching names
* methods used to match:
* wildcard match using first word (with and without any leading 'The')
* wildcard match using '%name%' - same method used in delivery partner search
* levenshtein match - for any typos
=> [CPDNPQ-2722] delivery partner name similarity matching

app/jobs/stream_api_requests_to_big_query_job.rb, spec/jobs/stream_api_requests_to_big_query_job_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3224
* stop logging the job arguments for `StreamAPIRequestsToBigQueryJob` - it seems redundant - the same parameters end up in BigQuery anyway
=> [CPDNPQ-3224] stop PII leaking into logs from webhook job logging

spec/services/exporters/contracts_spec.rb
seeing an occasional failure in `spec/services/exporters/contracts_spec.rb` - e.g.: https://github.com/DFE-Digital/npq-registration/actions/runs/17860355308/job/50789209183
use `contain_exactly` to make the spec not care about the order of the contracts returned.
=> fix flaky contracts exporter spec

app/views/npq_separation/admin/applications/show.html.erb, spec/views/npq_separation/admin/applications/show.html.erb_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3260
Delivery partner will not always be set and we shouldn't be assuming that it is
1. Handle when delivery partner is nil
2. Generate declarations of both types in view specs
=> [CPDNPQ-3260] Fix Admin::Applications#show not handling blank delivery partner

app/views/api/guidance/test-environments.md
Ticket: BAU
I've found a couple of links in the API guidance to the old versions of the API
1. Remove those links
=> [BAU] Remove old test environment links

app/controllers/api/guidance_controller.rb, app/controllers/errors_controller.rb, spec/requests/api/errors_spec.rb, spec/requests/api/guidance_controller_spec.rb, spec/requests/api/teacher_record_service/qualifications_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2910
- catch the `ActionView::MissingTemplate` for the `API::GuidanceController#show` and raise a `ActionController::RoutingError`, which results in a 404 response.
- make sure error pages for `/api/guidance/` and `/api/docs/` are in HTML not JSON.
=> [CPDNPQ-2910] raise RoutingError when no template found

app/services/admin_service/delivery_partners_search.rb, app/views/npq_separation/admin/delivery_partners/index.html.erb, spec/services/admin_service/delivery_partners_search_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-3148
Admin users need to search for delivery partners by ID.
- Expanded the existing delivery partner search scope so that you can search by ecf_id as well as name. 
- Added tests to check for different scenarios when searching by ecf_id, such as searching in uppercase or without hyphens.
- Updated the hint text copy to reflect the change in how you can search.
=> Search for delivery partners by ecf_id as well as name
